// tbclient.AddPost.AddPostResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: AddPostResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPostResIdl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *AddPostResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostResIdl) Reset() {
	*x = AddPostResIdl{}
	mi := &file_AddPostResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostResIdl) ProtoMessage() {}

func (x *AddPostResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_AddPostResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostResIdl.ProtoReflect.Descriptor instead.
func (*AddPostResIdl) Descriptor() ([]byte, []int) {
	return file_AddPostResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *AddPostResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AddPostResIdl) GetData() *AddPostResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddPostResIdl_DataRes struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	VideoId       string                              `protobuf:"bytes,4,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Msg           string                              `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	PreMsg        string                              `protobuf:"bytes,6,opt,name=pre_msg,json=preMsg,proto3" json:"pre_msg,omitempty"`
	ColorMsg      string                              `protobuf:"bytes,7,opt,name=color_msg,json=colorMsg,proto3" json:"color_msg,omitempty"`
	Info          *AddPostResIdl_DataRes_PostAntiInfo `protobuf:"bytes,14,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostResIdl_DataRes) Reset() {
	*x = AddPostResIdl_DataRes{}
	mi := &file_AddPostResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostResIdl_DataRes) ProtoMessage() {}

func (x *AddPostResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_AddPostResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*AddPostResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_AddPostResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AddPostResIdl_DataRes) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *AddPostResIdl_DataRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AddPostResIdl_DataRes) GetPreMsg() string {
	if x != nil {
		return x.PreMsg
	}
	return ""
}

func (x *AddPostResIdl_DataRes) GetColorMsg() string {
	if x != nil {
		return x.ColorMsg
	}
	return ""
}

func (x *AddPostResIdl_DataRes) GetInfo() *AddPostResIdl_DataRes_PostAntiInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type AddPostResIdl_DataRes_PostAntiInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeedVcode     string                 `protobuf:"bytes,3,opt,name=need_vcode,json=needVcode,proto3" json:"need_vcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostResIdl_DataRes_PostAntiInfo) Reset() {
	*x = AddPostResIdl_DataRes_PostAntiInfo{}
	mi := &file_AddPostResIdl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostResIdl_DataRes_PostAntiInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostResIdl_DataRes_PostAntiInfo) ProtoMessage() {}

func (x *AddPostResIdl_DataRes_PostAntiInfo) ProtoReflect() protoreflect.Message {
	mi := &file_AddPostResIdl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostResIdl_DataRes_PostAntiInfo.ProtoReflect.Descriptor instead.
func (*AddPostResIdl_DataRes_PostAntiInfo) Descriptor() ([]byte, []int) {
	return file_AddPostResIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *AddPostResIdl_DataRes_PostAntiInfo) GetNeedVcode() string {
	if x != nil {
		return x.NeedVcode
	}
	return ""
}

var File_AddPostResIdl_proto protoreflect.FileDescriptor

const file_AddPostResIdl_proto_rawDesc = "" +
	"\n" +
	"\x13AddPostResIdl.proto\x1a\vError.proto\"\xb0\x02\n" +
	"\rAddPostResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x12*\n" +
	"\x04data\x18\x02 \x01(\v2\x16.AddPostResIdl.DataResR\x04data\x1a\xd4\x01\n" +
	"\aDataRes\x12\x19\n" +
	"\bvideo_id\x18\x04 \x01(\tR\avideoId\x12\x10\n" +
	"\x03msg\x18\x05 \x01(\tR\x03msg\x12\x17\n" +
	"\apre_msg\x18\x06 \x01(\tR\x06preMsg\x12\x1b\n" +
	"\tcolor_msg\x18\a \x01(\tR\bcolorMsg\x127\n" +
	"\x04info\x18\x0e \x01(\v2#.AddPostResIdl.DataRes.PostAntiInfoR\x04info\x1a-\n" +
	"\fPostAntiInfo\x12\x1d\n" +
	"\n" +
	"need_vcode\x18\x03 \x01(\tR\tneedVcodeB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_AddPostResIdl_proto_rawDescOnce sync.Once
	file_AddPostResIdl_proto_rawDescData []byte
)

func file_AddPostResIdl_proto_rawDescGZIP() []byte {
	file_AddPostResIdl_proto_rawDescOnce.Do(func() {
		file_AddPostResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AddPostResIdl_proto_rawDesc), len(file_AddPostResIdl_proto_rawDesc)))
	})
	return file_AddPostResIdl_proto_rawDescData
}

var file_AddPostResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_AddPostResIdl_proto_goTypes = []any{
	(*AddPostResIdl)(nil),                      // 0: AddPostResIdl
	(*AddPostResIdl_DataRes)(nil),              // 1: AddPostResIdl.DataRes
	(*AddPostResIdl_DataRes_PostAntiInfo)(nil), // 2: AddPostResIdl.DataRes.PostAntiInfo
	(*Error)(nil),                              // 3: Error
}
var file_AddPostResIdl_proto_depIdxs = []int32{
	3, // 0: AddPostResIdl.error:type_name -> Error
	1, // 1: AddPostResIdl.data:type_name -> AddPostResIdl.DataRes
	2, // 2: AddPostResIdl.DataRes.info:type_name -> AddPostResIdl.DataRes.PostAntiInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_AddPostResIdl_proto_init() }
func file_AddPostResIdl_proto_init() {
	if File_AddPostResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AddPostResIdl_proto_rawDesc), len(file_AddPostResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AddPostResIdl_proto_goTypes,
		DependencyIndexes: file_AddPostResIdl_proto_depIdxs,
		MessageInfos:      file_AddPostResIdl_proto_msgTypes,
	}.Build()
	File_AddPostResIdl_proto = out.File
	file_AddPostResIdl_proto_goTypes = nil
	file_AddPostResIdl_proto_depIdxs = nil
}
