// tbclient.AddPost.AddPostReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: AddPostReqIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPostReqIdl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AddPostReqIdl_DataReq `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostReqIdl) Reset() {
	*x = AddPostReqIdl{}
	mi := &file_AddPostReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostReqIdl) ProtoMessage() {}

func (x *AddPostReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_AddPostReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostReqIdl.ProtoReflect.Descriptor instead.
func (*AddPostReqIdl) Descriptor() ([]byte, []int) {
	return file_AddPostReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *AddPostReqIdl) GetData() *AddPostReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddPostReqIdl_DataReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Common           *CommonReq             `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Anonymous        string                 `protobuf:"bytes,6,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	CanNoForum       string                 `protobuf:"bytes,7,opt,name=can_no_forum,json=canNoForum,proto3" json:"can_no_forum,omitempty"`
	IsFeedback       string                 `protobuf:"bytes,8,opt,name=is_feedback,json=isFeedback,proto3" json:"is_feedback,omitempty"`
	TakephotoNum     string                 `protobuf:"bytes,9,opt,name=takephoto_num,json=takephotoNum,proto3" json:"takephoto_num,omitempty"`
	EntranceType     string                 `protobuf:"bytes,10,opt,name=entrance_type,json=entranceType,proto3" json:"entrance_type,omitempty"`
	VcodeTag         string                 `protobuf:"bytes,16,opt,name=vcode_tag,json=vcodeTag,proto3" json:"vcode_tag,omitempty"`
	NewVcode         string                 `protobuf:"bytes,18,opt,name=new_vcode,json=newVcode,proto3" json:"new_vcode,omitempty"`
	Content          string                 `protobuf:"bytes,19,opt,name=content,proto3" json:"content,omitempty"`
	Fid              string                 `protobuf:"bytes,26,opt,name=fid,proto3" json:"fid,omitempty"`
	VFid             string                 `protobuf:"bytes,28,opt,name=v_fid,json=vFid,proto3" json:"v_fid,omitempty"`
	VFname           string                 `protobuf:"bytes,29,opt,name=v_fname,json=vFname,proto3" json:"v_fname,omitempty"`
	Kw               string                 `protobuf:"bytes,30,opt,name=kw,proto3" json:"kw,omitempty"`
	IsBarrage        string                 `protobuf:"bytes,31,opt,name=is_barrage,json=isBarrage,proto3" json:"is_barrage,omitempty"`
	BarrageTime      string                 `protobuf:"bytes,32,opt,name=barrage_time,json=barrageTime,proto3" json:"barrage_time,omitempty"`
	FromFourmId      string                 `protobuf:"bytes,44,opt,name=from_fourm_id,json=fromFourmId,proto3" json:"from_fourm_id,omitempty"`
	Tid              string                 `protobuf:"bytes,45,opt,name=tid,proto3" json:"tid,omitempty"`
	IsAd             string                 `protobuf:"bytes,51,opt,name=is_ad,json=isAd,proto3" json:"is_ad,omitempty"`
	PostFrom         string                 `protobuf:"bytes,55,opt,name=post_from,json=postFrom,proto3" json:"post_from,omitempty"`
	NameShow         string                 `protobuf:"bytes,58,opt,name=name_show,json=nameShow,proto3" json:"name_show,omitempty"`
	IsPictxt         string                 `protobuf:"bytes,60,opt,name=is_pictxt,json=isPictxt,proto3" json:"is_pictxt,omitempty"`
	ShowCustomFigure int32                  `protobuf:"varint,64,opt,name=show_custom_figure,json=showCustomFigure,proto3" json:"show_custom_figure,omitempty"`
	IsShowBless      int32                  `protobuf:"varint,67,opt,name=is_show_bless,json=isShowBless,proto3" json:"is_show_bless,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddPostReqIdl_DataReq) Reset() {
	*x = AddPostReqIdl_DataReq{}
	mi := &file_AddPostReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostReqIdl_DataReq) ProtoMessage() {}

func (x *AddPostReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_AddPostReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*AddPostReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_AddPostReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AddPostReqIdl_DataReq) GetCommon() *CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *AddPostReqIdl_DataReq) GetAnonymous() string {
	if x != nil {
		return x.Anonymous
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetCanNoForum() string {
	if x != nil {
		return x.CanNoForum
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetIsFeedback() string {
	if x != nil {
		return x.IsFeedback
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetTakephotoNum() string {
	if x != nil {
		return x.TakephotoNum
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetEntranceType() string {
	if x != nil {
		return x.EntranceType
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetVcodeTag() string {
	if x != nil {
		return x.VcodeTag
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetNewVcode() string {
	if x != nil {
		return x.NewVcode
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetVFid() string {
	if x != nil {
		return x.VFid
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetVFname() string {
	if x != nil {
		return x.VFname
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetKw() string {
	if x != nil {
		return x.Kw
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetIsBarrage() string {
	if x != nil {
		return x.IsBarrage
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetBarrageTime() string {
	if x != nil {
		return x.BarrageTime
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetFromFourmId() string {
	if x != nil {
		return x.FromFourmId
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetIsAd() string {
	if x != nil {
		return x.IsAd
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetPostFrom() string {
	if x != nil {
		return x.PostFrom
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetNameShow() string {
	if x != nil {
		return x.NameShow
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetIsPictxt() string {
	if x != nil {
		return x.IsPictxt
	}
	return ""
}

func (x *AddPostReqIdl_DataReq) GetShowCustomFigure() int32 {
	if x != nil {
		return x.ShowCustomFigure
	}
	return 0
}

func (x *AddPostReqIdl_DataReq) GetIsShowBless() int32 {
	if x != nil {
		return x.IsShowBless
	}
	return 0
}

var File_AddPostReqIdl_proto protoreflect.FileDescriptor

const file_AddPostReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x13AddPostReqIdl.proto\x1a\x0fCommonReq.proto\"\xf0\x05\n" +
	"\rAddPostReqIdl\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.AddPostReqIdl.DataReqR\x04data\x1a\xb2\x05\n" +
	"\aDataReq\x12\"\n" +
	"\x06common\x18\x01 \x01(\v2\n" +
	".CommonReqR\x06common\x12\x1c\n" +
	"\tanonymous\x18\x06 \x01(\tR\tanonymous\x12 \n" +
	"\fcan_no_forum\x18\a \x01(\tR\n" +
	"canNoForum\x12\x1f\n" +
	"\vis_feedback\x18\b \x01(\tR\n" +
	"isFeedback\x12#\n" +
	"\rtakephoto_num\x18\t \x01(\tR\ftakephotoNum\x12#\n" +
	"\rentrance_type\x18\n" +
	" \x01(\tR\fentranceType\x12\x1b\n" +
	"\tvcode_tag\x18\x10 \x01(\tR\bvcodeTag\x12\x1b\n" +
	"\tnew_vcode\x18\x12 \x01(\tR\bnewVcode\x12\x18\n" +
	"\acontent\x18\x13 \x01(\tR\acontent\x12\x10\n" +
	"\x03fid\x18\x1a \x01(\tR\x03fid\x12\x13\n" +
	"\x05v_fid\x18\x1c \x01(\tR\x04vFid\x12\x17\n" +
	"\av_fname\x18\x1d \x01(\tR\x06vFname\x12\x0e\n" +
	"\x02kw\x18\x1e \x01(\tR\x02kw\x12\x1d\n" +
	"\n" +
	"is_barrage\x18\x1f \x01(\tR\tisBarrage\x12!\n" +
	"\fbarrage_time\x18  \x01(\tR\vbarrageTime\x12\"\n" +
	"\rfrom_fourm_id\x18, \x01(\tR\vfromFourmId\x12\x10\n" +
	"\x03tid\x18- \x01(\tR\x03tid\x12\x13\n" +
	"\x05is_ad\x183 \x01(\tR\x04isAd\x12\x1b\n" +
	"\tpost_from\x187 \x01(\tR\bpostFrom\x12\x1b\n" +
	"\tname_show\x18: \x01(\tR\bnameShow\x12\x1b\n" +
	"\tis_pictxt\x18< \x01(\tR\bisPictxt\x12,\n" +
	"\x12show_custom_figure\x18@ \x01(\x05R\x10showCustomFigure\x12\"\n" +
	"\ris_show_bless\x18C \x01(\x05R\visShowBlessB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_AddPostReqIdl_proto_rawDescOnce sync.Once
	file_AddPostReqIdl_proto_rawDescData []byte
)

func file_AddPostReqIdl_proto_rawDescGZIP() []byte {
	file_AddPostReqIdl_proto_rawDescOnce.Do(func() {
		file_AddPostReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AddPostReqIdl_proto_rawDesc), len(file_AddPostReqIdl_proto_rawDesc)))
	})
	return file_AddPostReqIdl_proto_rawDescData
}

var file_AddPostReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_AddPostReqIdl_proto_goTypes = []any{
	(*AddPostReqIdl)(nil),         // 0: AddPostReqIdl
	(*AddPostReqIdl_DataReq)(nil), // 1: AddPostReqIdl.DataReq
	(*CommonReq)(nil),             // 2: CommonReq
}
var file_AddPostReqIdl_proto_depIdxs = []int32{
	1, // 0: AddPostReqIdl.data:type_name -> AddPostReqIdl.DataReq
	2, // 1: AddPostReqIdl.DataReq.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_AddPostReqIdl_proto_init() }
func file_AddPostReqIdl_proto_init() {
	if File_AddPostReqIdl_proto != nil {
		return
	}
	file_CommonReq_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AddPostReqIdl_proto_rawDesc), len(file_AddPostReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AddPostReqIdl_proto_goTypes,
		DependencyIndexes: file_AddPostReqIdl_proto_depIdxs,
		MessageInfos:      file_AddPostReqIdl_proto_msgTypes,
	}.Build()
	File_AddPostReqIdl_proto = out.File
	file_AddPostReqIdl_proto_goTypes = nil
	file_AddPostReqIdl_proto_depIdxs = nil
}
