// protobuf.CommitPersonalMsg.CommitPersonalMsgResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: CommitPersonalMsgResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommitPersonalMsgResIdl struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Error         *Error                           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *CommitPersonalMsgResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPersonalMsgResIdl) Reset() {
	*x = CommitPersonalMsgResIdl{}
	mi := &file_CommitPersonalMsgResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPersonalMsgResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPersonalMsgResIdl) ProtoMessage() {}

func (x *CommitPersonalMsgResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_CommitPersonalMsgResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPersonalMsgResIdl.ProtoReflect.Descriptor instead.
func (*CommitPersonalMsgResIdl) Descriptor() ([]byte, []int) {
	return file_CommitPersonalMsgResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *CommitPersonalMsgResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CommitPersonalMsgResIdl) GetData() *CommitPersonalMsgResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommitPersonalMsgResIdl_DataRes struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	MsgId         int64                                      `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	BlockInfo     *CommitPersonalMsgResIdl_DataRes_BlockInfo `protobuf:"bytes,6,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPersonalMsgResIdl_DataRes) Reset() {
	*x = CommitPersonalMsgResIdl_DataRes{}
	mi := &file_CommitPersonalMsgResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPersonalMsgResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPersonalMsgResIdl_DataRes) ProtoMessage() {}

func (x *CommitPersonalMsgResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_CommitPersonalMsgResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPersonalMsgResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*CommitPersonalMsgResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_CommitPersonalMsgResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CommitPersonalMsgResIdl_DataRes) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *CommitPersonalMsgResIdl_DataRes) GetBlockInfo() *CommitPersonalMsgResIdl_DataRes_BlockInfo {
	if x != nil {
		return x.BlockInfo
	}
	return nil
}

type CommitPersonalMsgResIdl_DataRes_BlockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockErrno    int32                  `protobuf:"varint,1,opt,name=blockErrno,proto3" json:"blockErrno,omitempty"`
	BlockErrmsg   string                 `protobuf:"bytes,2,opt,name=blockErrmsg,proto3" json:"blockErrmsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPersonalMsgResIdl_DataRes_BlockInfo) Reset() {
	*x = CommitPersonalMsgResIdl_DataRes_BlockInfo{}
	mi := &file_CommitPersonalMsgResIdl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPersonalMsgResIdl_DataRes_BlockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPersonalMsgResIdl_DataRes_BlockInfo) ProtoMessage() {}

func (x *CommitPersonalMsgResIdl_DataRes_BlockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_CommitPersonalMsgResIdl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPersonalMsgResIdl_DataRes_BlockInfo.ProtoReflect.Descriptor instead.
func (*CommitPersonalMsgResIdl_DataRes_BlockInfo) Descriptor() ([]byte, []int) {
	return file_CommitPersonalMsgResIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CommitPersonalMsgResIdl_DataRes_BlockInfo) GetBlockErrno() int32 {
	if x != nil {
		return x.BlockErrno
	}
	return 0
}

func (x *CommitPersonalMsgResIdl_DataRes_BlockInfo) GetBlockErrmsg() string {
	if x != nil {
		return x.BlockErrmsg
	}
	return ""
}

var File_CommitPersonalMsgResIdl_proto protoreflect.FileDescriptor

const file_CommitPersonalMsgResIdl_proto_rawDesc = "" +
	"\n" +
	"\x1dCommitPersonalMsgResIdl.proto\x1a\vError.proto\"\xa8\x02\n" +
	"\x17CommitPersonalMsgResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x124\n" +
	"\x04data\x18\x02 \x01(\v2 .CommitPersonalMsgResIdl.DataResR\x04data\x1a\xb8\x01\n" +
	"\aDataRes\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x03R\x05msgId\x12H\n" +
	"\tblockInfo\x18\x06 \x01(\v2*.CommitPersonalMsgResIdl.DataRes.BlockInfoR\tblockInfo\x1aM\n" +
	"\tBlockInfo\x12\x1e\n" +
	"\n" +
	"blockErrno\x18\x01 \x01(\x05R\n" +
	"blockErrno\x12 \n" +
	"\vblockErrmsg\x18\x02 \x01(\tR\vblockErrmsgB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_CommitPersonalMsgResIdl_proto_rawDescOnce sync.Once
	file_CommitPersonalMsgResIdl_proto_rawDescData []byte
)

func file_CommitPersonalMsgResIdl_proto_rawDescGZIP() []byte {
	file_CommitPersonalMsgResIdl_proto_rawDescOnce.Do(func() {
		file_CommitPersonalMsgResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CommitPersonalMsgResIdl_proto_rawDesc), len(file_CommitPersonalMsgResIdl_proto_rawDesc)))
	})
	return file_CommitPersonalMsgResIdl_proto_rawDescData
}

var file_CommitPersonalMsgResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_CommitPersonalMsgResIdl_proto_goTypes = []any{
	(*CommitPersonalMsgResIdl)(nil),                   // 0: CommitPersonalMsgResIdl
	(*CommitPersonalMsgResIdl_DataRes)(nil),           // 1: CommitPersonalMsgResIdl.DataRes
	(*CommitPersonalMsgResIdl_DataRes_BlockInfo)(nil), // 2: CommitPersonalMsgResIdl.DataRes.BlockInfo
	(*Error)(nil), // 3: Error
}
var file_CommitPersonalMsgResIdl_proto_depIdxs = []int32{
	3, // 0: CommitPersonalMsgResIdl.error:type_name -> Error
	1, // 1: CommitPersonalMsgResIdl.data:type_name -> CommitPersonalMsgResIdl.DataRes
	2, // 2: CommitPersonalMsgResIdl.DataRes.blockInfo:type_name -> CommitPersonalMsgResIdl.DataRes.BlockInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_CommitPersonalMsgResIdl_proto_init() }
func file_CommitPersonalMsgResIdl_proto_init() {
	if File_CommitPersonalMsgResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CommitPersonalMsgResIdl_proto_rawDesc), len(file_CommitPersonalMsgResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommitPersonalMsgResIdl_proto_goTypes,
		DependencyIndexes: file_CommitPersonalMsgResIdl_proto_depIdxs,
		MessageInfos:      file_CommitPersonalMsgResIdl_proto_msgTypes,
	}.Build()
	File_CommitPersonalMsgResIdl_proto = out.File
	file_CommitPersonalMsgResIdl_proto_goTypes = nil
	file_CommitPersonalMsgResIdl_proto_depIdxs = nil
}
