// protobuf.CommitReceivedPmsg.CommitReceivedPmsgResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: CommitReceivedPmsgResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommitReceivedPmsgResIdl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitReceivedPmsgResIdl) Reset() {
	*x = CommitReceivedPmsgResIdl{}
	mi := &file_CommitReceivedPmsgResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitReceivedPmsgResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReceivedPmsgResIdl) ProtoMessage() {}

func (x *CommitReceivedPmsgResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_CommitReceivedPmsgResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReceivedPmsgResIdl.ProtoReflect.Descriptor instead.
func (*CommitReceivedPmsgResIdl) Descriptor() ([]byte, []int) {
	return file_CommitReceivedPmsgResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *CommitReceivedPmsgResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_CommitReceivedPmsgResIdl_proto protoreflect.FileDescriptor

const file_CommitReceivedPmsgResIdl_proto_rawDesc = "" +
	"\n" +
	"\x1eCommitReceivedPmsgResIdl.proto\x1a\vError.proto\"8\n" +
	"\x18CommitReceivedPmsgResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05errorB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_CommitReceivedPmsgResIdl_proto_rawDescOnce sync.Once
	file_CommitReceivedPmsgResIdl_proto_rawDescData []byte
)

func file_CommitReceivedPmsgResIdl_proto_rawDescGZIP() []byte {
	file_CommitReceivedPmsgResIdl_proto_rawDescOnce.Do(func() {
		file_CommitReceivedPmsgResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CommitReceivedPmsgResIdl_proto_rawDesc), len(file_CommitReceivedPmsgResIdl_proto_rawDesc)))
	})
	return file_CommitReceivedPmsgResIdl_proto_rawDescData
}

var file_CommitReceivedPmsgResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommitReceivedPmsgResIdl_proto_goTypes = []any{
	(*CommitReceivedPmsgResIdl)(nil), // 0: CommitReceivedPmsgResIdl
	(*Error)(nil),                    // 1: Error
}
var file_CommitReceivedPmsgResIdl_proto_depIdxs = []int32{
	1, // 0: CommitReceivedPmsgResIdl.error:type_name -> Error
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CommitReceivedPmsgResIdl_proto_init() }
func file_CommitReceivedPmsgResIdl_proto_init() {
	if File_CommitReceivedPmsgResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CommitReceivedPmsgResIdl_proto_rawDesc), len(file_CommitReceivedPmsgResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommitReceivedPmsgResIdl_proto_goTypes,
		DependencyIndexes: file_CommitReceivedPmsgResIdl_proto_depIdxs,
		MessageInfos:      file_CommitReceivedPmsgResIdl_proto_msgTypes,
	}.Build()
	File_CommitReceivedPmsgResIdl_proto = out.File
	file_CommitReceivedPmsgResIdl_proto_goTypes = nil
	file_CommitReceivedPmsgResIdl_proto_depIdxs = nil
}
