// tbclient.CommonReq

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: CommonReq.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonReq struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	XClientType           int32                  `protobuf:"varint,1,opt,name=_client_type,json=ClientType,proto3" json:"_client_type,omitempty"`
	XClientVersion        string                 `protobuf:"bytes,2,opt,name=_client_version,json=ClientVersion,proto3" json:"_client_version,omitempty"`
	XClientId             string                 `protobuf:"bytes,3,opt,name=_client_id,json=ClientId,proto3" json:"_client_id,omitempty"`
	XPhoneImei            string                 `protobuf:"bytes,5,opt,name=_phone_imei,json=PhoneImei,proto3" json:"_phone_imei,omitempty"`
	XFrom                 string                 `protobuf:"bytes,6,opt,name=_from,json=From,proto3" json:"_from,omitempty"`
	Cuid                  string                 `protobuf:"bytes,7,opt,name=cuid,proto3" json:"cuid,omitempty"`
	XTimestamp            int64                  `protobuf:"varint,8,opt,name=_timestamp,json=Timestamp,proto3" json:"_timestamp,omitempty"`
	Model                 string                 `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	BDUSS                 string                 `protobuf:"bytes,10,opt,name=BDUSS,proto3" json:"BDUSS,omitempty"`
	Tbs                   string                 `protobuf:"bytes,11,opt,name=tbs,proto3" json:"tbs,omitempty"`
	NetType               int32                  `protobuf:"varint,12,opt,name=net_type,json=netType,proto3" json:"net_type,omitempty"`
	Pversion              string                 `protobuf:"bytes,24,opt,name=pversion,proto3" json:"pversion,omitempty"`
	XOsVersion            string                 `protobuf:"bytes,25,opt,name=_os_version,json=OsVersion,proto3" json:"_os_version,omitempty"`
	Brand                 string                 `protobuf:"bytes,26,opt,name=brand,proto3" json:"brand,omitempty"`
	LegoLibVersion        string                 `protobuf:"bytes,28,opt,name=lego_lib_version,json=legoLibVersion,proto3" json:"lego_lib_version,omitempty"`
	Applist               string                 `protobuf:"bytes,29,opt,name=applist,proto3" json:"applist,omitempty"`
	Stoken                string                 `protobuf:"bytes,30,opt,name=stoken,proto3" json:"stoken,omitempty"`
	ZId                   string                 `protobuf:"bytes,31,opt,name=z_id,json=zId,proto3" json:"z_id,omitempty"`
	CuidGalaxy2           string                 `protobuf:"bytes,32,opt,name=cuid_galaxy2,json=cuidGalaxy2,proto3" json:"cuid_galaxy2,omitempty"`
	CuidGid               string                 `protobuf:"bytes,33,opt,name=cuid_gid,json=cuidGid,proto3" json:"cuid_gid,omitempty"`
	C3Aid                 string                 `protobuf:"bytes,35,opt,name=c3_aid,json=c3Aid,proto3" json:"c3_aid,omitempty"`
	SampleId              string                 `protobuf:"bytes,36,opt,name=sample_id,json=sampleId,proto3" json:"sample_id,omitempty"`
	ScrW                  int32                  `protobuf:"varint,37,opt,name=scr_w,json=scrW,proto3" json:"scr_w,omitempty"`
	ScrH                  int32                  `protobuf:"varint,38,opt,name=scr_h,json=scrH,proto3" json:"scr_h,omitempty"`
	ScrDip                float64                `protobuf:"fixed64,39,opt,name=scr_dip,json=scrDip,proto3" json:"scr_dip,omitempty"`
	QType                 int32                  `protobuf:"varint,40,opt,name=q_type,json=qType,proto3" json:"q_type,omitempty"`
	IsTeenager            int32                  `protobuf:"varint,41,opt,name=is_teenager,json=isTeenager,proto3" json:"is_teenager,omitempty"`
	SdkVer                string                 `protobuf:"bytes,42,opt,name=sdk_ver,json=sdkVer,proto3" json:"sdk_ver,omitempty"`
	FrameworkVer          string                 `protobuf:"bytes,43,opt,name=framework_ver,json=frameworkVer,proto3" json:"framework_ver,omitempty"`
	NawsGameVer           string                 `protobuf:"bytes,44,opt,name=naws_game_ver,json=nawsGameVer,proto3" json:"naws_game_ver,omitempty"`
	ActiveTimestamp       int64                  `protobuf:"varint,49,opt,name=active_timestamp,json=activeTimestamp,proto3" json:"active_timestamp,omitempty"`
	FirstInstallTime      int64                  `protobuf:"varint,50,opt,name=first_install_time,json=firstInstallTime,proto3" json:"first_install_time,omitempty"`
	LastUpdateTime        int64                  `protobuf:"varint,51,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	EventDay              string                 `protobuf:"bytes,53,opt,name=event_day,json=eventDay,proto3" json:"event_day,omitempty"`
	AndroidId             string                 `protobuf:"bytes,54,opt,name=android_id,json=androidId,proto3" json:"android_id,omitempty"`
	Cmode                 int32                  `protobuf:"varint,55,opt,name=cmode,proto3" json:"cmode,omitempty"`
	StartScheme           string                 `protobuf:"bytes,56,opt,name=start_scheme,json=startScheme,proto3" json:"start_scheme,omitempty"`
	StartType             int32                  `protobuf:"varint,57,opt,name=start_type,json=startType,proto3" json:"start_type,omitempty"`
	Idfv                  string                 `protobuf:"bytes,60,opt,name=idfv,proto3" json:"idfv,omitempty"`
	Extra                 string                 `protobuf:"bytes,61,opt,name=extra,proto3" json:"extra,omitempty"`
	UserAgent             string                 `protobuf:"bytes,62,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	PersonalizedRecSwitch int32                  `protobuf:"varint,63,opt,name=personalized_rec_switch,json=personalizedRecSwitch,proto3" json:"personalized_rec_switch,omitempty"`
	DeviceScore           string                 `protobuf:"bytes,70,opt,name=device_score,json=deviceScore,proto3" json:"device_score,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CommonReq) Reset() {
	*x = CommonReq{}
	mi := &file_CommonReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonReq) ProtoMessage() {}

func (x *CommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_CommonReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonReq.ProtoReflect.Descriptor instead.
func (*CommonReq) Descriptor() ([]byte, []int) {
	return file_CommonReq_proto_rawDescGZIP(), []int{0}
}

func (x *CommonReq) GetXClientType() int32 {
	if x != nil {
		return x.XClientType
	}
	return 0
}

func (x *CommonReq) GetXClientVersion() string {
	if x != nil {
		return x.XClientVersion
	}
	return ""
}

func (x *CommonReq) GetXClientId() string {
	if x != nil {
		return x.XClientId
	}
	return ""
}

func (x *CommonReq) GetXPhoneImei() string {
	if x != nil {
		return x.XPhoneImei
	}
	return ""
}

func (x *CommonReq) GetXFrom() string {
	if x != nil {
		return x.XFrom
	}
	return ""
}

func (x *CommonReq) GetCuid() string {
	if x != nil {
		return x.Cuid
	}
	return ""
}

func (x *CommonReq) GetXTimestamp() int64 {
	if x != nil {
		return x.XTimestamp
	}
	return 0
}

func (x *CommonReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CommonReq) GetBDUSS() string {
	if x != nil {
		return x.BDUSS
	}
	return ""
}

func (x *CommonReq) GetTbs() string {
	if x != nil {
		return x.Tbs
	}
	return ""
}

func (x *CommonReq) GetNetType() int32 {
	if x != nil {
		return x.NetType
	}
	return 0
}

func (x *CommonReq) GetPversion() string {
	if x != nil {
		return x.Pversion
	}
	return ""
}

func (x *CommonReq) GetXOsVersion() string {
	if x != nil {
		return x.XOsVersion
	}
	return ""
}

func (x *CommonReq) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CommonReq) GetLegoLibVersion() string {
	if x != nil {
		return x.LegoLibVersion
	}
	return ""
}

func (x *CommonReq) GetApplist() string {
	if x != nil {
		return x.Applist
	}
	return ""
}

func (x *CommonReq) GetStoken() string {
	if x != nil {
		return x.Stoken
	}
	return ""
}

func (x *CommonReq) GetZId() string {
	if x != nil {
		return x.ZId
	}
	return ""
}

func (x *CommonReq) GetCuidGalaxy2() string {
	if x != nil {
		return x.CuidGalaxy2
	}
	return ""
}

func (x *CommonReq) GetCuidGid() string {
	if x != nil {
		return x.CuidGid
	}
	return ""
}

func (x *CommonReq) GetC3Aid() string {
	if x != nil {
		return x.C3Aid
	}
	return ""
}

func (x *CommonReq) GetSampleId() string {
	if x != nil {
		return x.SampleId
	}
	return ""
}

func (x *CommonReq) GetScrW() int32 {
	if x != nil {
		return x.ScrW
	}
	return 0
}

func (x *CommonReq) GetScrH() int32 {
	if x != nil {
		return x.ScrH
	}
	return 0
}

func (x *CommonReq) GetScrDip() float64 {
	if x != nil {
		return x.ScrDip
	}
	return 0
}

func (x *CommonReq) GetQType() int32 {
	if x != nil {
		return x.QType
	}
	return 0
}

func (x *CommonReq) GetIsTeenager() int32 {
	if x != nil {
		return x.IsTeenager
	}
	return 0
}

func (x *CommonReq) GetSdkVer() string {
	if x != nil {
		return x.SdkVer
	}
	return ""
}

func (x *CommonReq) GetFrameworkVer() string {
	if x != nil {
		return x.FrameworkVer
	}
	return ""
}

func (x *CommonReq) GetNawsGameVer() string {
	if x != nil {
		return x.NawsGameVer
	}
	return ""
}

func (x *CommonReq) GetActiveTimestamp() int64 {
	if x != nil {
		return x.ActiveTimestamp
	}
	return 0
}

func (x *CommonReq) GetFirstInstallTime() int64 {
	if x != nil {
		return x.FirstInstallTime
	}
	return 0
}

func (x *CommonReq) GetLastUpdateTime() int64 {
	if x != nil {
		return x.LastUpdateTime
	}
	return 0
}

func (x *CommonReq) GetEventDay() string {
	if x != nil {
		return x.EventDay
	}
	return ""
}

func (x *CommonReq) GetAndroidId() string {
	if x != nil {
		return x.AndroidId
	}
	return ""
}

func (x *CommonReq) GetCmode() int32 {
	if x != nil {
		return x.Cmode
	}
	return 0
}

func (x *CommonReq) GetStartScheme() string {
	if x != nil {
		return x.StartScheme
	}
	return ""
}

func (x *CommonReq) GetStartType() int32 {
	if x != nil {
		return x.StartType
	}
	return 0
}

func (x *CommonReq) GetIdfv() string {
	if x != nil {
		return x.Idfv
	}
	return ""
}

func (x *CommonReq) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *CommonReq) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *CommonReq) GetPersonalizedRecSwitch() int32 {
	if x != nil {
		return x.PersonalizedRecSwitch
	}
	return 0
}

func (x *CommonReq) GetDeviceScore() string {
	if x != nil {
		return x.DeviceScore
	}
	return ""
}

var File_CommonReq_proto protoreflect.FileDescriptor

const file_CommonReq_proto_rawDesc = "" +
	"\n" +
	"\x0fCommonReq.proto\"\xff\t\n" +
	"\tCommonReq\x12 \n" +
	"\f_client_type\x18\x01 \x01(\x05R\n" +
	"ClientType\x12&\n" +
	"\x0f_client_version\x18\x02 \x01(\tR\rClientVersion\x12\x1c\n" +
	"\n" +
	"_client_id\x18\x03 \x01(\tR\bClientId\x12\x1e\n" +
	"\v_phone_imei\x18\x05 \x01(\tR\tPhoneImei\x12\x13\n" +
	"\x05_from\x18\x06 \x01(\tR\x04From\x12\x12\n" +
	"\x04cuid\x18\a \x01(\tR\x04cuid\x12\x1d\n" +
	"\n" +
	"_timestamp\x18\b \x01(\x03R\tTimestamp\x12\x14\n" +
	"\x05model\x18\t \x01(\tR\x05model\x12\x14\n" +
	"\x05BDUSS\x18\n" +
	" \x01(\tR\x05BDUSS\x12\x10\n" +
	"\x03tbs\x18\v \x01(\tR\x03tbs\x12\x19\n" +
	"\bnet_type\x18\f \x01(\x05R\anetType\x12\x1a\n" +
	"\bpversion\x18\x18 \x01(\tR\bpversion\x12\x1e\n" +
	"\v_os_version\x18\x19 \x01(\tR\tOsVersion\x12\x14\n" +
	"\x05brand\x18\x1a \x01(\tR\x05brand\x12(\n" +
	"\x10lego_lib_version\x18\x1c \x01(\tR\x0elegoLibVersion\x12\x18\n" +
	"\aapplist\x18\x1d \x01(\tR\aapplist\x12\x16\n" +
	"\x06stoken\x18\x1e \x01(\tR\x06stoken\x12\x11\n" +
	"\x04z_id\x18\x1f \x01(\tR\x03zId\x12!\n" +
	"\fcuid_galaxy2\x18  \x01(\tR\vcuidGalaxy2\x12\x19\n" +
	"\bcuid_gid\x18! \x01(\tR\acuidGid\x12\x15\n" +
	"\x06c3_aid\x18# \x01(\tR\x05c3Aid\x12\x1b\n" +
	"\tsample_id\x18$ \x01(\tR\bsampleId\x12\x13\n" +
	"\x05scr_w\x18% \x01(\x05R\x04scrW\x12\x13\n" +
	"\x05scr_h\x18& \x01(\x05R\x04scrH\x12\x17\n" +
	"\ascr_dip\x18' \x01(\x01R\x06scrDip\x12\x15\n" +
	"\x06q_type\x18( \x01(\x05R\x05qType\x12\x1f\n" +
	"\vis_teenager\x18) \x01(\x05R\n" +
	"isTeenager\x12\x17\n" +
	"\asdk_ver\x18* \x01(\tR\x06sdkVer\x12#\n" +
	"\rframework_ver\x18+ \x01(\tR\fframeworkVer\x12\"\n" +
	"\rnaws_game_ver\x18, \x01(\tR\vnawsGameVer\x12)\n" +
	"\x10active_timestamp\x181 \x01(\x03R\x0factiveTimestamp\x12,\n" +
	"\x12first_install_time\x182 \x01(\x03R\x10firstInstallTime\x12(\n" +
	"\x10last_update_time\x183 \x01(\x03R\x0elastUpdateTime\x12\x1b\n" +
	"\tevent_day\x185 \x01(\tR\beventDay\x12\x1d\n" +
	"\n" +
	"android_id\x186 \x01(\tR\tandroidId\x12\x14\n" +
	"\x05cmode\x187 \x01(\x05R\x05cmode\x12!\n" +
	"\fstart_scheme\x188 \x01(\tR\vstartScheme\x12\x1d\n" +
	"\n" +
	"start_type\x189 \x01(\x05R\tstartType\x12\x12\n" +
	"\x04idfv\x18< \x01(\tR\x04idfv\x12\x14\n" +
	"\x05extra\x18= \x01(\tR\x05extra\x12\x1d\n" +
	"\n" +
	"user_agent\x18> \x01(\tR\tuserAgent\x126\n" +
	"\x17personalized_rec_switch\x18? \x01(\x05R\x15personalizedRecSwitch\x12!\n" +
	"\fdevice_score\x18F \x01(\tR\vdeviceScoreB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_CommonReq_proto_rawDescOnce sync.Once
	file_CommonReq_proto_rawDescData []byte
)

func file_CommonReq_proto_rawDescGZIP() []byte {
	file_CommonReq_proto_rawDescOnce.Do(func() {
		file_CommonReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CommonReq_proto_rawDesc), len(file_CommonReq_proto_rawDesc)))
	})
	return file_CommonReq_proto_rawDescData
}

var file_CommonReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommonReq_proto_goTypes = []any{
	(*CommonReq)(nil), // 0: CommonReq
}
var file_CommonReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CommonReq_proto_init() }
func file_CommonReq_proto_init() {
	if File_CommonReq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CommonReq_proto_rawDesc), len(file_CommonReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonReq_proto_goTypes,
		DependencyIndexes: file_CommonReq_proto_depIdxs,
		MessageInfos:      file_CommonReq_proto_msgTypes,
	}.Build()
	File_CommonReq_proto = out.File
	file_CommonReq_proto_goTypes = nil
	file_CommonReq_proto_depIdxs = nil
}
