// tbclient.Error

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: Error.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errorno       int32                  `protobuf:"varint,1,opt,name=errorno,proto3" json:"errorno,omitempty"`
	Errmsg        string                 `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_Error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_Error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_Error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetErrorno() int32 {
	if x != nil {
		return x.Errorno
	}
	return 0
}

func (x *Error) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

var File_Error_proto protoreflect.FileDescriptor

const file_Error_proto_rawDesc = "" +
	"\n" +
	"\vError.proto\"9\n" +
	"\x05Error\x12\x18\n" +
	"\aerrorno\x18\x01 \x01(\x05R\aerrorno\x12\x16\n" +
	"\x06errmsg\x18\x02 \x01(\tR\x06errmsgB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_Error_proto_rawDescOnce sync.Once
	file_Error_proto_rawDescData []byte
)

func file_Error_proto_rawDescGZIP() []byte {
	file_Error_proto_rawDescOnce.Do(func() {
		file_Error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Error_proto_rawDesc), len(file_Error_proto_rawDesc)))
	})
	return file_Error_proto_rawDescData
}

var file_Error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Error_proto_goTypes = []any{
	(*Error)(nil), // 0: Error
}
var file_Error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Error_proto_init() }
func file_Error_proto_init() {
	if File_Error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Error_proto_rawDesc), len(file_Error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Error_proto_goTypes,
		DependencyIndexes: file_Error_proto_depIdxs,
		MessageInfos:      file_Error_proto_msgTypes,
	}.Build()
	File_Error_proto = out.File
	file_Error_proto_goTypes = nil
	file_Error_proto_depIdxs = nil
}
