// Not actually exist

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: ForumList.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForumList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForumId       int64                  `protobuf:"varint,1,opt,name=forum_id,json=forumId,proto3" json:"forum_id,omitempty"`
	ForumName     string                 `protobuf:"bytes,2,opt,name=forum_name,json=forumName,proto3" json:"forum_name,omitempty"`
	MemberCount   int32                  `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	PostNum       int64                  `protobuf:"varint,7,opt,name=post_num,json=postNum,proto3" json:"post_num,omitempty"`
	ThreadNum     int64                  `protobuf:"varint,8,opt,name=thread_num,json=threadNum,proto3" json:"thread_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForumList) Reset() {
	*x = ForumList{}
	mi := &file_ForumList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForumList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForumList) ProtoMessage() {}

func (x *ForumList) ProtoReflect() protoreflect.Message {
	mi := &file_ForumList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForumList.ProtoReflect.Descriptor instead.
func (*ForumList) Descriptor() ([]byte, []int) {
	return file_ForumList_proto_rawDescGZIP(), []int{0}
}

func (x *ForumList) GetForumId() int64 {
	if x != nil {
		return x.ForumId
	}
	return 0
}

func (x *ForumList) GetForumName() string {
	if x != nil {
		return x.ForumName
	}
	return ""
}

func (x *ForumList) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *ForumList) GetPostNum() int64 {
	if x != nil {
		return x.PostNum
	}
	return 0
}

func (x *ForumList) GetThreadNum() int64 {
	if x != nil {
		return x.ThreadNum
	}
	return 0
}

var File_ForumList_proto protoreflect.FileDescriptor

const file_ForumList_proto_rawDesc = "" +
	"\n" +
	"\x0fForumList.proto\"\xa2\x01\n" +
	"\tForumList\x12\x19\n" +
	"\bforum_id\x18\x01 \x01(\x03R\aforumId\x12\x1d\n" +
	"\n" +
	"forum_name\x18\x02 \x01(\tR\tforumName\x12!\n" +
	"\fmember_count\x18\x04 \x01(\x05R\vmemberCount\x12\x19\n" +
	"\bpost_num\x18\a \x01(\x03R\apostNum\x12\x1d\n" +
	"\n" +
	"thread_num\x18\b \x01(\x03R\tthreadNumB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_ForumList_proto_rawDescOnce sync.Once
	file_ForumList_proto_rawDescData []byte
)

func file_ForumList_proto_rawDescGZIP() []byte {
	file_ForumList_proto_rawDescOnce.Do(func() {
		file_ForumList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ForumList_proto_rawDesc), len(file_ForumList_proto_rawDesc)))
	})
	return file_ForumList_proto_rawDescData
}

var file_ForumList_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ForumList_proto_goTypes = []any{
	(*ForumList)(nil), // 0: ForumList
}
var file_ForumList_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ForumList_proto_init() }
func file_ForumList_proto_init() {
	if File_ForumList_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ForumList_proto_rawDesc), len(file_ForumList_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ForumList_proto_goTypes,
		DependencyIndexes: file_ForumList_proto_depIdxs,
		MessageInfos:      file_ForumList_proto_msgTypes,
	}.Build()
	File_ForumList_proto = out.File
	file_ForumList_proto_goTypes = nil
	file_ForumList_proto_depIdxs = nil
}
