// tbclient.GetBawuInfo.GetBawuInfoResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GetBawuInfoResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBawuInfoResIdl struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          *GetBawuInfoResIdl_DataRes `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         *Error                     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBawuInfoResIdl) Reset() {
	*x = GetBawuInfoResIdl{}
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBawuInfoResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBawuInfoResIdl) ProtoMessage() {}

func (x *GetBawuInfoResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBawuInfoResIdl.ProtoReflect.Descriptor instead.
func (*GetBawuInfoResIdl) Descriptor() ([]byte, []int) {
	return file_GetBawuInfoResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetBawuInfoResIdl) GetData() *GetBawuInfoResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetBawuInfoResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetBawuInfoResIdl_DataRes struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	BawuTeamInfo  *GetBawuInfoResIdl_DataRes_BawuTeam `protobuf:"bytes,1,opt,name=bawu_team_info,json=bawuTeamInfo,proto3" json:"bawu_team_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBawuInfoResIdl_DataRes) Reset() {
	*x = GetBawuInfoResIdl_DataRes{}
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBawuInfoResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBawuInfoResIdl_DataRes) ProtoMessage() {}

func (x *GetBawuInfoResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBawuInfoResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*GetBawuInfoResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_GetBawuInfoResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetBawuInfoResIdl_DataRes) GetBawuTeamInfo() *GetBawuInfoResIdl_DataRes_BawuTeam {
	if x != nil {
		return x.BawuTeamInfo
	}
	return nil
}

type GetBawuInfoResIdl_DataRes_BawuTeam struct {
	state         protoimpl.MessageState                            `protogen:"open.v1"`
	TotalNum      int32                                             `protobuf:"varint,1,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	BawuTeamList  []*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes `protobuf:"bytes,2,rep,name=bawu_team_list,json=bawuTeamList,proto3" json:"bawu_team_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam) Reset() {
	*x = GetBawuInfoResIdl_DataRes_BawuTeam{}
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBawuInfoResIdl_DataRes_BawuTeam) ProtoMessage() {}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam) ProtoReflect() protoreflect.Message {
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBawuInfoResIdl_DataRes_BawuTeam.ProtoReflect.Descriptor instead.
func (*GetBawuInfoResIdl_DataRes_BawuTeam) Descriptor() ([]byte, []int) {
	return file_GetBawuInfoResIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam) GetTotalNum() int32 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam) GetBawuTeamList() []*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes {
	if x != nil {
		return x.BawuTeamList
	}
	return nil
}

type GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes struct {
	state         protoimpl.MessageState                                            `protogen:"open.v1"`
	RoleName      string                                                            `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleInfo      []*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub `protobuf:"bytes,2,rep,name=role_info,json=roleInfo,proto3" json:"role_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) Reset() {
	*x = GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes{}
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) ProtoMessage() {}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) ProtoReflect() protoreflect.Message {
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes.ProtoReflect.Descriptor instead.
func (*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) Descriptor() ([]byte, []int) {
	return file_GetBawuInfoResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) GetRoleInfo() []*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub {
	if x != nil {
		return x.RoleInfo
	}
	return nil
}

type GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Portrait      string                 `protobuf:"bytes,5,opt,name=portrait,proto3" json:"portrait,omitempty"`
	UserLevel     int32                  `protobuf:"varint,6,opt,name=user_level,json=userLevel,proto3" json:"user_level,omitempty"`
	UserName      string                 `protobuf:"bytes,8,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NameShow      string                 `protobuf:"bytes,9,opt,name=name_show,json=nameShow,proto3" json:"name_show,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) Reset() {
	*x = GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub{}
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) ProtoMessage() {}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) ProtoReflect() protoreflect.Message {
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub.ProtoReflect.Descriptor instead.
func (*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) Descriptor() ([]byte, []int) {
	return file_GetBawuInfoResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0}
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) GetPortrait() string {
	if x != nil {
		return x.Portrait
	}
	return ""
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) GetUserLevel() int32 {
	if x != nil {
		return x.UserLevel
	}
	return 0
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) GetNameShow() string {
	if x != nil {
		return x.NameShow
	}
	return ""
}

var File_GetBawuInfoResIdl_proto protoreflect.FileDescriptor

const file_GetBawuInfoResIdl_proto_rawDesc = "" +
	"\n" +
	"\x17GetBawuInfoResIdl.proto\x1a\vError.proto\"\xe6\x04\n" +
	"\x11GetBawuInfoResIdl\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.GetBawuInfoResIdl.DataResR\x04data\x12\x1c\n" +
	"\x05error\x18\x02 \x01(\v2\x06.ErrorR\x05error\x1a\x82\x04\n" +
	"\aDataRes\x12I\n" +
	"\x0ebawu_team_info\x18\x01 \x01(\v2#.GetBawuInfoResIdl.DataRes.BawuTeamR\fbawuTeamInfo\x1a\xab\x03\n" +
	"\bBawuTeam\x12\x1b\n" +
	"\ttotal_num\x18\x01 \x01(\x05R\btotalNum\x12U\n" +
	"\x0ebawu_team_list\x18\x02 \x03(\v2/.GetBawuInfoResIdl.DataRes.BawuTeam.BawuRoleDesR\fbawuTeamList\x1a\xaa\x02\n" +
	"\vBawuRoleDes\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12\\\n" +
	"\trole_info\x18\x02 \x03(\v2?.GetBawuInfoResIdl.DataRes.BawuTeam.BawuRoleDes.BawuRoleInfoPubR\broleInfo\x1a\x9f\x01\n" +
	"\x0fBawuRoleInfoPub\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bportrait\x18\x05 \x01(\tR\bportrait\x12\x1d\n" +
	"\n" +
	"user_level\x18\x06 \x01(\x05R\tuserLevel\x12\x1b\n" +
	"\tuser_name\x18\b \x01(\tR\buserName\x12\x1b\n" +
	"\tname_show\x18\t \x01(\tR\bnameShowB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_GetBawuInfoResIdl_proto_rawDescOnce sync.Once
	file_GetBawuInfoResIdl_proto_rawDescData []byte
)

func file_GetBawuInfoResIdl_proto_rawDescGZIP() []byte {
	file_GetBawuInfoResIdl_proto_rawDescOnce.Do(func() {
		file_GetBawuInfoResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetBawuInfoResIdl_proto_rawDesc), len(file_GetBawuInfoResIdl_proto_rawDesc)))
	})
	return file_GetBawuInfoResIdl_proto_rawDescData
}

var file_GetBawuInfoResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_GetBawuInfoResIdl_proto_goTypes = []any{
	(*GetBawuInfoResIdl)(nil),                                              // 0: GetBawuInfoResIdl
	(*GetBawuInfoResIdl_DataRes)(nil),                                      // 1: GetBawuInfoResIdl.DataRes
	(*GetBawuInfoResIdl_DataRes_BawuTeam)(nil),                             // 2: GetBawuInfoResIdl.DataRes.BawuTeam
	(*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes)(nil),                 // 3: GetBawuInfoResIdl.DataRes.BawuTeam.BawuRoleDes
	(*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub)(nil), // 4: GetBawuInfoResIdl.DataRes.BawuTeam.BawuRoleDes.BawuRoleInfoPub
	(*Error)(nil), // 5: Error
}
var file_GetBawuInfoResIdl_proto_depIdxs = []int32{
	1, // 0: GetBawuInfoResIdl.data:type_name -> GetBawuInfoResIdl.DataRes
	5, // 1: GetBawuInfoResIdl.error:type_name -> Error
	2, // 2: GetBawuInfoResIdl.DataRes.bawu_team_info:type_name -> GetBawuInfoResIdl.DataRes.BawuTeam
	3, // 3: GetBawuInfoResIdl.DataRes.BawuTeam.bawu_team_list:type_name -> GetBawuInfoResIdl.DataRes.BawuTeam.BawuRoleDes
	4, // 4: GetBawuInfoResIdl.DataRes.BawuTeam.BawuRoleDes.role_info:type_name -> GetBawuInfoResIdl.DataRes.BawuTeam.BawuRoleDes.BawuRoleInfoPub
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_GetBawuInfoResIdl_proto_init() }
func file_GetBawuInfoResIdl_proto_init() {
	if File_GetBawuInfoResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetBawuInfoResIdl_proto_rawDesc), len(file_GetBawuInfoResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetBawuInfoResIdl_proto_goTypes,
		DependencyIndexes: file_GetBawuInfoResIdl_proto_depIdxs,
		MessageInfos:      file_GetBawuInfoResIdl_proto_msgTypes,
	}.Build()
	File_GetBawuInfoResIdl_proto = out.File
	file_GetBawuInfoResIdl_proto_goTypes = nil
	file_GetBawuInfoResIdl_proto_depIdxs = nil
}
