// tbclient.GetBawuInfo.GetBawuInfoReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GetBawuInfoReqIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBawuInfoReqIdl struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          *GetBawuInfoReqIdl_DataReq `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBawuInfoReqIdl) Reset() {
	*x = GetBawuInfoReqIdl{}
	mi := &file_GetBawuInfoReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBawuInfoReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBawuInfoReqIdl) ProtoMessage() {}

func (x *GetBawuInfoReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetBawuInfoReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBawuInfoReqIdl.ProtoReflect.Descriptor instead.
func (*GetBawuInfoReqIdl) Descriptor() ([]byte, []int) {
	return file_GetBawuInfoReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetBawuInfoReqIdl) GetData() *GetBawuInfoReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetBawuInfoReqIdl_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *CommonReq             `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Fid           uint64                 `protobuf:"varint,2,opt,name=fid,proto3" json:"fid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBawuInfoReqIdl_DataReq) Reset() {
	*x = GetBawuInfoReqIdl_DataReq{}
	mi := &file_GetBawuInfoReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBawuInfoReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBawuInfoReqIdl_DataReq) ProtoMessage() {}

func (x *GetBawuInfoReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_GetBawuInfoReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBawuInfoReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*GetBawuInfoReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_GetBawuInfoReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetBawuInfoReqIdl_DataReq) GetCommon() *CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *GetBawuInfoReqIdl_DataReq) GetFid() uint64 {
	if x != nil {
		return x.Fid
	}
	return 0
}

var File_GetBawuInfoReqIdl_proto protoreflect.FileDescriptor

const file_GetBawuInfoReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x17GetBawuInfoReqIdl.proto\x1a\x0fCommonReq.proto\"\x84\x01\n" +
	"\x11GetBawuInfoReqIdl\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.GetBawuInfoReqIdl.DataReqR\x04data\x1a?\n" +
	"\aDataReq\x12\"\n" +
	"\x06common\x18\x01 \x01(\v2\n" +
	".CommonReqR\x06common\x12\x10\n" +
	"\x03fid\x18\x02 \x01(\x04R\x03fidB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_GetBawuInfoReqIdl_proto_rawDescOnce sync.Once
	file_GetBawuInfoReqIdl_proto_rawDescData []byte
)

func file_GetBawuInfoReqIdl_proto_rawDescGZIP() []byte {
	file_GetBawuInfoReqIdl_proto_rawDescOnce.Do(func() {
		file_GetBawuInfoReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetBawuInfoReqIdl_proto_rawDesc), len(file_GetBawuInfoReqIdl_proto_rawDesc)))
	})
	return file_GetBawuInfoReqIdl_proto_rawDescData
}

var file_GetBawuInfoReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetBawuInfoReqIdl_proto_goTypes = []any{
	(*GetBawuInfoReqIdl)(nil),         // 0: GetBawuInfoReqIdl
	(*GetBawuInfoReqIdl_DataReq)(nil), // 1: GetBawuInfoReqIdl.DataReq
	(*CommonReq)(nil),                 // 2: CommonReq
}
var file_GetBawuInfoReqIdl_proto_depIdxs = []int32{
	1, // 0: GetBawuInfoReqIdl.data:type_name -> GetBawuInfoReqIdl.DataReq
	2, // 1: GetBawuInfoReqIdl.DataReq.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GetBawuInfoReqIdl_proto_init() }
func file_GetBawuInfoReqIdl_proto_init() {
	if File_GetBawuInfoReqIdl_proto != nil {
		return
	}
	file_CommonReq_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetBawuInfoReqIdl_proto_rawDesc), len(file_GetBawuInfoReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetBawuInfoReqIdl_proto_goTypes,
		DependencyIndexes: file_GetBawuInfoReqIdl_proto_depIdxs,
		MessageInfos:      file_GetBawuInfoReqIdl_proto_msgTypes,
	}.Build()
	File_GetBawuInfoReqIdl_proto = out.File
	file_GetBawuInfoReqIdl_proto_goTypes = nil
	file_GetBawuInfoReqIdl_proto_depIdxs = nil
}
