// tbclient.GetDislikeList.GetDislikeListResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GetDislikeListResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDislikeListResIdl struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Error         *Error                        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *GetDislikeListResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDislikeListResIdl) Reset() {
	*x = GetDislikeListResIdl{}
	mi := &file_GetDislikeListResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDislikeListResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDislikeListResIdl) ProtoMessage() {}

func (x *GetDislikeListResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetDislikeListResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDislikeListResIdl.ProtoReflect.Descriptor instead.
func (*GetDislikeListResIdl) Descriptor() ([]byte, []int) {
	return file_GetDislikeListResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetDislikeListResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetDislikeListResIdl) GetData() *GetDislikeListResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetDislikeListResIdl_DataRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForumList     []*ForumList           `protobuf:"bytes,1,rep,name=forum_list,json=forumList,proto3" json:"forum_list,omitempty"`
	HasMore       int32                  `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	CurPage       int32                  `protobuf:"varint,3,opt,name=cur_page,json=curPage,proto3" json:"cur_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDislikeListResIdl_DataRes) Reset() {
	*x = GetDislikeListResIdl_DataRes{}
	mi := &file_GetDislikeListResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDislikeListResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDislikeListResIdl_DataRes) ProtoMessage() {}

func (x *GetDislikeListResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_GetDislikeListResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDislikeListResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*GetDislikeListResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_GetDislikeListResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetDislikeListResIdl_DataRes) GetForumList() []*ForumList {
	if x != nil {
		return x.ForumList
	}
	return nil
}

func (x *GetDislikeListResIdl_DataRes) GetHasMore() int32 {
	if x != nil {
		return x.HasMore
	}
	return 0
}

func (x *GetDislikeListResIdl_DataRes) GetCurPage() int32 {
	if x != nil {
		return x.CurPage
	}
	return 0
}

var File_GetDislikeListResIdl_proto protoreflect.FileDescriptor

const file_GetDislikeListResIdl_proto_rawDesc = "" +
	"\n" +
	"\x1aGetDislikeListResIdl.proto\x1a\vError.proto\x1a\x0fForumList.proto\"\xd3\x01\n" +
	"\x14GetDislikeListResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x121\n" +
	"\x04data\x18\x02 \x01(\v2\x1d.GetDislikeListResIdl.DataResR\x04data\x1aj\n" +
	"\aDataRes\x12)\n" +
	"\n" +
	"forum_list\x18\x01 \x03(\v2\n" +
	".ForumListR\tforumList\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\x05R\ahasMore\x12\x19\n" +
	"\bcur_page\x18\x03 \x01(\x05R\acurPageB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_GetDislikeListResIdl_proto_rawDescOnce sync.Once
	file_GetDislikeListResIdl_proto_rawDescData []byte
)

func file_GetDislikeListResIdl_proto_rawDescGZIP() []byte {
	file_GetDislikeListResIdl_proto_rawDescOnce.Do(func() {
		file_GetDislikeListResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetDislikeListResIdl_proto_rawDesc), len(file_GetDislikeListResIdl_proto_rawDesc)))
	})
	return file_GetDislikeListResIdl_proto_rawDescData
}

var file_GetDislikeListResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetDislikeListResIdl_proto_goTypes = []any{
	(*GetDislikeListResIdl)(nil),         // 0: GetDislikeListResIdl
	(*GetDislikeListResIdl_DataRes)(nil), // 1: GetDislikeListResIdl.DataRes
	(*Error)(nil),                        // 2: Error
	(*ForumList)(nil),                    // 3: ForumList
}
var file_GetDislikeListResIdl_proto_depIdxs = []int32{
	2, // 0: GetDislikeListResIdl.error:type_name -> Error
	1, // 1: GetDislikeListResIdl.data:type_name -> GetDislikeListResIdl.DataRes
	3, // 2: GetDislikeListResIdl.DataRes.forum_list:type_name -> ForumList
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_GetDislikeListResIdl_proto_init() }
func file_GetDislikeListResIdl_proto_init() {
	if File_GetDislikeListResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	file_ForumList_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetDislikeListResIdl_proto_rawDesc), len(file_GetDislikeListResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetDislikeListResIdl_proto_goTypes,
		DependencyIndexes: file_GetDislikeListResIdl_proto_depIdxs,
		MessageInfos:      file_GetDislikeListResIdl_proto_msgTypes,
	}.Build()
	File_GetDislikeListResIdl_proto = out.File
	file_GetDislikeListResIdl_proto_goTypes = nil
	file_GetDislikeListResIdl_proto_depIdxs = nil
}
