// tbclient.GetForumSquare.GetForumSquareResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GetForumSquareResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetForumSquareResIdl struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Error         *Error                        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *GetForumSquareResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForumSquareResIdl) Reset() {
	*x = GetForumSquareResIdl{}
	mi := &file_GetForumSquareResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForumSquareResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForumSquareResIdl) ProtoMessage() {}

func (x *GetForumSquareResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetForumSquareResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForumSquareResIdl.ProtoReflect.Descriptor instead.
func (*GetForumSquareResIdl) Descriptor() ([]byte, []int) {
	return file_GetForumSquareResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetForumSquareResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetForumSquareResIdl) GetData() *GetForumSquareResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetForumSquareResIdl_DataRes struct {
	state         protoimpl.MessageState                             `protogen:"open.v1"`
	ForumInfo     []*GetForumSquareResIdl_DataRes_RecommendForumInfo `protobuf:"bytes,2,rep,name=forum_info,json=forumInfo,proto3" json:"forum_info,omitempty"`
	Page          *Page                                              `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForumSquareResIdl_DataRes) Reset() {
	*x = GetForumSquareResIdl_DataRes{}
	mi := &file_GetForumSquareResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForumSquareResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForumSquareResIdl_DataRes) ProtoMessage() {}

func (x *GetForumSquareResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_GetForumSquareResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForumSquareResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*GetForumSquareResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_GetForumSquareResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetForumSquareResIdl_DataRes) GetForumInfo() []*GetForumSquareResIdl_DataRes_RecommendForumInfo {
	if x != nil {
		return x.ForumInfo
	}
	return nil
}

func (x *GetForumSquareResIdl_DataRes) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetForumSquareResIdl_DataRes_RecommendForumInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForumId       uint64                 `protobuf:"varint,2,opt,name=forum_id,json=forumId,proto3" json:"forum_id,omitempty"`
	ForumName     string                 `protobuf:"bytes,3,opt,name=forum_name,json=forumName,proto3" json:"forum_name,omitempty"`
	IsLike        uint32                 `protobuf:"varint,4,opt,name=is_like,json=isLike,proto3" json:"is_like,omitempty"`
	MemberCount   uint32                 `protobuf:"varint,5,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	ThreadCount   uint32                 `protobuf:"varint,6,opt,name=thread_count,json=threadCount,proto3" json:"thread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForumSquareResIdl_DataRes_RecommendForumInfo) Reset() {
	*x = GetForumSquareResIdl_DataRes_RecommendForumInfo{}
	mi := &file_GetForumSquareResIdl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForumSquareResIdl_DataRes_RecommendForumInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForumSquareResIdl_DataRes_RecommendForumInfo) ProtoMessage() {}

func (x *GetForumSquareResIdl_DataRes_RecommendForumInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GetForumSquareResIdl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForumSquareResIdl_DataRes_RecommendForumInfo.ProtoReflect.Descriptor instead.
func (*GetForumSquareResIdl_DataRes_RecommendForumInfo) Descriptor() ([]byte, []int) {
	return file_GetForumSquareResIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GetForumSquareResIdl_DataRes_RecommendForumInfo) GetForumId() uint64 {
	if x != nil {
		return x.ForumId
	}
	return 0
}

func (x *GetForumSquareResIdl_DataRes_RecommendForumInfo) GetForumName() string {
	if x != nil {
		return x.ForumName
	}
	return ""
}

func (x *GetForumSquareResIdl_DataRes_RecommendForumInfo) GetIsLike() uint32 {
	if x != nil {
		return x.IsLike
	}
	return 0
}

func (x *GetForumSquareResIdl_DataRes_RecommendForumInfo) GetMemberCount() uint32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *GetForumSquareResIdl_DataRes_RecommendForumInfo) GetThreadCount() uint32 {
	if x != nil {
		return x.ThreadCount
	}
	return 0
}

var File_GetForumSquareResIdl_proto protoreflect.FileDescriptor

const file_GetForumSquareResIdl_proto_rawDesc = "" +
	"\n" +
	"\x1aGetForumSquareResIdl.proto\x1a\vError.proto\x1a\n" +
	"Page.proto\"\x8f\x03\n" +
	"\x14GetForumSquareResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x121\n" +
	"\x04data\x18\x02 \x01(\v2\x1d.GetForumSquareResIdl.DataResR\x04data\x1a\xa5\x02\n" +
	"\aDataRes\x12O\n" +
	"\n" +
	"forum_info\x18\x02 \x03(\v20.GetForumSquareResIdl.DataRes.RecommendForumInfoR\tforumInfo\x12\x19\n" +
	"\x04page\x18\x03 \x01(\v2\x05.PageR\x04page\x1a\xad\x01\n" +
	"\x12RecommendForumInfo\x12\x19\n" +
	"\bforum_id\x18\x02 \x01(\x04R\aforumId\x12\x1d\n" +
	"\n" +
	"forum_name\x18\x03 \x01(\tR\tforumName\x12\x17\n" +
	"\ais_like\x18\x04 \x01(\rR\x06isLike\x12!\n" +
	"\fmember_count\x18\x05 \x01(\rR\vmemberCount\x12!\n" +
	"\fthread_count\x18\x06 \x01(\rR\vthreadCountB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_GetForumSquareResIdl_proto_rawDescOnce sync.Once
	file_GetForumSquareResIdl_proto_rawDescData []byte
)

func file_GetForumSquareResIdl_proto_rawDescGZIP() []byte {
	file_GetForumSquareResIdl_proto_rawDescOnce.Do(func() {
		file_GetForumSquareResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetForumSquareResIdl_proto_rawDesc), len(file_GetForumSquareResIdl_proto_rawDesc)))
	})
	return file_GetForumSquareResIdl_proto_rawDescData
}

var file_GetForumSquareResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_GetForumSquareResIdl_proto_goTypes = []any{
	(*GetForumSquareResIdl)(nil),                            // 0: GetForumSquareResIdl
	(*GetForumSquareResIdl_DataRes)(nil),                    // 1: GetForumSquareResIdl.DataRes
	(*GetForumSquareResIdl_DataRes_RecommendForumInfo)(nil), // 2: GetForumSquareResIdl.DataRes.RecommendForumInfo
	(*Error)(nil), // 3: Error
	(*Page)(nil),  // 4: Page
}
var file_GetForumSquareResIdl_proto_depIdxs = []int32{
	3, // 0: GetForumSquareResIdl.error:type_name -> Error
	1, // 1: GetForumSquareResIdl.data:type_name -> GetForumSquareResIdl.DataRes
	2, // 2: GetForumSquareResIdl.DataRes.forum_info:type_name -> GetForumSquareResIdl.DataRes.RecommendForumInfo
	4, // 3: GetForumSquareResIdl.DataRes.page:type_name -> Page
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_GetForumSquareResIdl_proto_init() }
func file_GetForumSquareResIdl_proto_init() {
	if File_GetForumSquareResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	file_Page_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetForumSquareResIdl_proto_rawDesc), len(file_GetForumSquareResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetForumSquareResIdl_proto_goTypes,
		DependencyIndexes: file_GetForumSquareResIdl_proto_depIdxs,
		MessageInfos:      file_GetForumSquareResIdl_proto_msgTypes,
	}.Build()
	File_GetForumSquareResIdl_proto = out.File
	file_GetForumSquareResIdl_proto_goTypes = nil
	file_GetForumSquareResIdl_proto_depIdxs = nil
}
