// tbclient.GetForumSquare.GetForumSquareReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GetForumSquareReqIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetForumSquareReqIdl struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Data          *GetForumSquareReqIdl_DataReq `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForumSquareReqIdl) Reset() {
	*x = GetForumSquareReqIdl{}
	mi := &file_GetForumSquareReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForumSquareReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForumSquareReqIdl) ProtoMessage() {}

func (x *GetForumSquareReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetForumSquareReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForumSquareReqIdl.ProtoReflect.Descriptor instead.
func (*GetForumSquareReqIdl) Descriptor() ([]byte, []int) {
	return file_GetForumSquareReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetForumSquareReqIdl) GetData() *GetForumSquareReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetForumSquareReqIdl_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *CommonReq             `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Pn            int32                  `protobuf:"varint,3,opt,name=pn,proto3" json:"pn,omitempty"`
	Rn            int32                  `protobuf:"varint,4,opt,name=rn,proto3" json:"rn,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForumSquareReqIdl_DataReq) Reset() {
	*x = GetForumSquareReqIdl_DataReq{}
	mi := &file_GetForumSquareReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForumSquareReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForumSquareReqIdl_DataReq) ProtoMessage() {}

func (x *GetForumSquareReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_GetForumSquareReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForumSquareReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*GetForumSquareReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_GetForumSquareReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetForumSquareReqIdl_DataReq) GetCommon() *CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *GetForumSquareReqIdl_DataReq) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *GetForumSquareReqIdl_DataReq) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *GetForumSquareReqIdl_DataReq) GetRn() int32 {
	if x != nil {
		return x.Rn
	}
	return 0
}

func (x *GetForumSquareReqIdl_DataReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_GetForumSquareReqIdl_proto protoreflect.FileDescriptor

const file_GetForumSquareReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x1aGetForumSquareReqIdl.proto\x1a\x0fCommonReq.proto\"\xd1\x01\n" +
	"\x14GetForumSquareReqIdl\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.GetForumSquareReqIdl.DataReqR\x04data\x1a\x85\x01\n" +
	"\aDataReq\x12\"\n" +
	"\x06common\x18\x01 \x01(\v2\n" +
	".CommonReqR\x06common\x12\x1d\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tR\tclassName\x12\x0e\n" +
	"\x02pn\x18\x03 \x01(\x05R\x02pn\x12\x0e\n" +
	"\x02rn\x18\x04 \x01(\x05R\x02rn\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userIdB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_GetForumSquareReqIdl_proto_rawDescOnce sync.Once
	file_GetForumSquareReqIdl_proto_rawDescData []byte
)

func file_GetForumSquareReqIdl_proto_rawDescGZIP() []byte {
	file_GetForumSquareReqIdl_proto_rawDescOnce.Do(func() {
		file_GetForumSquareReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetForumSquareReqIdl_proto_rawDesc), len(file_GetForumSquareReqIdl_proto_rawDesc)))
	})
	return file_GetForumSquareReqIdl_proto_rawDescData
}

var file_GetForumSquareReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetForumSquareReqIdl_proto_goTypes = []any{
	(*GetForumSquareReqIdl)(nil),         // 0: GetForumSquareReqIdl
	(*GetForumSquareReqIdl_DataReq)(nil), // 1: GetForumSquareReqIdl.DataReq
	(*CommonReq)(nil),                    // 2: CommonReq
}
var file_GetForumSquareReqIdl_proto_depIdxs = []int32{
	1, // 0: GetForumSquareReqIdl.data:type_name -> GetForumSquareReqIdl.DataReq
	2, // 1: GetForumSquareReqIdl.DataReq.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GetForumSquareReqIdl_proto_init() }
func file_GetForumSquareReqIdl_proto_init() {
	if File_GetForumSquareReqIdl_proto != nil {
		return
	}
	file_CommonReq_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetForumSquareReqIdl_proto_rawDesc), len(file_GetForumSquareReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetForumSquareReqIdl_proto_goTypes,
		DependencyIndexes: file_GetForumSquareReqIdl_proto_depIdxs,
		MessageInfos:      file_GetForumSquareReqIdl_proto_msgTypes,
	}.Build()
	File_GetForumSquareReqIdl_proto = out.File
	file_GetForumSquareReqIdl_proto_goTypes = nil
	file_GetForumSquareReqIdl_proto_depIdxs = nil
}
