// protobuf.GetGroupMsg.GetGroupMsgResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GetGroupMsgResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGroupMsgResIdl struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Error         *Error                     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *GetGroupMsgResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMsgResIdl) Reset() {
	*x = GetGroupMsgResIdl{}
	mi := &file_GetGroupMsgResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMsgResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMsgResIdl) ProtoMessage() {}

func (x *GetGroupMsgResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetGroupMsgResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMsgResIdl.ProtoReflect.Descriptor instead.
func (*GetGroupMsgResIdl) Descriptor() ([]byte, []int) {
	return file_GetGroupMsgResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetGroupMsgResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetGroupMsgResIdl) GetData() *GetGroupMsgResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetGroupMsgResIdl_DataRes struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	GroupInfo     []*GetGroupMsgResIdl_DataRes_GroupMsg `protobuf:"bytes,1,rep,name=groupInfo,proto3" json:"groupInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMsgResIdl_DataRes) Reset() {
	*x = GetGroupMsgResIdl_DataRes{}
	mi := &file_GetGroupMsgResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMsgResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMsgResIdl_DataRes) ProtoMessage() {}

func (x *GetGroupMsgResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_GetGroupMsgResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMsgResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*GetGroupMsgResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_GetGroupMsgResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetGroupMsgResIdl_DataRes) GetGroupInfo() []*GetGroupMsgResIdl_DataRes_GroupMsg {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

type GetGroupMsgResIdl_DataRes_GroupMsg struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	GroupInfo     *GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo `protobuf:"bytes,1,opt,name=groupInfo,proto3" json:"groupInfo,omitempty"`
	MsgList       []*GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo `protobuf:"bytes,2,rep,name=msgList,proto3" json:"msgList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg) Reset() {
	*x = GetGroupMsgResIdl_DataRes_GroupMsg{}
	mi := &file_GetGroupMsgResIdl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMsgResIdl_DataRes_GroupMsg) ProtoMessage() {}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg) ProtoReflect() protoreflect.Message {
	mi := &file_GetGroupMsgResIdl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMsgResIdl_DataRes_GroupMsg.ProtoReflect.Descriptor instead.
func (*GetGroupMsgResIdl_DataRes_GroupMsg) Descriptor() ([]byte, []int) {
	return file_GetGroupMsgResIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg) GetGroupInfo() *GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg) GetMsgList() []*GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo {
	if x != nil {
		return x.MsgList
	}
	return nil
}

type GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	GroupType     int32                  `protobuf:"varint,20,opt,name=groupType,proto3" json:"groupType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo) Reset() {
	*x = GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo{}
	mi := &file_GetGroupMsgResIdl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo) ProtoMessage() {}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GetGroupMsgResIdl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo.ProtoReflect.Descriptor instead.
func (*GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo) Descriptor() ([]byte, []int) {
	return file_GetGroupMsgResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

type GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo struct {
	state         protoimpl.MessageState                               `protogen:"open.v1"`
	MsgId         int64                                                `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	MsgType       int32                                                `protobuf:"varint,3,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Content       string                                               `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime    int32                                                `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UserInfo      *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo `protobuf:"bytes,10,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo) Reset() {
	*x = GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo{}
	mi := &file_GetGroupMsgResIdl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo) ProtoMessage() {}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GetGroupMsgResIdl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo.ProtoReflect.Descriptor instead.
func (*GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo) Descriptor() ([]byte, []int) {
	return file_GetGroupMsgResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo) GetCreateTime() int32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo) GetUserInfo() *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Portrait      string                 `protobuf:"bytes,4,opt,name=portrait,proto3" json:"portrait,omitempty"` // string userNameShow = 18;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo) Reset() {
	*x = GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo{}
	mi := &file_GetGroupMsgResIdl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo) ProtoMessage() {}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GetGroupMsgResIdl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo.ProtoReflect.Descriptor instead.
func (*GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo) Descriptor() ([]byte, []int) {
	return file_GetGroupMsgResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 1, 0}
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo) GetPortrait() string {
	if x != nil {
		return x.Portrait
	}
	return ""
}

var File_GetGroupMsgResIdl_proto protoreflect.FileDescriptor

const file_GetGroupMsgResIdl_proto_rawDesc = "" +
	"\n" +
	"\x17GetGroupMsgResIdl.proto\x1a\vError.proto\"\xba\x05\n" +
	"\x11GetGroupMsgResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x12.\n" +
	"\x04data\x18\x02 \x01(\v2\x1a.GetGroupMsgResIdl.DataResR\x04data\x1a\xd6\x04\n" +
	"\aDataRes\x12A\n" +
	"\tgroupInfo\x18\x01 \x03(\v2#.GetGroupMsgResIdl.DataRes.GroupMsgR\tgroupInfo\x1a\x87\x04\n" +
	"\bGroupMsg\x12K\n" +
	"\tgroupInfo\x18\x01 \x01(\v2-.GetGroupMsgResIdl.DataRes.GroupMsg.GroupInfoR\tgroupInfo\x12E\n" +
	"\amsgList\x18\x02 \x03(\v2+.GetGroupMsgResIdl.DataRes.GroupMsg.MsgInfoR\amsgList\x1aC\n" +
	"\tGroupInfo\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\x03R\agroupId\x12\x1c\n" +
	"\tgroupType\x18\x14 \x01(\x05R\tgroupType\x1a\xa1\x02\n" +
	"\aMsgInfo\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x03R\x05msgId\x12\x18\n" +
	"\amsgType\x18\x03 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"createTime\x18\b \x01(\x05R\n" +
	"createTime\x12P\n" +
	"\buserInfo\x18\n" +
	" \x01(\v24.GetGroupMsgResIdl.DataRes.GroupMsg.MsgInfo.UserInfoR\buserInfo\x1aZ\n" +
	"\bUserInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\x12\x1a\n" +
	"\bportrait\x18\x04 \x01(\tR\bportraitB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_GetGroupMsgResIdl_proto_rawDescOnce sync.Once
	file_GetGroupMsgResIdl_proto_rawDescData []byte
)

func file_GetGroupMsgResIdl_proto_rawDescGZIP() []byte {
	file_GetGroupMsgResIdl_proto_rawDescOnce.Do(func() {
		file_GetGroupMsgResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetGroupMsgResIdl_proto_rawDesc), len(file_GetGroupMsgResIdl_proto_rawDesc)))
	})
	return file_GetGroupMsgResIdl_proto_rawDescData
}

var file_GetGroupMsgResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_GetGroupMsgResIdl_proto_goTypes = []any{
	(*GetGroupMsgResIdl)(nil),                                   // 0: GetGroupMsgResIdl
	(*GetGroupMsgResIdl_DataRes)(nil),                           // 1: GetGroupMsgResIdl.DataRes
	(*GetGroupMsgResIdl_DataRes_GroupMsg)(nil),                  // 2: GetGroupMsgResIdl.DataRes.GroupMsg
	(*GetGroupMsgResIdl_DataRes_GroupMsg_GroupInfo)(nil),        // 3: GetGroupMsgResIdl.DataRes.GroupMsg.GroupInfo
	(*GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo)(nil),          // 4: GetGroupMsgResIdl.DataRes.GroupMsg.MsgInfo
	(*GetGroupMsgResIdl_DataRes_GroupMsg_MsgInfo_UserInfo)(nil), // 5: GetGroupMsgResIdl.DataRes.GroupMsg.MsgInfo.UserInfo
	(*Error)(nil), // 6: Error
}
var file_GetGroupMsgResIdl_proto_depIdxs = []int32{
	6, // 0: GetGroupMsgResIdl.error:type_name -> Error
	1, // 1: GetGroupMsgResIdl.data:type_name -> GetGroupMsgResIdl.DataRes
	2, // 2: GetGroupMsgResIdl.DataRes.groupInfo:type_name -> GetGroupMsgResIdl.DataRes.GroupMsg
	3, // 3: GetGroupMsgResIdl.DataRes.GroupMsg.groupInfo:type_name -> GetGroupMsgResIdl.DataRes.GroupMsg.GroupInfo
	4, // 4: GetGroupMsgResIdl.DataRes.GroupMsg.msgList:type_name -> GetGroupMsgResIdl.DataRes.GroupMsg.MsgInfo
	5, // 5: GetGroupMsgResIdl.DataRes.GroupMsg.MsgInfo.userInfo:type_name -> GetGroupMsgResIdl.DataRes.GroupMsg.MsgInfo.UserInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_GetGroupMsgResIdl_proto_init() }
func file_GetGroupMsgResIdl_proto_init() {
	if File_GetGroupMsgResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetGroupMsgResIdl_proto_rawDesc), len(file_GetGroupMsgResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetGroupMsgResIdl_proto_goTypes,
		DependencyIndexes: file_GetGroupMsgResIdl_proto_depIdxs,
		MessageInfos:      file_GetGroupMsgResIdl_proto_msgTypes,
	}.Build()
	File_GetGroupMsgResIdl_proto = out.File
	file_GetGroupMsgResIdl_proto_goTypes = nil
	file_GetGroupMsgResIdl_proto_depIdxs = nil
}
