// protobuf.GetGroupMsg.GetGroupMsgReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GetGroupMsgReqIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGroupMsgReqIdl struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Cuid          string                     `protobuf:"bytes,1,opt,name=cuid,proto3" json:"cuid,omitempty"`
	Data          *GetGroupMsgReqIdl_DataReq `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMsgReqIdl) Reset() {
	*x = GetGroupMsgReqIdl{}
	mi := &file_GetGroupMsgReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMsgReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMsgReqIdl) ProtoMessage() {}

func (x *GetGroupMsgReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetGroupMsgReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMsgReqIdl.ProtoReflect.Descriptor instead.
func (*GetGroupMsgReqIdl) Descriptor() ([]byte, []int) {
	return file_GetGroupMsgReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetGroupMsgReqIdl) GetCuid() string {
	if x != nil {
		return x.Cuid
	}
	return ""
}

func (x *GetGroupMsgReqIdl) GetData() *GetGroupMsgReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetGroupMsgReqIdl_DataReq struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	GroupMids     []*GetGroupMsgReqIdl_DataReq_GroupLastId `protobuf:"bytes,6,rep,name=groupMids,proto3" json:"groupMids,omitempty"`
	Gettype       string                                   `protobuf:"bytes,7,opt,name=gettype,proto3" json:"gettype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMsgReqIdl_DataReq) Reset() {
	*x = GetGroupMsgReqIdl_DataReq{}
	mi := &file_GetGroupMsgReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMsgReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMsgReqIdl_DataReq) ProtoMessage() {}

func (x *GetGroupMsgReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_GetGroupMsgReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMsgReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*GetGroupMsgReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_GetGroupMsgReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetGroupMsgReqIdl_DataReq) GetGroupMids() []*GetGroupMsgReqIdl_DataReq_GroupLastId {
	if x != nil {
		return x.GroupMids
	}
	return nil
}

func (x *GetGroupMsgReqIdl_DataReq) GetGettype() string {
	if x != nil {
		return x.Gettype
	}
	return ""
}

type GetGroupMsgReqIdl_DataReq_GroupLastId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	LastMsgId     int64                  `protobuf:"varint,2,opt,name=lastMsgId,proto3" json:"lastMsgId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMsgReqIdl_DataReq_GroupLastId) Reset() {
	*x = GetGroupMsgReqIdl_DataReq_GroupLastId{}
	mi := &file_GetGroupMsgReqIdl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMsgReqIdl_DataReq_GroupLastId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMsgReqIdl_DataReq_GroupLastId) ProtoMessage() {}

func (x *GetGroupMsgReqIdl_DataReq_GroupLastId) ProtoReflect() protoreflect.Message {
	mi := &file_GetGroupMsgReqIdl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMsgReqIdl_DataReq_GroupLastId.ProtoReflect.Descriptor instead.
func (*GetGroupMsgReqIdl_DataReq_GroupLastId) Descriptor() ([]byte, []int) {
	return file_GetGroupMsgReqIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GetGroupMsgReqIdl_DataReq_GroupLastId) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupMsgReqIdl_DataReq_GroupLastId) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

var File_GetGroupMsgReqIdl_proto protoreflect.FileDescriptor

const file_GetGroupMsgReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x17GetGroupMsgReqIdl.proto\"\x8a\x02\n" +
	"\x11GetGroupMsgReqIdl\x12\x12\n" +
	"\x04cuid\x18\x01 \x01(\tR\x04cuid\x12.\n" +
	"\x04data\x18\x02 \x01(\v2\x1a.GetGroupMsgReqIdl.DataReqR\x04data\x1a\xb0\x01\n" +
	"\aDataReq\x12D\n" +
	"\tgroupMids\x18\x06 \x03(\v2&.GetGroupMsgReqIdl.DataReq.GroupLastIdR\tgroupMids\x12\x18\n" +
	"\agettype\x18\a \x01(\tR\agettype\x1aE\n" +
	"\vGroupLastId\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\x03R\agroupId\x12\x1c\n" +
	"\tlastMsgId\x18\x02 \x01(\x03R\tlastMsgIdB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_GetGroupMsgReqIdl_proto_rawDescOnce sync.Once
	file_GetGroupMsgReqIdl_proto_rawDescData []byte
)

func file_GetGroupMsgReqIdl_proto_rawDescGZIP() []byte {
	file_GetGroupMsgReqIdl_proto_rawDescOnce.Do(func() {
		file_GetGroupMsgReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetGroupMsgReqIdl_proto_rawDesc), len(file_GetGroupMsgReqIdl_proto_rawDesc)))
	})
	return file_GetGroupMsgReqIdl_proto_rawDescData
}

var file_GetGroupMsgReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_GetGroupMsgReqIdl_proto_goTypes = []any{
	(*GetGroupMsgReqIdl)(nil),                     // 0: GetGroupMsgReqIdl
	(*GetGroupMsgReqIdl_DataReq)(nil),             // 1: GetGroupMsgReqIdl.DataReq
	(*GetGroupMsgReqIdl_DataReq_GroupLastId)(nil), // 2: GetGroupMsgReqIdl.DataReq.GroupLastId
}
var file_GetGroupMsgReqIdl_proto_depIdxs = []int32{
	1, // 0: GetGroupMsgReqIdl.data:type_name -> GetGroupMsgReqIdl.DataReq
	2, // 1: GetGroupMsgReqIdl.DataReq.groupMids:type_name -> GetGroupMsgReqIdl.DataReq.GroupLastId
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GetGroupMsgReqIdl_proto_init() }
func file_GetGroupMsgReqIdl_proto_init() {
	if File_GetGroupMsgReqIdl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetGroupMsgReqIdl_proto_rawDesc), len(file_GetGroupMsgReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetGroupMsgReqIdl_proto_goTypes,
		DependencyIndexes: file_GetGroupMsgReqIdl_proto_depIdxs,
		MessageInfos:      file_GetGroupMsgReqIdl_proto_msgTypes,
	}.Build()
	File_GetGroupMsgReqIdl_proto = out.File
	file_GetGroupMsgReqIdl_proto_goTypes = nil
	file_GetGroupMsgReqIdl_proto_depIdxs = nil
}
