// tbclient.GetUserByTiebaUid.GetUserByTiebaUidReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GetUserByTiebaUidReqIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserByTiebaUidReqIdl struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Data          *GetUserByTiebaUidReqIdl_DataReq `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTiebaUidReqIdl) Reset() {
	*x = GetUserByTiebaUidReqIdl{}
	mi := &file_GetUserByTiebaUidReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTiebaUidReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTiebaUidReqIdl) ProtoMessage() {}

func (x *GetUserByTiebaUidReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserByTiebaUidReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTiebaUidReqIdl.ProtoReflect.Descriptor instead.
func (*GetUserByTiebaUidReqIdl) Descriptor() ([]byte, []int) {
	return file_GetUserByTiebaUidReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByTiebaUidReqIdl) GetData() *GetUserByTiebaUidReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserByTiebaUidReqIdl_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *CommonReq             `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	TiebaUid      string                 `protobuf:"bytes,2,opt,name=tieba_uid,json=tiebaUid,proto3" json:"tieba_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTiebaUidReqIdl_DataReq) Reset() {
	*x = GetUserByTiebaUidReqIdl_DataReq{}
	mi := &file_GetUserByTiebaUidReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTiebaUidReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTiebaUidReqIdl_DataReq) ProtoMessage() {}

func (x *GetUserByTiebaUidReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserByTiebaUidReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTiebaUidReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*GetUserByTiebaUidReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_GetUserByTiebaUidReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetUserByTiebaUidReqIdl_DataReq) GetCommon() *CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *GetUserByTiebaUidReqIdl_DataReq) GetTiebaUid() string {
	if x != nil {
		return x.TiebaUid
	}
	return ""
}

var File_GetUserByTiebaUidReqIdl_proto protoreflect.FileDescriptor

const file_GetUserByTiebaUidReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x1dGetUserByTiebaUidReqIdl.proto\x1a\x0fCommonReq.proto\"\x9b\x01\n" +
	"\x17GetUserByTiebaUidReqIdl\x124\n" +
	"\x04data\x18\x01 \x01(\v2 .GetUserByTiebaUidReqIdl.DataReqR\x04data\x1aJ\n" +
	"\aDataReq\x12\"\n" +
	"\x06common\x18\x01 \x01(\v2\n" +
	".CommonReqR\x06common\x12\x1b\n" +
	"\ttieba_uid\x18\x02 \x01(\tR\btiebaUidB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_GetUserByTiebaUidReqIdl_proto_rawDescOnce sync.Once
	file_GetUserByTiebaUidReqIdl_proto_rawDescData []byte
)

func file_GetUserByTiebaUidReqIdl_proto_rawDescGZIP() []byte {
	file_GetUserByTiebaUidReqIdl_proto_rawDescOnce.Do(func() {
		file_GetUserByTiebaUidReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetUserByTiebaUidReqIdl_proto_rawDesc), len(file_GetUserByTiebaUidReqIdl_proto_rawDesc)))
	})
	return file_GetUserByTiebaUidReqIdl_proto_rawDescData
}

var file_GetUserByTiebaUidReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetUserByTiebaUidReqIdl_proto_goTypes = []any{
	(*GetUserByTiebaUidReqIdl)(nil),         // 0: GetUserByTiebaUidReqIdl
	(*GetUserByTiebaUidReqIdl_DataReq)(nil), // 1: GetUserByTiebaUidReqIdl.DataReq
	(*CommonReq)(nil),                       // 2: CommonReq
}
var file_GetUserByTiebaUidReqIdl_proto_depIdxs = []int32{
	1, // 0: GetUserByTiebaUidReqIdl.data:type_name -> GetUserByTiebaUidReqIdl.DataReq
	2, // 1: GetUserByTiebaUidReqIdl.DataReq.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GetUserByTiebaUidReqIdl_proto_init() }
func file_GetUserByTiebaUidReqIdl_proto_init() {
	if File_GetUserByTiebaUidReqIdl_proto != nil {
		return
	}
	file_CommonReq_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetUserByTiebaUidReqIdl_proto_rawDesc), len(file_GetUserByTiebaUidReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetUserByTiebaUidReqIdl_proto_goTypes,
		DependencyIndexes: file_GetUserByTiebaUidReqIdl_proto_depIdxs,
		MessageInfos:      file_GetUserByTiebaUidReqIdl_proto_msgTypes,
	}.Build()
	File_GetUserByTiebaUidReqIdl_proto = out.File
	file_GetUserByTiebaUidReqIdl_proto_goTypes = nil
	file_GetUserByTiebaUidReqIdl_proto_depIdxs = nil
}
