// tbclient.GetUserByTiebaUid.GetUserByTiebaUidResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GetUserByTiebaUidResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserByTiebaUidResIdl struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Error         *Error                           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *GetUserByTiebaUidResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTiebaUidResIdl) Reset() {
	*x = GetUserByTiebaUidResIdl{}
	mi := &file_GetUserByTiebaUidResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTiebaUidResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTiebaUidResIdl) ProtoMessage() {}

func (x *GetUserByTiebaUidResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserByTiebaUidResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTiebaUidResIdl.ProtoReflect.Descriptor instead.
func (*GetUserByTiebaUidResIdl) Descriptor() ([]byte, []int) {
	return file_GetUserByTiebaUidResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByTiebaUidResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetUserByTiebaUidResIdl) GetData() *GetUserByTiebaUidResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserByTiebaUidResIdl_DataRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTiebaUidResIdl_DataRes) Reset() {
	*x = GetUserByTiebaUidResIdl_DataRes{}
	mi := &file_GetUserByTiebaUidResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTiebaUidResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTiebaUidResIdl_DataRes) ProtoMessage() {}

func (x *GetUserByTiebaUidResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserByTiebaUidResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTiebaUidResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*GetUserByTiebaUidResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_GetUserByTiebaUidResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetUserByTiebaUidResIdl_DataRes) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_GetUserByTiebaUidResIdl_proto protoreflect.FileDescriptor

const file_GetUserByTiebaUidResIdl_proto_rawDesc = "" +
	"\n" +
	"\x1dGetUserByTiebaUidResIdl.proto\x1a\vError.proto\x1a\n" +
	"User.proto\"\x93\x01\n" +
	"\x17GetUserByTiebaUidResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x124\n" +
	"\x04data\x18\x02 \x01(\v2 .GetUserByTiebaUidResIdl.DataResR\x04data\x1a$\n" +
	"\aDataRes\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04userB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_GetUserByTiebaUidResIdl_proto_rawDescOnce sync.Once
	file_GetUserByTiebaUidResIdl_proto_rawDescData []byte
)

func file_GetUserByTiebaUidResIdl_proto_rawDescGZIP() []byte {
	file_GetUserByTiebaUidResIdl_proto_rawDescOnce.Do(func() {
		file_GetUserByTiebaUidResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetUserByTiebaUidResIdl_proto_rawDesc), len(file_GetUserByTiebaUidResIdl_proto_rawDesc)))
	})
	return file_GetUserByTiebaUidResIdl_proto_rawDescData
}

var file_GetUserByTiebaUidResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetUserByTiebaUidResIdl_proto_goTypes = []any{
	(*GetUserByTiebaUidResIdl)(nil),         // 0: GetUserByTiebaUidResIdl
	(*GetUserByTiebaUidResIdl_DataRes)(nil), // 1: GetUserByTiebaUidResIdl.DataRes
	(*Error)(nil),                           // 2: Error
	(*User)(nil),                            // 3: User
}
var file_GetUserByTiebaUidResIdl_proto_depIdxs = []int32{
	2, // 0: GetUserByTiebaUidResIdl.error:type_name -> Error
	1, // 1: GetUserByTiebaUidResIdl.data:type_name -> GetUserByTiebaUidResIdl.DataRes
	3, // 2: GetUserByTiebaUidResIdl.DataRes.user:type_name -> User
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_GetUserByTiebaUidResIdl_proto_init() }
func file_GetUserByTiebaUidResIdl_proto_init() {
	if File_GetUserByTiebaUidResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	file_User_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetUserByTiebaUidResIdl_proto_rawDesc), len(file_GetUserByTiebaUidResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetUserByTiebaUidResIdl_proto_goTypes,
		DependencyIndexes: file_GetUserByTiebaUidResIdl_proto_depIdxs,
		MessageInfos:      file_GetUserByTiebaUidResIdl_proto_msgTypes,
	}.Build()
	File_GetUserByTiebaUidResIdl_proto = out.File
	file_GetUserByTiebaUidResIdl_proto_goTypes = nil
	file_GetUserByTiebaUidResIdl_proto_depIdxs = nil
}
