// tbclient.GetUserInfo.GetUserInfoReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GetUserInfoReqIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserInfoReqIdl struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          *GetUserInfoReqIdl_DataReq `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReqIdl) Reset() {
	*x = GetUserInfoReqIdl{}
	mi := &file_GetUserInfoReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReqIdl) ProtoMessage() {}

func (x *GetUserInfoReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserInfoReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReqIdl.ProtoReflect.Descriptor instead.
func (*GetUserInfoReqIdl) Descriptor() ([]byte, []int) {
	return file_GetUserInfoReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoReqIdl) GetData() *GetUserInfoReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserInfoReqIdl_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReqIdl_DataReq) Reset() {
	*x = GetUserInfoReqIdl_DataReq{}
	mi := &file_GetUserInfoReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReqIdl_DataReq) ProtoMessage() {}

func (x *GetUserInfoReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserInfoReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_GetUserInfoReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetUserInfoReqIdl_DataReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_GetUserInfoReqIdl_proto protoreflect.FileDescriptor

const file_GetUserInfoReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x17GetUserInfoReqIdl.proto\"g\n" +
	"\x11GetUserInfoReqIdl\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.GetUserInfoReqIdl.DataReqR\x04data\x1a\"\n" +
	"\aDataReq\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userIdB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_GetUserInfoReqIdl_proto_rawDescOnce sync.Once
	file_GetUserInfoReqIdl_proto_rawDescData []byte
)

func file_GetUserInfoReqIdl_proto_rawDescGZIP() []byte {
	file_GetUserInfoReqIdl_proto_rawDescOnce.Do(func() {
		file_GetUserInfoReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetUserInfoReqIdl_proto_rawDesc), len(file_GetUserInfoReqIdl_proto_rawDesc)))
	})
	return file_GetUserInfoReqIdl_proto_rawDescData
}

var file_GetUserInfoReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetUserInfoReqIdl_proto_goTypes = []any{
	(*GetUserInfoReqIdl)(nil),         // 0: GetUserInfoReqIdl
	(*GetUserInfoReqIdl_DataReq)(nil), // 1: GetUserInfoReqIdl.DataReq
}
var file_GetUserInfoReqIdl_proto_depIdxs = []int32{
	1, // 0: GetUserInfoReqIdl.data:type_name -> GetUserInfoReqIdl.DataReq
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_GetUserInfoReqIdl_proto_init() }
func file_GetUserInfoReqIdl_proto_init() {
	if File_GetUserInfoReqIdl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetUserInfoReqIdl_proto_rawDesc), len(file_GetUserInfoReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetUserInfoReqIdl_proto_goTypes,
		DependencyIndexes: file_GetUserInfoReqIdl_proto_depIdxs,
		MessageInfos:      file_GetUserInfoReqIdl_proto_msgTypes,
	}.Build()
	File_GetUserInfoReqIdl_proto = out.File
	file_GetUserInfoReqIdl_proto_goTypes = nil
	file_GetUserInfoReqIdl_proto_depIdxs = nil
}
