// tbclient.Media

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: Media.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	SmallPic      string                 `protobuf:"bytes,2,opt,name=small_pic,json=smallPic,proto3" json:"small_pic,omitempty"`
	BigPic        string                 `protobuf:"bytes,3,opt,name=big_pic,json=bigPic,proto3" json:"big_pic,omitempty"`
	WaterPic      string                 `protobuf:"bytes,4,opt,name=water_pic,json=waterPic,proto3" json:"water_pic,omitempty"`
	Width         uint32                 `protobuf:"varint,10,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,11,opt,name=height,proto3" json:"height,omitempty"`
	OriginPic     string                 `protobuf:"bytes,15,opt,name=origin_pic,json=originPic,proto3" json:"origin_pic,omitempty"`
	OriginSize    uint32                 `protobuf:"varint,16,opt,name=origin_size,json=originSize,proto3" json:"origin_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_Media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_Media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_Media_proto_rawDescGZIP(), []int{0}
}

func (x *Media) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Media) GetSmallPic() string {
	if x != nil {
		return x.SmallPic
	}
	return ""
}

func (x *Media) GetBigPic() string {
	if x != nil {
		return x.BigPic
	}
	return ""
}

func (x *Media) GetWaterPic() string {
	if x != nil {
		return x.WaterPic
	}
	return ""
}

func (x *Media) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Media) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Media) GetOriginPic() string {
	if x != nil {
		return x.OriginPic
	}
	return ""
}

func (x *Media) GetOriginSize() uint32 {
	if x != nil {
		return x.OriginSize
	}
	return 0
}

var File_Media_proto protoreflect.FileDescriptor

const file_Media_proto_rawDesc = "" +
	"\n" +
	"\vMedia.proto\"\xdc\x01\n" +
	"\x05Media\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x1b\n" +
	"\tsmall_pic\x18\x02 \x01(\tR\bsmallPic\x12\x17\n" +
	"\abig_pic\x18\x03 \x01(\tR\x06bigPic\x12\x1b\n" +
	"\twater_pic\x18\x04 \x01(\tR\bwaterPic\x12\x14\n" +
	"\x05width\x18\n" +
	" \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\v \x01(\rR\x06height\x12\x1d\n" +
	"\n" +
	"origin_pic\x18\x0f \x01(\tR\toriginPic\x12\x1f\n" +
	"\vorigin_size\x18\x10 \x01(\rR\n" +
	"originSizeB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_Media_proto_rawDescOnce sync.Once
	file_Media_proto_rawDescData []byte
)

func file_Media_proto_rawDescGZIP() []byte {
	file_Media_proto_rawDescOnce.Do(func() {
		file_Media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Media_proto_rawDesc), len(file_Media_proto_rawDesc)))
	})
	return file_Media_proto_rawDescData
}

var file_Media_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Media_proto_goTypes = []any{
	(*Media)(nil), // 0: Media
}
var file_Media_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Media_proto_init() }
func file_Media_proto_init() {
	if File_Media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Media_proto_rawDesc), len(file_Media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Media_proto_goTypes,
		DependencyIndexes: file_Media_proto_depIdxs,
		MessageInfos:      file_Media_proto_msgTypes,
	}.Build()
	File_Media_proto = out.File
	file_Media_proto_goTypes = nil
	file_Media_proto_depIdxs = nil
}
