// tbclient.Page

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: Page.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPage     int32                  `protobuf:"varint,5,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	HasMore       int32                  `protobuf:"varint,6,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	HasPrev       int32                  `protobuf:"varint,7,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_Page_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_Page_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_Page_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Page) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *Page) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Page) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *Page) GetHasMore() int32 {
	if x != nil {
		return x.HasMore
	}
	return 0
}

func (x *Page) GetHasPrev() int32 {
	if x != nil {
		return x.HasPrev
	}
	return 0
}

var File_Page_proto protoreflect.FileDescriptor

const file_Page_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"Page.proto\"\xbc\x01\n" +
	"\x04Page\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"total_page\x18\x05 \x01(\x05R\ttotalPage\x12\x19\n" +
	"\bhas_more\x18\x06 \x01(\x05R\ahasMore\x12\x19\n" +
	"\bhas_prev\x18\a \x01(\x05R\ahasPrevB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_Page_proto_rawDescOnce sync.Once
	file_Page_proto_rawDescData []byte
)

func file_Page_proto_rawDescGZIP() []byte {
	file_Page_proto_rawDescOnce.Do(func() {
		file_Page_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Page_proto_rawDesc), len(file_Page_proto_rawDesc)))
	})
	return file_Page_proto_rawDescData
}

var file_Page_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Page_proto_goTypes = []any{
	(*Page)(nil), // 0: Page
}
var file_Page_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Page_proto_init() }
func file_Page_proto_init() {
	if File_Page_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Page_proto_rawDesc), len(file_Page_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Page_proto_goTypes,
		DependencyIndexes: file_Page_proto_depIdxs,
		MessageInfos:      file_Page_proto_msgTypes,
	}.Build()
	File_Page_proto = out.File
	file_Page_proto_goTypes = nil
	file_Page_proto_depIdxs = nil
}
