// tbclient.PbContent

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: PbContent.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbContent struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          uint32                   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Link          string                   `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Src           string                   `protobuf:"bytes,4,opt,name=src,proto3" json:"src,omitempty"`
	Bsize         string                   `protobuf:"bytes,5,opt,name=bsize,proto3" json:"bsize,omitempty"`
	CdnSrc        string                   `protobuf:"bytes,8,opt,name=cdn_src,json=cdnSrc,proto3" json:"cdn_src,omitempty"`
	BigCdnSrc     string                   `protobuf:"bytes,9,opt,name=big_cdn_src,json=bigCdnSrc,proto3" json:"big_cdn_src,omitempty"`
	C             string                   `protobuf:"bytes,11,opt,name=c,proto3" json:"c,omitempty"`
	VoiceMd5      string                   `protobuf:"bytes,12,opt,name=voice_md5,json=voiceMd5,proto3" json:"voice_md5,omitempty"`
	DuringTime    uint32                   `protobuf:"varint,13,opt,name=during_time,json=duringTime,proto3" json:"during_time,omitempty"`
	Uid           int64                    `protobuf:"varint,15,opt,name=uid,proto3" json:"uid,omitempty"`
	Width         uint32                   `protobuf:"varint,18,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                   `protobuf:"varint,19,opt,name=height,proto3" json:"height,omitempty"`
	OriginSrc     string                   `protobuf:"bytes,25,opt,name=origin_src,json=originSrc,proto3" json:"origin_src,omitempty"`
	OriginSize    uint32                   `protobuf:"varint,27,opt,name=origin_size,json=originSize,proto3" json:"origin_size,omitempty"`
	Count         int32                    `protobuf:"varint,28,opt,name=count,proto3" json:"count,omitempty"`
	TiebaplusInfo *PbContent_TiebaPlusInfo `protobuf:"bytes,40,opt,name=tiebaplus_info,json=tiebaplusInfo,proto3" json:"tiebaplus_info,omitempty"`
	Item          *PbContent_Item          `protobuf:"bytes,41,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbContent) Reset() {
	*x = PbContent{}
	mi := &file_PbContent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbContent) ProtoMessage() {}

func (x *PbContent) ProtoReflect() protoreflect.Message {
	mi := &file_PbContent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbContent.ProtoReflect.Descriptor instead.
func (*PbContent) Descriptor() ([]byte, []int) {
	return file_PbContent_proto_rawDescGZIP(), []int{0}
}

func (x *PbContent) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PbContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PbContent) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PbContent) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *PbContent) GetBsize() string {
	if x != nil {
		return x.Bsize
	}
	return ""
}

func (x *PbContent) GetCdnSrc() string {
	if x != nil {
		return x.CdnSrc
	}
	return ""
}

func (x *PbContent) GetBigCdnSrc() string {
	if x != nil {
		return x.BigCdnSrc
	}
	return ""
}

func (x *PbContent) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

func (x *PbContent) GetVoiceMd5() string {
	if x != nil {
		return x.VoiceMd5
	}
	return ""
}

func (x *PbContent) GetDuringTime() uint32 {
	if x != nil {
		return x.DuringTime
	}
	return 0
}

func (x *PbContent) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PbContent) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PbContent) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PbContent) GetOriginSrc() string {
	if x != nil {
		return x.OriginSrc
	}
	return ""
}

func (x *PbContent) GetOriginSize() uint32 {
	if x != nil {
		return x.OriginSize
	}
	return 0
}

func (x *PbContent) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PbContent) GetTiebaplusInfo() *PbContent_TiebaPlusInfo {
	if x != nil {
		return x.TiebaplusInfo
	}
	return nil
}

func (x *PbContent) GetItem() *PbContent_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type PbContent_TiebaPlusInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	JumpUrl       string                 `protobuf:"bytes,3,opt,name=jump_url,json=jumpUrl,proto3" json:"jump_url,omitempty"`
	AppIcon       string                 `protobuf:"bytes,6,opt,name=app_icon,json=appIcon,proto3" json:"app_icon,omitempty"`
	TargetType    int32                  `protobuf:"varint,12,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	H5JumpType    int32                  `protobuf:"varint,13,opt,name=h5_jump_type,json=h5JumpType,proto3" json:"h5_jump_type,omitempty"`
	H5JumpNumber  string                 `protobuf:"bytes,14,opt,name=h5_jump_number,json=h5JumpNumber,proto3" json:"h5_jump_number,omitempty"`
	H5JumpParam   string                 `protobuf:"bytes,15,opt,name=h5_jump_param,json=h5JumpParam,proto3" json:"h5_jump_param,omitempty"`
	JumpType      int32                  `protobuf:"varint,16,opt,name=jump_type,json=jumpType,proto3" json:"jump_type,omitempty"`
	ButtonDesc    string                 `protobuf:"bytes,23,opt,name=button_desc,json=buttonDesc,proto3" json:"button_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbContent_TiebaPlusInfo) Reset() {
	*x = PbContent_TiebaPlusInfo{}
	mi := &file_PbContent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbContent_TiebaPlusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbContent_TiebaPlusInfo) ProtoMessage() {}

func (x *PbContent_TiebaPlusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_PbContent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbContent_TiebaPlusInfo.ProtoReflect.Descriptor instead.
func (*PbContent_TiebaPlusInfo) Descriptor() ([]byte, []int) {
	return file_PbContent_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PbContent_TiebaPlusInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PbContent_TiebaPlusInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *PbContent_TiebaPlusInfo) GetJumpUrl() string {
	if x != nil {
		return x.JumpUrl
	}
	return ""
}

func (x *PbContent_TiebaPlusInfo) GetAppIcon() string {
	if x != nil {
		return x.AppIcon
	}
	return ""
}

func (x *PbContent_TiebaPlusInfo) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *PbContent_TiebaPlusInfo) GetH5JumpType() int32 {
	if x != nil {
		return x.H5JumpType
	}
	return 0
}

func (x *PbContent_TiebaPlusInfo) GetH5JumpNumber() string {
	if x != nil {
		return x.H5JumpNumber
	}
	return ""
}

func (x *PbContent_TiebaPlusInfo) GetH5JumpParam() string {
	if x != nil {
		return x.H5JumpParam
	}
	return ""
}

func (x *PbContent_TiebaPlusInfo) GetJumpType() int32 {
	if x != nil {
		return x.JumpType
	}
	return 0
}

func (x *PbContent_TiebaPlusInfo) GetButtonDesc() string {
	if x != nil {
		return x.ButtonDesc
	}
	return ""
}

type PbContent_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbContent_Item) Reset() {
	*x = PbContent_Item{}
	mi := &file_PbContent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbContent_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbContent_Item) ProtoMessage() {}

func (x *PbContent_Item) ProtoReflect() protoreflect.Message {
	mi := &file_PbContent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbContent_Item.ProtoReflect.Descriptor instead.
func (*PbContent_Item) Descriptor() ([]byte, []int) {
	return file_PbContent_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PbContent_Item) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

var File_PbContent_proto protoreflect.FileDescriptor

const file_PbContent_proto_rawDesc = "" +
	"\n" +
	"\x0fPbContent.proto\"\xd2\x06\n" +
	"\tPbContent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x10\n" +
	"\x03src\x18\x04 \x01(\tR\x03src\x12\x14\n" +
	"\x05bsize\x18\x05 \x01(\tR\x05bsize\x12\x17\n" +
	"\acdn_src\x18\b \x01(\tR\x06cdnSrc\x12\x1e\n" +
	"\vbig_cdn_src\x18\t \x01(\tR\tbigCdnSrc\x12\f\n" +
	"\x01c\x18\v \x01(\tR\x01c\x12\x1b\n" +
	"\tvoice_md5\x18\f \x01(\tR\bvoiceMd5\x12\x1f\n" +
	"\vduring_time\x18\r \x01(\rR\n" +
	"duringTime\x12\x10\n" +
	"\x03uid\x18\x0f \x01(\x03R\x03uid\x12\x14\n" +
	"\x05width\x18\x12 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x13 \x01(\rR\x06height\x12\x1d\n" +
	"\n" +
	"origin_src\x18\x19 \x01(\tR\toriginSrc\x12\x1f\n" +
	"\vorigin_size\x18\x1b \x01(\rR\n" +
	"originSize\x12\x14\n" +
	"\x05count\x18\x1c \x01(\x05R\x05count\x12?\n" +
	"\x0etiebaplus_info\x18( \x01(\v2\x18.PbContent.TiebaPlusInfoR\rtiebaplusInfo\x12#\n" +
	"\x04item\x18) \x01(\v2\x0f.PbContent.ItemR\x04item\x1a\xba\x02\n" +
	"\rTiebaPlusInfo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x19\n" +
	"\bjump_url\x18\x03 \x01(\tR\ajumpUrl\x12\x19\n" +
	"\bapp_icon\x18\x06 \x01(\tR\aappIcon\x12\x1f\n" +
	"\vtarget_type\x18\f \x01(\x05R\n" +
	"targetType\x12 \n" +
	"\fh5_jump_type\x18\r \x01(\x05R\n" +
	"h5JumpType\x12$\n" +
	"\x0eh5_jump_number\x18\x0e \x01(\tR\fh5JumpNumber\x12\"\n" +
	"\rh5_jump_param\x18\x0f \x01(\tR\vh5JumpParam\x12\x1b\n" +
	"\tjump_type\x18\x10 \x01(\x05R\bjumpType\x12\x1f\n" +
	"\vbutton_desc\x18\x17 \x01(\tR\n" +
	"buttonDesc\x1a#\n" +
	"\x04Item\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemNameB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_PbContent_proto_rawDescOnce sync.Once
	file_PbContent_proto_rawDescData []byte
)

func file_PbContent_proto_rawDescGZIP() []byte {
	file_PbContent_proto_rawDescOnce.Do(func() {
		file_PbContent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PbContent_proto_rawDesc), len(file_PbContent_proto_rawDesc)))
	})
	return file_PbContent_proto_rawDescData
}

var file_PbContent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_PbContent_proto_goTypes = []any{
	(*PbContent)(nil),               // 0: PbContent
	(*PbContent_TiebaPlusInfo)(nil), // 1: PbContent.TiebaPlusInfo
	(*PbContent_Item)(nil),          // 2: PbContent.Item
}
var file_PbContent_proto_depIdxs = []int32{
	1, // 0: PbContent.tiebaplus_info:type_name -> PbContent.TiebaPlusInfo
	2, // 1: PbContent.item:type_name -> PbContent.Item
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PbContent_proto_init() }
func file_PbContent_proto_init() {
	if File_PbContent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PbContent_proto_rawDesc), len(file_PbContent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PbContent_proto_goTypes,
		DependencyIndexes: file_PbContent_proto_depIdxs,
		MessageInfos:      file_PbContent_proto_msgTypes,
	}.Build()
	File_PbContent_proto = out.File
	file_PbContent_proto_goTypes = nil
	file_PbContent_proto_depIdxs = nil
}
