// tbclient.PbFloor.PbFloorReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: PbFloorReqIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbFloorReqIdl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *PbFloorReqIdl_DataReq `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbFloorReqIdl) Reset() {
	*x = PbFloorReqIdl{}
	mi := &file_PbFloorReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbFloorReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbFloorReqIdl) ProtoMessage() {}

func (x *PbFloorReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_PbFloorReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbFloorReqIdl.ProtoReflect.Descriptor instead.
func (*PbFloorReqIdl) Descriptor() ([]byte, []int) {
	return file_PbFloorReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *PbFloorReqIdl) GetData() *PbFloorReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type PbFloorReqIdl_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *CommonReq             `protobuf:"bytes,9,opt,name=common,proto3" json:"common,omitempty"`
	Kz            int64                  `protobuf:"varint,1,opt,name=kz,proto3" json:"kz,omitempty"`
	Pid           int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Spid          int64                  `protobuf:"varint,3,opt,name=spid,proto3" json:"spid,omitempty"`
	Pn            int32                  `protobuf:"varint,4,opt,name=pn,proto3" json:"pn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbFloorReqIdl_DataReq) Reset() {
	*x = PbFloorReqIdl_DataReq{}
	mi := &file_PbFloorReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbFloorReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbFloorReqIdl_DataReq) ProtoMessage() {}

func (x *PbFloorReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_PbFloorReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbFloorReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*PbFloorReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_PbFloorReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PbFloorReqIdl_DataReq) GetCommon() *CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *PbFloorReqIdl_DataReq) GetKz() int64 {
	if x != nil {
		return x.Kz
	}
	return 0
}

func (x *PbFloorReqIdl_DataReq) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PbFloorReqIdl_DataReq) GetSpid() int64 {
	if x != nil {
		return x.Spid
	}
	return 0
}

func (x *PbFloorReqIdl_DataReq) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

var File_PbFloorReqIdl_proto protoreflect.FileDescriptor

const file_PbFloorReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x13PbFloorReqIdl.proto\x1a\x0fCommonReq.proto\"\xb0\x01\n" +
	"\rPbFloorReqIdl\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.PbFloorReqIdl.DataReqR\x04data\x1as\n" +
	"\aDataReq\x12\"\n" +
	"\x06common\x18\t \x01(\v2\n" +
	".CommonReqR\x06common\x12\x0e\n" +
	"\x02kz\x18\x01 \x01(\x03R\x02kz\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\x12\x12\n" +
	"\x04spid\x18\x03 \x01(\x03R\x04spid\x12\x0e\n" +
	"\x02pn\x18\x04 \x01(\x05R\x02pnB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_PbFloorReqIdl_proto_rawDescOnce sync.Once
	file_PbFloorReqIdl_proto_rawDescData []byte
)

func file_PbFloorReqIdl_proto_rawDescGZIP() []byte {
	file_PbFloorReqIdl_proto_rawDescOnce.Do(func() {
		file_PbFloorReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PbFloorReqIdl_proto_rawDesc), len(file_PbFloorReqIdl_proto_rawDesc)))
	})
	return file_PbFloorReqIdl_proto_rawDescData
}

var file_PbFloorReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_PbFloorReqIdl_proto_goTypes = []any{
	(*PbFloorReqIdl)(nil),         // 0: PbFloorReqIdl
	(*PbFloorReqIdl_DataReq)(nil), // 1: PbFloorReqIdl.DataReq
	(*CommonReq)(nil),             // 2: CommonReq
}
var file_PbFloorReqIdl_proto_depIdxs = []int32{
	1, // 0: PbFloorReqIdl.data:type_name -> PbFloorReqIdl.DataReq
	2, // 1: PbFloorReqIdl.DataReq.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PbFloorReqIdl_proto_init() }
func file_PbFloorReqIdl_proto_init() {
	if File_PbFloorReqIdl_proto != nil {
		return
	}
	file_CommonReq_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PbFloorReqIdl_proto_rawDesc), len(file_PbFloorReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PbFloorReqIdl_proto_goTypes,
		DependencyIndexes: file_PbFloorReqIdl_proto_depIdxs,
		MessageInfos:      file_PbFloorReqIdl_proto_msgTypes,
	}.Build()
	File_PbFloorReqIdl_proto = out.File
	file_PbFloorReqIdl_proto_goTypes = nil
	file_PbFloorReqIdl_proto_depIdxs = nil
}
