// tbclient.PbPage.PbPageReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: PbPageReqIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbPageReqIdl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *PbPageReqIdl_DataReq  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbPageReqIdl) Reset() {
	*x = PbPageReqIdl{}
	mi := &file_PbPageReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbPageReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbPageReqIdl) ProtoMessage() {}

func (x *PbPageReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_PbPageReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbPageReqIdl.ProtoReflect.Descriptor instead.
func (*PbPageReqIdl) Descriptor() ([]byte, []int) {
	return file_PbPageReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *PbPageReqIdl) GetData() *PbPageReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type PbPageReqIdl_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *CommonReq             `protobuf:"bytes,25,opt,name=common,proto3" json:"common,omitempty"`
	Kz            int64                  `protobuf:"varint,4,opt,name=kz,proto3" json:"kz,omitempty"`
	Lz            int32                  `protobuf:"varint,5,opt,name=lz,proto3" json:"lz,omitempty"`
	R             int32                  `protobuf:"varint,6,opt,name=r,proto3" json:"r,omitempty"`
	Pid           int64                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	WithFloor     int32                  `protobuf:"varint,8,opt,name=with_floor,json=withFloor,proto3" json:"with_floor,omitempty"`
	FloorRn       int32                  `protobuf:"varint,9,opt,name=floor_rn,json=floorRn,proto3" json:"floor_rn,omitempty"`
	Rn            int32                  `protobuf:"varint,13,opt,name=rn,proto3" json:"rn,omitempty"`
	Pn            int32                  `protobuf:"varint,18,opt,name=pn,proto3" json:"pn,omitempty"`
	FloorSortType int32                  `protobuf:"varint,74,opt,name=floor_sort_type,json=floorSortType,proto3" json:"floor_sort_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbPageReqIdl_DataReq) Reset() {
	*x = PbPageReqIdl_DataReq{}
	mi := &file_PbPageReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbPageReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbPageReqIdl_DataReq) ProtoMessage() {}

func (x *PbPageReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_PbPageReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbPageReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*PbPageReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_PbPageReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PbPageReqIdl_DataReq) GetCommon() *CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *PbPageReqIdl_DataReq) GetKz() int64 {
	if x != nil {
		return x.Kz
	}
	return 0
}

func (x *PbPageReqIdl_DataReq) GetLz() int32 {
	if x != nil {
		return x.Lz
	}
	return 0
}

func (x *PbPageReqIdl_DataReq) GetR() int32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *PbPageReqIdl_DataReq) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PbPageReqIdl_DataReq) GetWithFloor() int32 {
	if x != nil {
		return x.WithFloor
	}
	return 0
}

func (x *PbPageReqIdl_DataReq) GetFloorRn() int32 {
	if x != nil {
		return x.FloorRn
	}
	return 0
}

func (x *PbPageReqIdl_DataReq) GetRn() int32 {
	if x != nil {
		return x.Rn
	}
	return 0
}

func (x *PbPageReqIdl_DataReq) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *PbPageReqIdl_DataReq) GetFloorSortType() int32 {
	if x != nil {
		return x.FloorSortType
	}
	return 0
}

var File_PbPageReqIdl_proto protoreflect.FileDescriptor

const file_PbPageReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x12PbPageReqIdl.proto\x1a\x0fCommonReq.proto\"\xab\x02\n" +
	"\fPbPageReqIdl\x12)\n" +
	"\x04data\x18\x01 \x01(\v2\x15.PbPageReqIdl.DataReqR\x04data\x1a\xef\x01\n" +
	"\aDataReq\x12\"\n" +
	"\x06common\x18\x19 \x01(\v2\n" +
	".CommonReqR\x06common\x12\x0e\n" +
	"\x02kz\x18\x04 \x01(\x03R\x02kz\x12\x0e\n" +
	"\x02lz\x18\x05 \x01(\x05R\x02lz\x12\f\n" +
	"\x01r\x18\x06 \x01(\x05R\x01r\x12\x10\n" +
	"\x03pid\x18\a \x01(\x03R\x03pid\x12\x1d\n" +
	"\n" +
	"with_floor\x18\b \x01(\x05R\twithFloor\x12\x19\n" +
	"\bfloor_rn\x18\t \x01(\x05R\afloorRn\x12\x0e\n" +
	"\x02rn\x18\r \x01(\x05R\x02rn\x12\x0e\n" +
	"\x02pn\x18\x12 \x01(\x05R\x02pn\x12&\n" +
	"\x0ffloor_sort_type\x18J \x01(\x05R\rfloorSortTypeB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_PbPageReqIdl_proto_rawDescOnce sync.Once
	file_PbPageReqIdl_proto_rawDescData []byte
)

func file_PbPageReqIdl_proto_rawDescGZIP() []byte {
	file_PbPageReqIdl_proto_rawDescOnce.Do(func() {
		file_PbPageReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PbPageReqIdl_proto_rawDesc), len(file_PbPageReqIdl_proto_rawDesc)))
	})
	return file_PbPageReqIdl_proto_rawDescData
}

var file_PbPageReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_PbPageReqIdl_proto_goTypes = []any{
	(*PbPageReqIdl)(nil),         // 0: PbPageReqIdl
	(*PbPageReqIdl_DataReq)(nil), // 1: PbPageReqIdl.DataReq
	(*CommonReq)(nil),            // 2: CommonReq
}
var file_PbPageReqIdl_proto_depIdxs = []int32{
	1, // 0: PbPageReqIdl.data:type_name -> PbPageReqIdl.DataReq
	2, // 1: PbPageReqIdl.DataReq.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PbPageReqIdl_proto_init() }
func file_PbPageReqIdl_proto_init() {
	if File_PbPageReqIdl_proto != nil {
		return
	}
	file_CommonReq_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PbPageReqIdl_proto_rawDesc), len(file_PbPageReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PbPageReqIdl_proto_goTypes,
		DependencyIndexes: file_PbPageReqIdl_proto_depIdxs,
		MessageInfos:      file_PbPageReqIdl_proto_msgTypes,
	}.Build()
	File_PbPageReqIdl_proto = out.File
	file_PbPageReqIdl_proto_goTypes = nil
	file_PbPageReqIdl_proto_depIdxs = nil
}
