// tbclient.PbPage.PbPageResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: PbPageResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbPageResIdl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *PbPageResIdl_DataRes  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbPageResIdl) Reset() {
	*x = PbPageResIdl{}
	mi := &file_PbPageResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbPageResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbPageResIdl) ProtoMessage() {}

func (x *PbPageResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_PbPageResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbPageResIdl.ProtoReflect.Descriptor instead.
func (*PbPageResIdl) Descriptor() ([]byte, []int) {
	return file_PbPageResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *PbPageResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *PbPageResIdl) GetData() *PbPageResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type PbPageResIdl_DataRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forum         *SimpleForum           `protobuf:"bytes,2,opt,name=forum,proto3" json:"forum,omitempty"`
	Page          *Page                  `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	PostList      []*Post                `protobuf:"bytes,6,rep,name=post_list,json=postList,proto3" json:"post_list,omitempty"`
	Thread        *ThreadInfo            `protobuf:"bytes,8,opt,name=thread,proto3" json:"thread,omitempty"`
	UserList      []*User                `protobuf:"bytes,13,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	ThreadFreqNum int64                  `protobuf:"varint,37,opt,name=thread_freq_num,json=threadFreqNum,proto3" json:"thread_freq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbPageResIdl_DataRes) Reset() {
	*x = PbPageResIdl_DataRes{}
	mi := &file_PbPageResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbPageResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbPageResIdl_DataRes) ProtoMessage() {}

func (x *PbPageResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_PbPageResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbPageResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*PbPageResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_PbPageResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PbPageResIdl_DataRes) GetForum() *SimpleForum {
	if x != nil {
		return x.Forum
	}
	return nil
}

func (x *PbPageResIdl_DataRes) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PbPageResIdl_DataRes) GetPostList() []*Post {
	if x != nil {
		return x.PostList
	}
	return nil
}

func (x *PbPageResIdl_DataRes) GetThread() *ThreadInfo {
	if x != nil {
		return x.Thread
	}
	return nil
}

func (x *PbPageResIdl_DataRes) GetUserList() []*User {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *PbPageResIdl_DataRes) GetThreadFreqNum() int64 {
	if x != nil {
		return x.ThreadFreqNum
	}
	return 0
}

var File_PbPageResIdl_proto protoreflect.FileDescriptor

const file_PbPageResIdl_proto_rawDesc = "" +
	"\n" +
	"\x12PbPageResIdl.proto\x1a\vError.proto\x1a\x11SimpleForum.proto\x1a\n" +
	"Page.proto\x1a\n" +
	"Post.proto\x1a\x10ThreadInfo.proto\x1a\n" +
	"User.proto\"\xb7\x02\n" +
	"\fPbPageResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x12)\n" +
	"\x04data\x18\x02 \x01(\v2\x15.PbPageResIdl.DataResR\x04data\x1a\xdd\x01\n" +
	"\aDataRes\x12\"\n" +
	"\x05forum\x18\x02 \x01(\v2\f.SimpleForumR\x05forum\x12\x19\n" +
	"\x04page\x18\x03 \x01(\v2\x05.PageR\x04page\x12\"\n" +
	"\tpost_list\x18\x06 \x03(\v2\x05.PostR\bpostList\x12#\n" +
	"\x06thread\x18\b \x01(\v2\v.ThreadInfoR\x06thread\x12\"\n" +
	"\tuser_list\x18\r \x03(\v2\x05.UserR\buserList\x12&\n" +
	"\x0fthread_freq_num\x18% \x01(\x03R\rthreadFreqNumB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_PbPageResIdl_proto_rawDescOnce sync.Once
	file_PbPageResIdl_proto_rawDescData []byte
)

func file_PbPageResIdl_proto_rawDescGZIP() []byte {
	file_PbPageResIdl_proto_rawDescOnce.Do(func() {
		file_PbPageResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PbPageResIdl_proto_rawDesc), len(file_PbPageResIdl_proto_rawDesc)))
	})
	return file_PbPageResIdl_proto_rawDescData
}

var file_PbPageResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_PbPageResIdl_proto_goTypes = []any{
	(*PbPageResIdl)(nil),         // 0: PbPageResIdl
	(*PbPageResIdl_DataRes)(nil), // 1: PbPageResIdl.DataRes
	(*Error)(nil),                // 2: Error
	(*SimpleForum)(nil),          // 3: SimpleForum
	(*Page)(nil),                 // 4: Page
	(*Post)(nil),                 // 5: Post
	(*ThreadInfo)(nil),           // 6: ThreadInfo
	(*User)(nil),                 // 7: User
}
var file_PbPageResIdl_proto_depIdxs = []int32{
	2, // 0: PbPageResIdl.error:type_name -> Error
	1, // 1: PbPageResIdl.data:type_name -> PbPageResIdl.DataRes
	3, // 2: PbPageResIdl.DataRes.forum:type_name -> SimpleForum
	4, // 3: PbPageResIdl.DataRes.page:type_name -> Page
	5, // 4: PbPageResIdl.DataRes.post_list:type_name -> Post
	6, // 5: PbPageResIdl.DataRes.thread:type_name -> ThreadInfo
	7, // 6: PbPageResIdl.DataRes.user_list:type_name -> User
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_PbPageResIdl_proto_init() }
func file_PbPageResIdl_proto_init() {
	if File_PbPageResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	file_SimpleForum_proto_init()
	file_Page_proto_init()
	file_Post_proto_init()
	file_ThreadInfo_proto_init()
	file_User_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PbPageResIdl_proto_rawDesc), len(file_PbPageResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PbPageResIdl_proto_goTypes,
		DependencyIndexes: file_PbPageResIdl_proto_depIdxs,
		MessageInfos:      file_PbPageResIdl_proto_msgTypes,
	}.Build()
	File_PbPageResIdl_proto = out.File
	file_PbPageResIdl_proto_goTypes = nil
	file_PbPageResIdl_proto_depIdxs = nil
}
