// tbclient.Post

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: Post.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Post struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Floor          uint32                 `protobuf:"varint,3,opt,name=floor,proto3" json:"floor,omitempty"`
	Time           uint32                 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Content        []*PbContent           `protobuf:"bytes,5,rep,name=content,proto3" json:"content,omitempty"`
	SubPostNumber  uint32                 `protobuf:"varint,13,opt,name=sub_post_number,json=subPostNumber,proto3" json:"sub_post_number,omitempty"`
	AuthorId       int64                  `protobuf:"varint,19,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	SubPostList    *Post_SubPost          `protobuf:"bytes,15,opt,name=sub_post_list,json=subPostList,proto3" json:"sub_post_list,omitempty"`
	Signature      *Post_SignatureData    `protobuf:"bytes,21,opt,name=signature,proto3" json:"signature,omitempty"`
	Author         *User                  `protobuf:"bytes,23,opt,name=author,proto3" json:"author,omitempty"`
	Agree          *Agree                 `protobuf:"bytes,37,opt,name=agree,proto3" json:"agree,omitempty"`
	Tid            int64                  `protobuf:"varint,46,opt,name=tid,proto3" json:"tid,omitempty"`
	CustomFigure   *Post_CustomFigure     `protobuf:"bytes,60,opt,name=custom_figure,json=customFigure,proto3" json:"custom_figure,omitempty"`
	CustomState    *Post_CustomState      `protobuf:"bytes,61,opt,name=custom_state,json=customState,proto3" json:"custom_state,omitempty"`
	ChatContent    *Post_ChatContent      `protobuf:"bytes,78,opt,name=chat_content,json=chatContent,proto3" json:"chat_content,omitempty"`
	SpriteMemeInfo *Post_SpriteMemeInfo   `protobuf:"bytes,79,opt,name=sprite_meme_info,json=spriteMemeInfo,proto3" json:"sprite_meme_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_Post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_Post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_Post_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetFloor() uint32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *Post) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Post) GetContent() []*PbContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Post) GetSubPostNumber() uint32 {
	if x != nil {
		return x.SubPostNumber
	}
	return 0
}

func (x *Post) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Post) GetSubPostList() *Post_SubPost {
	if x != nil {
		return x.SubPostList
	}
	return nil
}

func (x *Post) GetSignature() *Post_SignatureData {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Post) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Post) GetAgree() *Agree {
	if x != nil {
		return x.Agree
	}
	return nil
}

func (x *Post) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *Post) GetCustomFigure() *Post_CustomFigure {
	if x != nil {
		return x.CustomFigure
	}
	return nil
}

func (x *Post) GetCustomState() *Post_CustomState {
	if x != nil {
		return x.CustomState
	}
	return nil
}

func (x *Post) GetChatContent() *Post_ChatContent {
	if x != nil {
		return x.ChatContent
	}
	return nil
}

func (x *Post) GetSpriteMemeInfo() *Post_SpriteMemeInfo {
	if x != nil {
		return x.SpriteMemeInfo
	}
	return nil
}

type Post_SubPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubPostList   []*SubPostList         `protobuf:"bytes,2,rep,name=sub_post_list,json=subPostList,proto3" json:"sub_post_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post_SubPost) Reset() {
	*x = Post_SubPost{}
	mi := &file_Post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post_SubPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post_SubPost) ProtoMessage() {}

func (x *Post_SubPost) ProtoReflect() protoreflect.Message {
	mi := &file_Post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post_SubPost.ProtoReflect.Descriptor instead.
func (*Post_SubPost) Descriptor() ([]byte, []int) {
	return file_Post_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Post_SubPost) GetSubPostList() []*SubPostList {
	if x != nil {
		return x.SubPostList
	}
	return nil
}

type Post_SignatureData struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Content       []*Post_SignatureData_SignatureContent `protobuf:"bytes,4,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post_SignatureData) Reset() {
	*x = Post_SignatureData{}
	mi := &file_Post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post_SignatureData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post_SignatureData) ProtoMessage() {}

func (x *Post_SignatureData) ProtoReflect() protoreflect.Message {
	mi := &file_Post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post_SignatureData.ProtoReflect.Descriptor instead.
func (*Post_SignatureData) Descriptor() ([]byte, []int) {
	return file_Post_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Post_SignatureData) GetContent() []*Post_SignatureData_SignatureContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type Post_CustomFigure struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BackgroundValue string                 `protobuf:"bytes,3,opt,name=background_value,json=backgroundValue,proto3" json:"background_value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Post_CustomFigure) Reset() {
	*x = Post_CustomFigure{}
	mi := &file_Post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post_CustomFigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post_CustomFigure) ProtoMessage() {}

func (x *Post_CustomFigure) ProtoReflect() protoreflect.Message {
	mi := &file_Post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post_CustomFigure.ProtoReflect.Descriptor instead.
func (*Post_CustomFigure) Descriptor() ([]byte, []int) {
	return file_Post_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Post_CustomFigure) GetBackgroundValue() string {
	if x != nil {
		return x.BackgroundValue
	}
	return ""
}

type Post_CustomState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post_CustomState) Reset() {
	*x = Post_CustomState{}
	mi := &file_Post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post_CustomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post_CustomState) ProtoMessage() {}

func (x *Post_CustomState) ProtoReflect() protoreflect.Message {
	mi := &file_Post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post_CustomState.ProtoReflect.Descriptor instead.
func (*Post_CustomState) Descriptor() ([]byte, []int) {
	return file_Post_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Post_CustomState) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Post_ChatContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotUk         string                 `protobuf:"bytes,1,opt,name=bot_uk,json=botUk,proto3" json:"bot_uk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post_ChatContent) Reset() {
	*x = Post_ChatContent{}
	mi := &file_Post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post_ChatContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post_ChatContent) ProtoMessage() {}

func (x *Post_ChatContent) ProtoReflect() protoreflect.Message {
	mi := &file_Post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post_ChatContent.ProtoReflect.Descriptor instead.
func (*Post_ChatContent) Descriptor() ([]byte, []int) {
	return file_Post_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Post_ChatContent) GetBotUk() string {
	if x != nil {
		return x.BotUk
	}
	return ""
}

type Post_SpriteMemeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemeId        int64                  `protobuf:"varint,1,opt,name=meme_id,json=memeId,proto3" json:"meme_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post_SpriteMemeInfo) Reset() {
	*x = Post_SpriteMemeInfo{}
	mi := &file_Post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post_SpriteMemeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post_SpriteMemeInfo) ProtoMessage() {}

func (x *Post_SpriteMemeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post_SpriteMemeInfo.ProtoReflect.Descriptor instead.
func (*Post_SpriteMemeInfo) Descriptor() ([]byte, []int) {
	return file_Post_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Post_SpriteMemeInfo) GetMemeId() int64 {
	if x != nil {
		return x.MemeId
	}
	return 0
}

type Post_SignatureData_SignatureContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post_SignatureData_SignatureContent) Reset() {
	*x = Post_SignatureData_SignatureContent{}
	mi := &file_Post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post_SignatureData_SignatureContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post_SignatureData_SignatureContent) ProtoMessage() {}

func (x *Post_SignatureData_SignatureContent) ProtoReflect() protoreflect.Message {
	mi := &file_Post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post_SignatureData_SignatureContent.ProtoReflect.Descriptor instead.
func (*Post_SignatureData_SignatureContent) Descriptor() ([]byte, []int) {
	return file_Post_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Post_SignatureData_SignatureContent) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Post_SignatureData_SignatureContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_Post_proto protoreflect.FileDescriptor

const file_Post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"Post.proto\x1a\x0fPbContent.proto\x1a\x11SubPostList.proto\x1a\n" +
	"User.proto\x1a\vAgree.proto\"\xc5\a\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05floor\x18\x03 \x01(\rR\x05floor\x12\x12\n" +
	"\x04time\x18\x04 \x01(\rR\x04time\x12$\n" +
	"\acontent\x18\x05 \x03(\v2\n" +
	".PbContentR\acontent\x12&\n" +
	"\x0fsub_post_number\x18\r \x01(\rR\rsubPostNumber\x12\x1b\n" +
	"\tauthor_id\x18\x13 \x01(\x03R\bauthorId\x121\n" +
	"\rsub_post_list\x18\x0f \x01(\v2\r.Post.SubPostR\vsubPostList\x121\n" +
	"\tsignature\x18\x15 \x01(\v2\x13.Post.SignatureDataR\tsignature\x12\x1d\n" +
	"\x06author\x18\x17 \x01(\v2\x05.UserR\x06author\x12\x1c\n" +
	"\x05agree\x18% \x01(\v2\x06.AgreeR\x05agree\x12\x10\n" +
	"\x03tid\x18. \x01(\x03R\x03tid\x127\n" +
	"\rcustom_figure\x18< \x01(\v2\x12.Post.CustomFigureR\fcustomFigure\x124\n" +
	"\fcustom_state\x18= \x01(\v2\x11.Post.CustomStateR\vcustomState\x124\n" +
	"\fchat_content\x18N \x01(\v2\x11.Post.ChatContentR\vchatContent\x12>\n" +
	"\x10sprite_meme_info\x18O \x01(\v2\x14.Post.SpriteMemeInfoR\x0espriteMemeInfo\x1a;\n" +
	"\aSubPost\x120\n" +
	"\rsub_post_list\x18\x02 \x03(\v2\f.SubPostListR\vsubPostList\x1a\x8b\x01\n" +
	"\rSignatureData\x12>\n" +
	"\acontent\x18\x04 \x03(\v2$.Post.SignatureData.SignatureContentR\acontent\x1a:\n" +
	"\x10SignatureContent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x1a9\n" +
	"\fCustomFigure\x12)\n" +
	"\x10background_value\x18\x03 \x01(\tR\x0fbackgroundValue\x1a'\n" +
	"\vCustomState\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x1a$\n" +
	"\vChatContent\x12\x15\n" +
	"\x06bot_uk\x18\x01 \x01(\tR\x05botUk\x1a)\n" +
	"\x0eSpriteMemeInfo\x12\x17\n" +
	"\ameme_id\x18\x01 \x01(\x03R\x06memeIdB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_Post_proto_rawDescOnce sync.Once
	file_Post_proto_rawDescData []byte
)

func file_Post_proto_rawDescGZIP() []byte {
	file_Post_proto_rawDescOnce.Do(func() {
		file_Post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Post_proto_rawDesc), len(file_Post_proto_rawDesc)))
	})
	return file_Post_proto_rawDescData
}

var file_Post_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_Post_proto_goTypes = []any{
	(*Post)(nil),                                // 0: Post
	(*Post_SubPost)(nil),                        // 1: Post.SubPost
	(*Post_SignatureData)(nil),                  // 2: Post.SignatureData
	(*Post_CustomFigure)(nil),                   // 3: Post.CustomFigure
	(*Post_CustomState)(nil),                    // 4: Post.CustomState
	(*Post_ChatContent)(nil),                    // 5: Post.ChatContent
	(*Post_SpriteMemeInfo)(nil),                 // 6: Post.SpriteMemeInfo
	(*Post_SignatureData_SignatureContent)(nil), // 7: Post.SignatureData.SignatureContent
	(*PbContent)(nil),                           // 8: PbContent
	(*User)(nil),                                // 9: User
	(*Agree)(nil),                               // 10: Agree
	(*SubPostList)(nil),                         // 11: SubPostList
}
var file_Post_proto_depIdxs = []int32{
	8,  // 0: Post.content:type_name -> PbContent
	1,  // 1: Post.sub_post_list:type_name -> Post.SubPost
	2,  // 2: Post.signature:type_name -> Post.SignatureData
	9,  // 3: Post.author:type_name -> User
	10, // 4: Post.agree:type_name -> Agree
	3,  // 5: Post.custom_figure:type_name -> Post.CustomFigure
	4,  // 6: Post.custom_state:type_name -> Post.CustomState
	5,  // 7: Post.chat_content:type_name -> Post.ChatContent
	6,  // 8: Post.sprite_meme_info:type_name -> Post.SpriteMemeInfo
	11, // 9: Post.SubPost.sub_post_list:type_name -> SubPostList
	7,  // 10: Post.SignatureData.content:type_name -> Post.SignatureData.SignatureContent
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_Post_proto_init() }
func file_Post_proto_init() {
	if File_Post_proto != nil {
		return
	}
	file_PbContent_proto_init()
	file_SubPostList_proto_init()
	file_User_proto_init()
	file_Agree_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Post_proto_rawDesc), len(file_Post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Post_proto_goTypes,
		DependencyIndexes: file_Post_proto_depIdxs,
		MessageInfos:      file_Post_proto_msgTypes,
	}.Build()
	File_Post_proto = out.File
	file_Post_proto_goTypes = nil
	file_Post_proto_depIdxs = nil
}
