// tbclient.PostInfoList

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: PostInfoList.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostInfoList struct {
	state            protoimpl.MessageState          `protogen:"open.v1"`
	ForumId          uint64                          `protobuf:"varint,1,opt,name=forum_id,json=forumId,proto3" json:"forum_id,omitempty"`
	ThreadId         uint64                          `protobuf:"varint,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	PostId           uint64                          `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CreateTime       uint32                          `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ForumName        string                          `protobuf:"bytes,6,opt,name=forum_name,json=forumName,proto3" json:"forum_name,omitempty"`
	Title            string                          `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Content          []*PostInfoList_PostInfoContent `protobuf:"bytes,8,rep,name=content,proto3" json:"content,omitempty"`
	UserName         string                          `protobuf:"bytes,10,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Media            []*Media                        `protobuf:"bytes,16,rep,name=media,proto3" json:"media,omitempty"`
	ReplyNum         uint32                          `protobuf:"varint,17,opt,name=reply_num,json=replyNum,proto3" json:"reply_num,omitempty"`
	UserId           int64                           `protobuf:"varint,18,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserPortrait     string                          `protobuf:"bytes,19,opt,name=user_portrait,json=userPortrait,proto3" json:"user_portrait,omitempty"`
	VoiceInfo        []*Voice                        `protobuf:"bytes,23,rep,name=voice_info,json=voiceInfo,proto3" json:"voice_info,omitempty"`
	ThreadType       uint64                          `protobuf:"varint,26,opt,name=thread_type,json=threadType,proto3" json:"thread_type,omitempty"`
	PollInfo         *PollInfo                       `protobuf:"bytes,28,opt,name=poll_info,json=pollInfo,proto3" json:"poll_info,omitempty"`
	VideoInfo        *VideoInfo                      `protobuf:"bytes,29,opt,name=video_info,json=videoInfo,proto3" json:"video_info,omitempty"`
	FreqNum          int32                           `protobuf:"varint,33,opt,name=freq_num,json=freqNum,proto3" json:"freq_num,omitempty"`
	NameShow         string                          `protobuf:"bytes,35,opt,name=name_show,json=nameShow,proto3" json:"name_show,omitempty"`
	ShareNum         int32                           `protobuf:"varint,39,opt,name=share_num,json=shareNum,proto3" json:"share_num,omitempty"`
	Agree            *Agree                          `protobuf:"bytes,40,opt,name=agree,proto3" json:"agree,omitempty"`
	IsShareThread    int32                           `protobuf:"varint,44,opt,name=is_share_thread,json=isShareThread,proto3" json:"is_share_thread,omitempty"`
	FirstPostContent []*PbContent                    `protobuf:"bytes,49,rep,name=first_post_content,json=firstPostContent,proto3" json:"first_post_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PostInfoList) Reset() {
	*x = PostInfoList{}
	mi := &file_PostInfoList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoList) ProtoMessage() {}

func (x *PostInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_PostInfoList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoList.ProtoReflect.Descriptor instead.
func (*PostInfoList) Descriptor() ([]byte, []int) {
	return file_PostInfoList_proto_rawDescGZIP(), []int{0}
}

func (x *PostInfoList) GetForumId() uint64 {
	if x != nil {
		return x.ForumId
	}
	return 0
}

func (x *PostInfoList) GetThreadId() uint64 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *PostInfoList) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostInfoList) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *PostInfoList) GetForumName() string {
	if x != nil {
		return x.ForumName
	}
	return ""
}

func (x *PostInfoList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostInfoList) GetContent() []*PostInfoList_PostInfoContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PostInfoList) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *PostInfoList) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *PostInfoList) GetReplyNum() uint32 {
	if x != nil {
		return x.ReplyNum
	}
	return 0
}

func (x *PostInfoList) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostInfoList) GetUserPortrait() string {
	if x != nil {
		return x.UserPortrait
	}
	return ""
}

func (x *PostInfoList) GetVoiceInfo() []*Voice {
	if x != nil {
		return x.VoiceInfo
	}
	return nil
}

func (x *PostInfoList) GetThreadType() uint64 {
	if x != nil {
		return x.ThreadType
	}
	return 0
}

func (x *PostInfoList) GetPollInfo() *PollInfo {
	if x != nil {
		return x.PollInfo
	}
	return nil
}

func (x *PostInfoList) GetVideoInfo() *VideoInfo {
	if x != nil {
		return x.VideoInfo
	}
	return nil
}

func (x *PostInfoList) GetFreqNum() int32 {
	if x != nil {
		return x.FreqNum
	}
	return 0
}

func (x *PostInfoList) GetNameShow() string {
	if x != nil {
		return x.NameShow
	}
	return ""
}

func (x *PostInfoList) GetShareNum() int32 {
	if x != nil {
		return x.ShareNum
	}
	return 0
}

func (x *PostInfoList) GetAgree() *Agree {
	if x != nil {
		return x.Agree
	}
	return nil
}

func (x *PostInfoList) GetIsShareThread() int32 {
	if x != nil {
		return x.IsShareThread
	}
	return 0
}

func (x *PostInfoList) GetFirstPostContent() []*PbContent {
	if x != nil {
		return x.FirstPostContent
	}
	return nil
}

type PostInfoList_PostInfoContent struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	PostContent   []*PostInfoList_PostInfoContent_Abstract `protobuf:"bytes,1,rep,name=post_content,json=postContent,proto3" json:"post_content,omitempty"`
	CreateTime    uint64                                   `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	PostType      uint64                                   `protobuf:"varint,3,opt,name=post_type,json=postType,proto3" json:"post_type,omitempty"`
	PostId        uint64                                   `protobuf:"varint,4,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoList_PostInfoContent) Reset() {
	*x = PostInfoList_PostInfoContent{}
	mi := &file_PostInfoList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoList_PostInfoContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoList_PostInfoContent) ProtoMessage() {}

func (x *PostInfoList_PostInfoContent) ProtoReflect() protoreflect.Message {
	mi := &file_PostInfoList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoList_PostInfoContent.ProtoReflect.Descriptor instead.
func (*PostInfoList_PostInfoContent) Descriptor() ([]byte, []int) {
	return file_PostInfoList_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PostInfoList_PostInfoContent) GetPostContent() []*PostInfoList_PostInfoContent_Abstract {
	if x != nil {
		return x.PostContent
	}
	return nil
}

func (x *PostInfoList_PostInfoContent) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *PostInfoList_PostInfoContent) GetPostType() uint64 {
	if x != nil {
		return x.PostType
	}
	return 0
}

func (x *PostInfoList_PostInfoContent) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type PostInfoList_PostInfoContent_Abstract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	DuringTime    string                 `protobuf:"bytes,6,opt,name=during_time,json=duringTime,proto3" json:"during_time,omitempty"`
	VoiceMd5      string                 `protobuf:"bytes,7,opt,name=voice_md5,json=voiceMd5,proto3" json:"voice_md5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoList_PostInfoContent_Abstract) Reset() {
	*x = PostInfoList_PostInfoContent_Abstract{}
	mi := &file_PostInfoList_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoList_PostInfoContent_Abstract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoList_PostInfoContent_Abstract) ProtoMessage() {}

func (x *PostInfoList_PostInfoContent_Abstract) ProtoReflect() protoreflect.Message {
	mi := &file_PostInfoList_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoList_PostInfoContent_Abstract.ProtoReflect.Descriptor instead.
func (*PostInfoList_PostInfoContent_Abstract) Descriptor() ([]byte, []int) {
	return file_PostInfoList_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PostInfoList_PostInfoContent_Abstract) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PostInfoList_PostInfoContent_Abstract) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PostInfoList_PostInfoContent_Abstract) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PostInfoList_PostInfoContent_Abstract) GetDuringTime() string {
	if x != nil {
		return x.DuringTime
	}
	return ""
}

func (x *PostInfoList_PostInfoContent_Abstract) GetVoiceMd5() string {
	if x != nil {
		return x.VoiceMd5
	}
	return ""
}

var File_PostInfoList_proto protoreflect.FileDescriptor

const file_PostInfoList_proto_rawDesc = "" +
	"\n" +
	"\x12PostInfoList.proto\x1a\vMedia.proto\x1a\vVoice.proto\x1a\x0ePollInfo.proto\x1a\x0fVideoInfo.proto\x1a\x0fPbContent.proto\x1a\vAgree.proto\"\xb1\b\n" +
	"\fPostInfoList\x12\x19\n" +
	"\bforum_id\x18\x01 \x01(\x04R\aforumId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\x04R\bthreadId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\x04R\x06postId\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\rR\n" +
	"createTime\x12\x1d\n" +
	"\n" +
	"forum_name\x18\x06 \x01(\tR\tforumName\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x127\n" +
	"\acontent\x18\b \x03(\v2\x1d.PostInfoList.PostInfoContentR\acontent\x12\x1b\n" +
	"\tuser_name\x18\n" +
	" \x01(\tR\buserName\x12\x1c\n" +
	"\x05media\x18\x10 \x03(\v2\x06.MediaR\x05media\x12\x1b\n" +
	"\treply_num\x18\x11 \x01(\rR\breplyNum\x12\x17\n" +
	"\auser_id\x18\x12 \x01(\x03R\x06userId\x12#\n" +
	"\ruser_portrait\x18\x13 \x01(\tR\fuserPortrait\x12%\n" +
	"\n" +
	"voice_info\x18\x17 \x03(\v2\x06.VoiceR\tvoiceInfo\x12\x1f\n" +
	"\vthread_type\x18\x1a \x01(\x04R\n" +
	"threadType\x12&\n" +
	"\tpoll_info\x18\x1c \x01(\v2\t.PollInfoR\bpollInfo\x12)\n" +
	"\n" +
	"video_info\x18\x1d \x01(\v2\n" +
	".VideoInfoR\tvideoInfo\x12\x19\n" +
	"\bfreq_num\x18! \x01(\x05R\afreqNum\x12\x1b\n" +
	"\tname_show\x18# \x01(\tR\bnameShow\x12\x1b\n" +
	"\tshare_num\x18' \x01(\x05R\bshareNum\x12\x1c\n" +
	"\x05agree\x18( \x01(\v2\x06.AgreeR\x05agree\x12&\n" +
	"\x0fis_share_thread\x18, \x01(\x05R\risShareThread\x128\n" +
	"\x12first_post_content\x181 \x03(\v2\n" +
	".PbContentR\x10firstPostContent\x1a\xba\x02\n" +
	"\x0fPostInfoContent\x12I\n" +
	"\fpost_content\x18\x01 \x03(\v2&.PostInfoList.PostInfoContent.AbstractR\vpostContent\x12\x1f\n" +
	"\vcreate_time\x18\x02 \x01(\x04R\n" +
	"createTime\x12\x1b\n" +
	"\tpost_type\x18\x03 \x01(\x04R\bpostType\x12\x17\n" +
	"\apost_id\x18\x04 \x01(\x04R\x06postId\x1a\x84\x01\n" +
	"\bAbstract\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x1f\n" +
	"\vduring_time\x18\x06 \x01(\tR\n" +
	"duringTime\x12\x1b\n" +
	"\tvoice_md5\x18\a \x01(\tR\bvoiceMd5B\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_PostInfoList_proto_rawDescOnce sync.Once
	file_PostInfoList_proto_rawDescData []byte
)

func file_PostInfoList_proto_rawDescGZIP() []byte {
	file_PostInfoList_proto_rawDescOnce.Do(func() {
		file_PostInfoList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PostInfoList_proto_rawDesc), len(file_PostInfoList_proto_rawDesc)))
	})
	return file_PostInfoList_proto_rawDescData
}

var file_PostInfoList_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_PostInfoList_proto_goTypes = []any{
	(*PostInfoList)(nil),                          // 0: PostInfoList
	(*PostInfoList_PostInfoContent)(nil),          // 1: PostInfoList.PostInfoContent
	(*PostInfoList_PostInfoContent_Abstract)(nil), // 2: PostInfoList.PostInfoContent.Abstract
	(*Media)(nil),                                 // 3: Media
	(*Voice)(nil),                                 // 4: Voice
	(*PollInfo)(nil),                              // 5: PollInfo
	(*VideoInfo)(nil),                             // 6: VideoInfo
	(*Agree)(nil),                                 // 7: Agree
	(*PbContent)(nil),                             // 8: PbContent
}
var file_PostInfoList_proto_depIdxs = []int32{
	1, // 0: PostInfoList.content:type_name -> PostInfoList.PostInfoContent
	3, // 1: PostInfoList.media:type_name -> Media
	4, // 2: PostInfoList.voice_info:type_name -> Voice
	5, // 3: PostInfoList.poll_info:type_name -> PollInfo
	6, // 4: PostInfoList.video_info:type_name -> VideoInfo
	7, // 5: PostInfoList.agree:type_name -> Agree
	8, // 6: PostInfoList.first_post_content:type_name -> PbContent
	2, // 7: PostInfoList.PostInfoContent.post_content:type_name -> PostInfoList.PostInfoContent.Abstract
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_PostInfoList_proto_init() }
func file_PostInfoList_proto_init() {
	if File_PostInfoList_proto != nil {
		return
	}
	file_Media_proto_init()
	file_Voice_proto_init()
	file_PollInfo_proto_init()
	file_VideoInfo_proto_init()
	file_PbContent_proto_init()
	file_Agree_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PostInfoList_proto_rawDesc), len(file_PostInfoList_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PostInfoList_proto_goTypes,
		DependencyIndexes: file_PostInfoList_proto_depIdxs,
		MessageInfos:      file_PostInfoList_proto_msgTypes,
	}.Build()
	File_PostInfoList_proto = out.File
	file_PostInfoList_proto_goTypes = nil
	file_PostInfoList_proto_depIdxs = nil
}
