// protobuf.PushNotify.PushNotifyResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: PushNotifyResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushNotifyResIdl struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	MultiMsg      []*PushNotifyResIdl_PusherMsg `protobuf:"bytes,2,rep,name=multiMsg,proto3" json:"multiMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushNotifyResIdl) Reset() {
	*x = PushNotifyResIdl{}
	mi := &file_PushNotifyResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotifyResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotifyResIdl) ProtoMessage() {}

func (x *PushNotifyResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_PushNotifyResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotifyResIdl.ProtoReflect.Descriptor instead.
func (*PushNotifyResIdl) Descriptor() ([]byte, []int) {
	return file_PushNotifyResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *PushNotifyResIdl) GetMultiMsg() []*PushNotifyResIdl_PusherMsg {
	if x != nil {
		return x.MultiMsg
	}
	return nil
}

type PushNotifyResIdl_PusherMsg struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Data          *PushNotifyResIdl_PusherMsg_PusherMsgInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushNotifyResIdl_PusherMsg) Reset() {
	*x = PushNotifyResIdl_PusherMsg{}
	mi := &file_PushNotifyResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotifyResIdl_PusherMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotifyResIdl_PusherMsg) ProtoMessage() {}

func (x *PushNotifyResIdl_PusherMsg) ProtoReflect() protoreflect.Message {
	mi := &file_PushNotifyResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotifyResIdl_PusherMsg.ProtoReflect.Descriptor instead.
func (*PushNotifyResIdl_PusherMsg) Descriptor() ([]byte, []int) {
	return file_PushNotifyResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PushNotifyResIdl_PusherMsg) GetData() *PushNotifyResIdl_PusherMsg_PusherMsgInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type PushNotifyResIdl_PusherMsg_PusherMsgInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	MsgId         int64                  `protobuf:"varint,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Et            string                 `protobuf:"bytes,6,opt,name=et,proto3" json:"et,omitempty"`
	GroupType     int32                  `protobuf:"varint,7,opt,name=groupType,proto3" json:"groupType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushNotifyResIdl_PusherMsg_PusherMsgInfo) Reset() {
	*x = PushNotifyResIdl_PusherMsg_PusherMsgInfo{}
	mi := &file_PushNotifyResIdl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotifyResIdl_PusherMsg_PusherMsgInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotifyResIdl_PusherMsg_PusherMsgInfo) ProtoMessage() {}

func (x *PushNotifyResIdl_PusherMsg_PusherMsgInfo) ProtoReflect() protoreflect.Message {
	mi := &file_PushNotifyResIdl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotifyResIdl_PusherMsg_PusherMsgInfo.ProtoReflect.Descriptor instead.
func (*PushNotifyResIdl_PusherMsg_PusherMsgInfo) Descriptor() ([]byte, []int) {
	return file_PushNotifyResIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PushNotifyResIdl_PusherMsg_PusherMsgInfo) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *PushNotifyResIdl_PusherMsg_PusherMsgInfo) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *PushNotifyResIdl_PusherMsg_PusherMsgInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PushNotifyResIdl_PusherMsg_PusherMsgInfo) GetEt() string {
	if x != nil {
		return x.Et
	}
	return ""
}

func (x *PushNotifyResIdl_PusherMsg_PusherMsgInfo) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

var File_PushNotifyResIdl_proto protoreflect.FileDescriptor

const file_PushNotifyResIdl_proto_rawDesc = "" +
	"\n" +
	"\x16PushNotifyResIdl.proto\"\x9c\x02\n" +
	"\x10PushNotifyResIdl\x127\n" +
	"\bmultiMsg\x18\x02 \x03(\v2\x1b.PushNotifyResIdl.PusherMsgR\bmultiMsg\x1a\xce\x01\n" +
	"\tPusherMsg\x12=\n" +
	"\x04data\x18\x02 \x01(\v2).PushNotifyResIdl.PusherMsg.PusherMsgInfoR\x04data\x1a\x81\x01\n" +
	"\rPusherMsgInfo\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\x03R\agroupId\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\x03R\x05msgId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x0e\n" +
	"\x02et\x18\x06 \x01(\tR\x02et\x12\x1c\n" +
	"\tgroupType\x18\a \x01(\x05R\tgroupTypeB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_PushNotifyResIdl_proto_rawDescOnce sync.Once
	file_PushNotifyResIdl_proto_rawDescData []byte
)

func file_PushNotifyResIdl_proto_rawDescGZIP() []byte {
	file_PushNotifyResIdl_proto_rawDescOnce.Do(func() {
		file_PushNotifyResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PushNotifyResIdl_proto_rawDesc), len(file_PushNotifyResIdl_proto_rawDesc)))
	})
	return file_PushNotifyResIdl_proto_rawDescData
}

var file_PushNotifyResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_PushNotifyResIdl_proto_goTypes = []any{
	(*PushNotifyResIdl)(nil),                         // 0: PushNotifyResIdl
	(*PushNotifyResIdl_PusherMsg)(nil),               // 1: PushNotifyResIdl.PusherMsg
	(*PushNotifyResIdl_PusherMsg_PusherMsgInfo)(nil), // 2: PushNotifyResIdl.PusherMsg.PusherMsgInfo
}
var file_PushNotifyResIdl_proto_depIdxs = []int32{
	1, // 0: PushNotifyResIdl.multiMsg:type_name -> PushNotifyResIdl.PusherMsg
	2, // 1: PushNotifyResIdl.PusherMsg.data:type_name -> PushNotifyResIdl.PusherMsg.PusherMsgInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PushNotifyResIdl_proto_init() }
func file_PushNotifyResIdl_proto_init() {
	if File_PushNotifyResIdl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PushNotifyResIdl_proto_rawDesc), len(file_PushNotifyResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PushNotifyResIdl_proto_goTypes,
		DependencyIndexes: file_PushNotifyResIdl_proto_depIdxs,
		MessageInfos:      file_PushNotifyResIdl_proto_msgTypes,
	}.Build()
	File_PushNotifyResIdl_proto = out.File
	file_PushNotifyResIdl_proto_goTypes = nil
	file_PushNotifyResIdl_proto_depIdxs = nil
}
