// tbclient.ReplyMe.ReplyMeResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: ReplyMeResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplyMeResIdl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *ReplyMeResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMeResIdl) Reset() {
	*x = ReplyMeResIdl{}
	mi := &file_ReplyMeResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMeResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMeResIdl) ProtoMessage() {}

func (x *ReplyMeResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_ReplyMeResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMeResIdl.ProtoReflect.Descriptor instead.
func (*ReplyMeResIdl) Descriptor() ([]byte, []int) {
	return file_ReplyMeResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *ReplyMeResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ReplyMeResIdl) GetData() *ReplyMeResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReplyMeResIdl_DataRes struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Page          *Page                              `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	ReplyList     []*ReplyMeResIdl_DataRes_ReplyList `protobuf:"bytes,2,rep,name=reply_list,json=replyList,proto3" json:"reply_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMeResIdl_DataRes) Reset() {
	*x = ReplyMeResIdl_DataRes{}
	mi := &file_ReplyMeResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMeResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMeResIdl_DataRes) ProtoMessage() {}

func (x *ReplyMeResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_ReplyMeResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMeResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*ReplyMeResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_ReplyMeResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ReplyMeResIdl_DataRes) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ReplyMeResIdl_DataRes) GetReplyList() []*ReplyMeResIdl_DataRes_ReplyList {
	if x != nil {
		return x.ReplyList
	}
	return nil
}

type ReplyMeResIdl_DataRes_ReplyList struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ThreadId         uint64                 `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	PostId           uint64                 `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Time             uint32                 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Fname            string                 `protobuf:"bytes,5,opt,name=fname,proto3" json:"fname,omitempty"`
	Content          string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	IsFloor          uint32                 `protobuf:"varint,7,opt,name=is_floor,json=isFloor,proto3" json:"is_floor,omitempty"`
	QuoteContent     string                 `protobuf:"bytes,8,opt,name=quote_content,json=quoteContent,proto3" json:"quote_content,omitempty"`
	Replyer          *User                  `protobuf:"bytes,9,opt,name=replyer,proto3" json:"replyer,omitempty"`
	QuotePid         uint64                 `protobuf:"varint,14,opt,name=quote_pid,json=quotePid,proto3" json:"quote_pid,omitempty"`
	QuoteUser        *User                  `protobuf:"bytes,15,opt,name=quote_user,json=quoteUser,proto3" json:"quote_user,omitempty"`
	ThreadAuthorUser *User                  `protobuf:"bytes,25,opt,name=thread_author_user,json=threadAuthorUser,proto3" json:"thread_author_user,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplyMeResIdl_DataRes_ReplyList) Reset() {
	*x = ReplyMeResIdl_DataRes_ReplyList{}
	mi := &file_ReplyMeResIdl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMeResIdl_DataRes_ReplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMeResIdl_DataRes_ReplyList) ProtoMessage() {}

func (x *ReplyMeResIdl_DataRes_ReplyList) ProtoReflect() protoreflect.Message {
	mi := &file_ReplyMeResIdl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMeResIdl_DataRes_ReplyList.ProtoReflect.Descriptor instead.
func (*ReplyMeResIdl_DataRes_ReplyList) Descriptor() ([]byte, []int) {
	return file_ReplyMeResIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ReplyMeResIdl_DataRes_ReplyList) GetThreadId() uint64 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *ReplyMeResIdl_DataRes_ReplyList) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *ReplyMeResIdl_DataRes_ReplyList) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ReplyMeResIdl_DataRes_ReplyList) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *ReplyMeResIdl_DataRes_ReplyList) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyMeResIdl_DataRes_ReplyList) GetIsFloor() uint32 {
	if x != nil {
		return x.IsFloor
	}
	return 0
}

func (x *ReplyMeResIdl_DataRes_ReplyList) GetQuoteContent() string {
	if x != nil {
		return x.QuoteContent
	}
	return ""
}

func (x *ReplyMeResIdl_DataRes_ReplyList) GetReplyer() *User {
	if x != nil {
		return x.Replyer
	}
	return nil
}

func (x *ReplyMeResIdl_DataRes_ReplyList) GetQuotePid() uint64 {
	if x != nil {
		return x.QuotePid
	}
	return 0
}

func (x *ReplyMeResIdl_DataRes_ReplyList) GetQuoteUser() *User {
	if x != nil {
		return x.QuoteUser
	}
	return nil
}

func (x *ReplyMeResIdl_DataRes_ReplyList) GetThreadAuthorUser() *User {
	if x != nil {
		return x.ThreadAuthorUser
	}
	return nil
}

var File_ReplyMeResIdl_proto protoreflect.FileDescriptor

const file_ReplyMeResIdl_proto_rawDesc = "" +
	"\n" +
	"\x13ReplyMeResIdl.proto\x1a\vError.proto\x1a\n" +
	"Page.proto\x1a\n" +
	"User.proto\"\xa2\x04\n" +
	"\rReplyMeResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x12*\n" +
	"\x04data\x18\x02 \x01(\v2\x16.ReplyMeResIdl.DataResR\x04data\x1a\xc6\x03\n" +
	"\aDataRes\x12\x19\n" +
	"\x04page\x18\x01 \x01(\v2\x05.PageR\x04page\x12?\n" +
	"\n" +
	"reply_list\x18\x02 \x03(\v2 .ReplyMeResIdl.DataRes.ReplyListR\treplyList\x1a\xde\x02\n" +
	"\tReplyList\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\x04R\bthreadId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x04R\x06postId\x12\x12\n" +
	"\x04time\x18\x03 \x01(\rR\x04time\x12\x14\n" +
	"\x05fname\x18\x05 \x01(\tR\x05fname\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x19\n" +
	"\bis_floor\x18\a \x01(\rR\aisFloor\x12#\n" +
	"\rquote_content\x18\b \x01(\tR\fquoteContent\x12\x1f\n" +
	"\areplyer\x18\t \x01(\v2\x05.UserR\areplyer\x12\x1b\n" +
	"\tquote_pid\x18\x0e \x01(\x04R\bquotePid\x12$\n" +
	"\n" +
	"quote_user\x18\x0f \x01(\v2\x05.UserR\tquoteUser\x123\n" +
	"\x12thread_author_user\x18\x19 \x01(\v2\x05.UserR\x10threadAuthorUserB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_ReplyMeResIdl_proto_rawDescOnce sync.Once
	file_ReplyMeResIdl_proto_rawDescData []byte
)

func file_ReplyMeResIdl_proto_rawDescGZIP() []byte {
	file_ReplyMeResIdl_proto_rawDescOnce.Do(func() {
		file_ReplyMeResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ReplyMeResIdl_proto_rawDesc), len(file_ReplyMeResIdl_proto_rawDesc)))
	})
	return file_ReplyMeResIdl_proto_rawDescData
}

var file_ReplyMeResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ReplyMeResIdl_proto_goTypes = []any{
	(*ReplyMeResIdl)(nil),                   // 0: ReplyMeResIdl
	(*ReplyMeResIdl_DataRes)(nil),           // 1: ReplyMeResIdl.DataRes
	(*ReplyMeResIdl_DataRes_ReplyList)(nil), // 2: ReplyMeResIdl.DataRes.ReplyList
	(*Error)(nil),                           // 3: Error
	(*Page)(nil),                            // 4: Page
	(*User)(nil),                            // 5: User
}
var file_ReplyMeResIdl_proto_depIdxs = []int32{
	3, // 0: ReplyMeResIdl.error:type_name -> Error
	1, // 1: ReplyMeResIdl.data:type_name -> ReplyMeResIdl.DataRes
	4, // 2: ReplyMeResIdl.DataRes.page:type_name -> Page
	2, // 3: ReplyMeResIdl.DataRes.reply_list:type_name -> ReplyMeResIdl.DataRes.ReplyList
	5, // 4: ReplyMeResIdl.DataRes.ReplyList.replyer:type_name -> User
	5, // 5: ReplyMeResIdl.DataRes.ReplyList.quote_user:type_name -> User
	5, // 6: ReplyMeResIdl.DataRes.ReplyList.thread_author_user:type_name -> User
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_ReplyMeResIdl_proto_init() }
func file_ReplyMeResIdl_proto_init() {
	if File_ReplyMeResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	file_Page_proto_init()
	file_User_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ReplyMeResIdl_proto_rawDesc), len(file_ReplyMeResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ReplyMeResIdl_proto_goTypes,
		DependencyIndexes: file_ReplyMeResIdl_proto_depIdxs,
		MessageInfos:      file_ReplyMeResIdl_proto_msgTypes,
	}.Build()
	File_ReplyMeResIdl_proto = out.File
	file_ReplyMeResIdl_proto_goTypes = nil
	file_ReplyMeResIdl_proto_depIdxs = nil
}
