// tbclient.SearchPostForum.SearchPostForumResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: SearchPostForumResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchPostForumResIdl struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Error         *Error                         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *SearchPostForumResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostForumResIdl) Reset() {
	*x = SearchPostForumResIdl{}
	mi := &file_SearchPostForumResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostForumResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostForumResIdl) ProtoMessage() {}

func (x *SearchPostForumResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_SearchPostForumResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostForumResIdl.ProtoReflect.Descriptor instead.
func (*SearchPostForumResIdl) Descriptor() ([]byte, []int) {
	return file_SearchPostForumResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *SearchPostForumResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SearchPostForumResIdl) GetData() *SearchPostForumResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchPostForumResIdl_DataRes struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	ExactMatch    *SearchPostForumResIdl_DataRes_SearchForum `protobuf:"bytes,1,opt,name=exact_match,json=exactMatch,proto3" json:"exact_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostForumResIdl_DataRes) Reset() {
	*x = SearchPostForumResIdl_DataRes{}
	mi := &file_SearchPostForumResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostForumResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostForumResIdl_DataRes) ProtoMessage() {}

func (x *SearchPostForumResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_SearchPostForumResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostForumResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*SearchPostForumResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_SearchPostForumResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SearchPostForumResIdl_DataRes) GetExactMatch() *SearchPostForumResIdl_DataRes_SearchForum {
	if x != nil {
		return x.ExactMatch
	}
	return nil
}

type SearchPostForumResIdl_DataRes_SearchForum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForumId       int64                  `protobuf:"varint,1,opt,name=forum_id,json=forumId,proto3" json:"forum_id,omitempty"`
	ForumName     string                 `protobuf:"bytes,2,opt,name=forum_name,json=forumName,proto3" json:"forum_name,omitempty"`
	TabInfo       []*FrsTabInfo          `protobuf:"bytes,9,rep,name=tab_info,json=tabInfo,proto3" json:"tab_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostForumResIdl_DataRes_SearchForum) Reset() {
	*x = SearchPostForumResIdl_DataRes_SearchForum{}
	mi := &file_SearchPostForumResIdl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostForumResIdl_DataRes_SearchForum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostForumResIdl_DataRes_SearchForum) ProtoMessage() {}

func (x *SearchPostForumResIdl_DataRes_SearchForum) ProtoReflect() protoreflect.Message {
	mi := &file_SearchPostForumResIdl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostForumResIdl_DataRes_SearchForum.ProtoReflect.Descriptor instead.
func (*SearchPostForumResIdl_DataRes_SearchForum) Descriptor() ([]byte, []int) {
	return file_SearchPostForumResIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *SearchPostForumResIdl_DataRes_SearchForum) GetForumId() int64 {
	if x != nil {
		return x.ForumId
	}
	return 0
}

func (x *SearchPostForumResIdl_DataRes_SearchForum) GetForumName() string {
	if x != nil {
		return x.ForumName
	}
	return ""
}

func (x *SearchPostForumResIdl_DataRes_SearchForum) GetTabInfo() []*FrsTabInfo {
	if x != nil {
		return x.TabInfo
	}
	return nil
}

var File_SearchPostForumResIdl_proto protoreflect.FileDescriptor

const file_SearchPostForumResIdl_proto_rawDesc = "" +
	"\n" +
	"\x1bSearchPostForumResIdl.proto\x1a\vError.proto\x1a\x10FrsTabInfo.proto\"\xb3\x02\n" +
	"\x15SearchPostForumResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x122\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.SearchPostForumResIdl.DataResR\x04data\x1a\xc7\x01\n" +
	"\aDataRes\x12K\n" +
	"\vexact_match\x18\x01 \x01(\v2*.SearchPostForumResIdl.DataRes.SearchForumR\n" +
	"exactMatch\x1ao\n" +
	"\vSearchForum\x12\x19\n" +
	"\bforum_id\x18\x01 \x01(\x03R\aforumId\x12\x1d\n" +
	"\n" +
	"forum_name\x18\x02 \x01(\tR\tforumName\x12&\n" +
	"\btab_info\x18\t \x03(\v2\v.FrsTabInfoR\atabInfoB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_SearchPostForumResIdl_proto_rawDescOnce sync.Once
	file_SearchPostForumResIdl_proto_rawDescData []byte
)

func file_SearchPostForumResIdl_proto_rawDescGZIP() []byte {
	file_SearchPostForumResIdl_proto_rawDescOnce.Do(func() {
		file_SearchPostForumResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SearchPostForumResIdl_proto_rawDesc), len(file_SearchPostForumResIdl_proto_rawDesc)))
	})
	return file_SearchPostForumResIdl_proto_rawDescData
}

var file_SearchPostForumResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_SearchPostForumResIdl_proto_goTypes = []any{
	(*SearchPostForumResIdl)(nil),                     // 0: SearchPostForumResIdl
	(*SearchPostForumResIdl_DataRes)(nil),             // 1: SearchPostForumResIdl.DataRes
	(*SearchPostForumResIdl_DataRes_SearchForum)(nil), // 2: SearchPostForumResIdl.DataRes.SearchForum
	(*Error)(nil),      // 3: Error
	(*FrsTabInfo)(nil), // 4: FrsTabInfo
}
var file_SearchPostForumResIdl_proto_depIdxs = []int32{
	3, // 0: SearchPostForumResIdl.error:type_name -> Error
	1, // 1: SearchPostForumResIdl.data:type_name -> SearchPostForumResIdl.DataRes
	2, // 2: SearchPostForumResIdl.DataRes.exact_match:type_name -> SearchPostForumResIdl.DataRes.SearchForum
	4, // 3: SearchPostForumResIdl.DataRes.SearchForum.tab_info:type_name -> FrsTabInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_SearchPostForumResIdl_proto_init() }
func file_SearchPostForumResIdl_proto_init() {
	if File_SearchPostForumResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	file_FrsTabInfo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SearchPostForumResIdl_proto_rawDesc), len(file_SearchPostForumResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SearchPostForumResIdl_proto_goTypes,
		DependencyIndexes: file_SearchPostForumResIdl_proto_depIdxs,
		MessageInfos:      file_SearchPostForumResIdl_proto_msgTypes,
	}.Build()
	File_SearchPostForumResIdl_proto = out.File
	file_SearchPostForumResIdl_proto_goTypes = nil
	file_SearchPostForumResIdl_proto_depIdxs = nil
}
