// tbclient.SearchPostForum.SearchPostForumReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: SearchPostForumReqIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchPostForumReqIdl struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Data          *SearchPostForumReqIdl_DataReq `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostForumReqIdl) Reset() {
	*x = SearchPostForumReqIdl{}
	mi := &file_SearchPostForumReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostForumReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostForumReqIdl) ProtoMessage() {}

func (x *SearchPostForumReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_SearchPostForumReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostForumReqIdl.ProtoReflect.Descriptor instead.
func (*SearchPostForumReqIdl) Descriptor() ([]byte, []int) {
	return file_SearchPostForumReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *SearchPostForumReqIdl) GetData() *SearchPostForumReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchPostForumReqIdl_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *CommonReq             `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Fname         string                 `protobuf:"bytes,2,opt,name=fname,proto3" json:"fname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostForumReqIdl_DataReq) Reset() {
	*x = SearchPostForumReqIdl_DataReq{}
	mi := &file_SearchPostForumReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostForumReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostForumReqIdl_DataReq) ProtoMessage() {}

func (x *SearchPostForumReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_SearchPostForumReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostForumReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*SearchPostForumReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_SearchPostForumReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SearchPostForumReqIdl_DataReq) GetCommon() *CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *SearchPostForumReqIdl_DataReq) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

var File_SearchPostForumReqIdl_proto protoreflect.FileDescriptor

const file_SearchPostForumReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x1bSearchPostForumReqIdl.proto\x1a\x0fCommonReq.proto\"\x90\x01\n" +
	"\x15SearchPostForumReqIdl\x122\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.SearchPostForumReqIdl.DataReqR\x04data\x1aC\n" +
	"\aDataReq\x12\"\n" +
	"\x06common\x18\x01 \x01(\v2\n" +
	".CommonReqR\x06common\x12\x14\n" +
	"\x05fname\x18\x02 \x01(\tR\x05fnameB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_SearchPostForumReqIdl_proto_rawDescOnce sync.Once
	file_SearchPostForumReqIdl_proto_rawDescData []byte
)

func file_SearchPostForumReqIdl_proto_rawDescGZIP() []byte {
	file_SearchPostForumReqIdl_proto_rawDescOnce.Do(func() {
		file_SearchPostForumReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SearchPostForumReqIdl_proto_rawDesc), len(file_SearchPostForumReqIdl_proto_rawDesc)))
	})
	return file_SearchPostForumReqIdl_proto_rawDescData
}

var file_SearchPostForumReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_SearchPostForumReqIdl_proto_goTypes = []any{
	(*SearchPostForumReqIdl)(nil),         // 0: SearchPostForumReqIdl
	(*SearchPostForumReqIdl_DataReq)(nil), // 1: SearchPostForumReqIdl.DataReq
	(*CommonReq)(nil),                     // 2: CommonReq
}
var file_SearchPostForumReqIdl_proto_depIdxs = []int32{
	1, // 0: SearchPostForumReqIdl.data:type_name -> SearchPostForumReqIdl.DataReq
	2, // 1: SearchPostForumReqIdl.DataReq.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SearchPostForumReqIdl_proto_init() }
func file_SearchPostForumReqIdl_proto_init() {
	if File_SearchPostForumReqIdl_proto != nil {
		return
	}
	file_CommonReq_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SearchPostForumReqIdl_proto_rawDesc), len(file_SearchPostForumReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SearchPostForumReqIdl_proto_goTypes,
		DependencyIndexes: file_SearchPostForumReqIdl_proto_depIdxs,
		MessageInfos:      file_SearchPostForumReqIdl_proto_msgTypes,
	}.Build()
	File_SearchPostForumReqIdl_proto = out.File
	file_SearchPostForumReqIdl_proto_goTypes = nil
	file_SearchPostForumReqIdl_proto_depIdxs = nil
}
