// tbclient.SimpleForum

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: SimpleForum.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleForum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FirstClass    string                 `protobuf:"bytes,7,opt,name=first_class,json=firstClass,proto3" json:"first_class,omitempty"`
	SecondClass   string                 `protobuf:"bytes,8,opt,name=second_class,json=secondClass,proto3" json:"second_class,omitempty"`
	MemberNum     int32                  `protobuf:"varint,12,opt,name=member_num,json=memberNum,proto3" json:"member_num,omitempty"`
	PostNum       int32                  `protobuf:"varint,13,opt,name=post_num,json=postNum,proto3" json:"post_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleForum) Reset() {
	*x = SimpleForum{}
	mi := &file_SimpleForum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleForum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleForum) ProtoMessage() {}

func (x *SimpleForum) ProtoReflect() protoreflect.Message {
	mi := &file_SimpleForum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleForum.ProtoReflect.Descriptor instead.
func (*SimpleForum) Descriptor() ([]byte, []int) {
	return file_SimpleForum_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleForum) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SimpleForum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimpleForum) GetFirstClass() string {
	if x != nil {
		return x.FirstClass
	}
	return ""
}

func (x *SimpleForum) GetSecondClass() string {
	if x != nil {
		return x.SecondClass
	}
	return ""
}

func (x *SimpleForum) GetMemberNum() int32 {
	if x != nil {
		return x.MemberNum
	}
	return 0
}

func (x *SimpleForum) GetPostNum() int32 {
	if x != nil {
		return x.PostNum
	}
	return 0
}

var File_SimpleForum_proto protoreflect.FileDescriptor

const file_SimpleForum_proto_rawDesc = "" +
	"\n" +
	"\x11SimpleForum.proto\"\xaf\x01\n" +
	"\vSimpleForum\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vfirst_class\x18\a \x01(\tR\n" +
	"firstClass\x12!\n" +
	"\fsecond_class\x18\b \x01(\tR\vsecondClass\x12\x1d\n" +
	"\n" +
	"member_num\x18\f \x01(\x05R\tmemberNum\x12\x19\n" +
	"\bpost_num\x18\r \x01(\x05R\apostNumB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_SimpleForum_proto_rawDescOnce sync.Once
	file_SimpleForum_proto_rawDescData []byte
)

func file_SimpleForum_proto_rawDescGZIP() []byte {
	file_SimpleForum_proto_rawDescOnce.Do(func() {
		file_SimpleForum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SimpleForum_proto_rawDesc), len(file_SimpleForum_proto_rawDesc)))
	})
	return file_SimpleForum_proto_rawDescData
}

var file_SimpleForum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SimpleForum_proto_goTypes = []any{
	(*SimpleForum)(nil), // 0: SimpleForum
}
var file_SimpleForum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SimpleForum_proto_init() }
func file_SimpleForum_proto_init() {
	if File_SimpleForum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SimpleForum_proto_rawDesc), len(file_SimpleForum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SimpleForum_proto_goTypes,
		DependencyIndexes: file_SimpleForum_proto_depIdxs,
		MessageInfos:      file_SimpleForum_proto_msgTypes,
	}.Build()
	File_SimpleForum_proto = out.File
	file_SimpleForum_proto_goTypes = nil
	file_SimpleForum_proto_depIdxs = nil
}
