// tbclient.SubPost

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: SubPostList.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubPostList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       []*PbContent           `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	Time          uint32                 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	AuthorId      int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Floor         uint32                 `protobuf:"varint,6,opt,name=floor,proto3" json:"floor,omitempty"`
	Author        *User                  `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	Agree         *Agree                 `protobuf:"bytes,9,opt,name=agree,proto3" json:"agree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubPostList) Reset() {
	*x = SubPostList{}
	mi := &file_SubPostList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubPostList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubPostList) ProtoMessage() {}

func (x *SubPostList) ProtoReflect() protoreflect.Message {
	mi := &file_SubPostList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubPostList.ProtoReflect.Descriptor instead.
func (*SubPostList) Descriptor() ([]byte, []int) {
	return file_SubPostList_proto_rawDescGZIP(), []int{0}
}

func (x *SubPostList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubPostList) GetContent() []*PbContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SubPostList) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SubPostList) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *SubPostList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubPostList) GetFloor() uint32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *SubPostList) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *SubPostList) GetAgree() *Agree {
	if x != nil {
		return x.Agree
	}
	return nil
}

type SubPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint64                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	SubPostList   []*SubPostList         `protobuf:"bytes,2,rep,name=sub_post_list,json=subPostList,proto3" json:"sub_post_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubPost) Reset() {
	*x = SubPost{}
	mi := &file_SubPostList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubPost) ProtoMessage() {}

func (x *SubPost) ProtoReflect() protoreflect.Message {
	mi := &file_SubPostList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubPost.ProtoReflect.Descriptor instead.
func (*SubPost) Descriptor() ([]byte, []int) {
	return file_SubPostList_proto_rawDescGZIP(), []int{1}
}

func (x *SubPost) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SubPost) GetSubPostList() []*SubPostList {
	if x != nil {
		return x.SubPostList
	}
	return nil
}

var File_SubPostList_proto protoreflect.FileDescriptor

const file_SubPostList_proto_rawDesc = "" +
	"\n" +
	"\x11SubPostList.proto\x1a\x0fPbContent.proto\x1a\n" +
	"User.proto\x1a\vAgree.proto\"\xdd\x01\n" +
	"\vSubPostList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\acontent\x18\x02 \x03(\v2\n" +
	".PbContentR\acontent\x12\x12\n" +
	"\x04time\x18\x03 \x01(\rR\x04time\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x14\n" +
	"\x05floor\x18\x06 \x01(\rR\x05floor\x12\x1d\n" +
	"\x06author\x18\a \x01(\v2\x05.UserR\x06author\x12\x1c\n" +
	"\x05agree\x18\t \x01(\v2\x06.AgreeR\x05agree\"M\n" +
	"\aSubPost\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x04R\x03pid\x120\n" +
	"\rsub_post_list\x18\x02 \x03(\v2\f.SubPostListR\vsubPostListB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_SubPostList_proto_rawDescOnce sync.Once
	file_SubPostList_proto_rawDescData []byte
)

func file_SubPostList_proto_rawDescGZIP() []byte {
	file_SubPostList_proto_rawDescOnce.Do(func() {
		file_SubPostList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SubPostList_proto_rawDesc), len(file_SubPostList_proto_rawDesc)))
	})
	return file_SubPostList_proto_rawDescData
}

var file_SubPostList_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_SubPostList_proto_goTypes = []any{
	(*SubPostList)(nil), // 0: SubPostList
	(*SubPost)(nil),     // 1: SubPost
	(*PbContent)(nil),   // 2: PbContent
	(*User)(nil),        // 3: User
	(*Agree)(nil),       // 4: Agree
}
var file_SubPostList_proto_depIdxs = []int32{
	2, // 0: SubPostList.content:type_name -> PbContent
	3, // 1: SubPostList.author:type_name -> User
	4, // 2: SubPostList.agree:type_name -> Agree
	0, // 3: SubPost.sub_post_list:type_name -> SubPostList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_SubPostList_proto_init() }
func file_SubPostList_proto_init() {
	if File_SubPostList_proto != nil {
		return
	}
	file_PbContent_proto_init()
	file_User_proto_init()
	file_Agree_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SubPostList_proto_rawDesc), len(file_SubPostList_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SubPostList_proto_goTypes,
		DependencyIndexes: file_SubPostList_proto_depIdxs,
		MessageInfos:      file_SubPostList_proto_msgTypes,
	}.Build()
	File_SubPostList_proto = out.File
	file_SubPostList_proto_goTypes = nil
	file_SubPostList_proto_depIdxs = nil
}
