// protobuf.UpdateClientInfo.UpdateClientInfoResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: UpdateClientInfoResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateClientInfoResIdl struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Error         *Error                          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *UpdateClientInfoResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientInfoResIdl) Reset() {
	*x = UpdateClientInfoResIdl{}
	mi := &file_UpdateClientInfoResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientInfoResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientInfoResIdl) ProtoMessage() {}

func (x *UpdateClientInfoResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_UpdateClientInfoResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientInfoResIdl.ProtoReflect.Descriptor instead.
func (*UpdateClientInfoResIdl) Descriptor() ([]byte, []int) {
	return file_UpdateClientInfoResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateClientInfoResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *UpdateClientInfoResIdl) GetData() *UpdateClientInfoResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateClientInfoResIdl_DataRes struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	GroupInfo     []*UpdateClientInfoResIdl_DataRes_GroupInfo `protobuf:"bytes,1,rep,name=groupInfo,proto3" json:"groupInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientInfoResIdl_DataRes) Reset() {
	*x = UpdateClientInfoResIdl_DataRes{}
	mi := &file_UpdateClientInfoResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientInfoResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientInfoResIdl_DataRes) ProtoMessage() {}

func (x *UpdateClientInfoResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_UpdateClientInfoResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientInfoResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*UpdateClientInfoResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_UpdateClientInfoResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UpdateClientInfoResIdl_DataRes) GetGroupInfo() []*UpdateClientInfoResIdl_DataRes_GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

type UpdateClientInfoResIdl_DataRes_GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	GroupType     int32                  `protobuf:"varint,20,opt,name=groupType,proto3" json:"groupType,omitempty"`
	LastMsgId     int64                  `protobuf:"varint,21,opt,name=lastMsgId,proto3" json:"lastMsgId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientInfoResIdl_DataRes_GroupInfo) Reset() {
	*x = UpdateClientInfoResIdl_DataRes_GroupInfo{}
	mi := &file_UpdateClientInfoResIdl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientInfoResIdl_DataRes_GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientInfoResIdl_DataRes_GroupInfo) ProtoMessage() {}

func (x *UpdateClientInfoResIdl_DataRes_GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_UpdateClientInfoResIdl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientInfoResIdl_DataRes_GroupInfo.ProtoReflect.Descriptor instead.
func (*UpdateClientInfoResIdl_DataRes_GroupInfo) Descriptor() ([]byte, []int) {
	return file_UpdateClientInfoResIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *UpdateClientInfoResIdl_DataRes_GroupInfo) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateClientInfoResIdl_DataRes_GroupInfo) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *UpdateClientInfoResIdl_DataRes_GroupInfo) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

var File_UpdateClientInfoResIdl_proto protoreflect.FileDescriptor

const file_UpdateClientInfoResIdl_proto_rawDesc = "" +
	"\n" +
	"\x1cUpdateClientInfoResIdl.proto\x1a\vError.proto\"\xa3\x02\n" +
	"\x16UpdateClientInfoResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x123\n" +
	"\x04data\x18\x02 \x01(\v2\x1f.UpdateClientInfoResIdl.DataResR\x04data\x1a\xb5\x01\n" +
	"\aDataRes\x12G\n" +
	"\tgroupInfo\x18\x01 \x03(\v2).UpdateClientInfoResIdl.DataRes.GroupInfoR\tgroupInfo\x1aa\n" +
	"\tGroupInfo\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\x03R\agroupId\x12\x1c\n" +
	"\tgroupType\x18\x14 \x01(\x05R\tgroupType\x12\x1c\n" +
	"\tlastMsgId\x18\x15 \x01(\x03R\tlastMsgIdB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_UpdateClientInfoResIdl_proto_rawDescOnce sync.Once
	file_UpdateClientInfoResIdl_proto_rawDescData []byte
)

func file_UpdateClientInfoResIdl_proto_rawDescGZIP() []byte {
	file_UpdateClientInfoResIdl_proto_rawDescOnce.Do(func() {
		file_UpdateClientInfoResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_UpdateClientInfoResIdl_proto_rawDesc), len(file_UpdateClientInfoResIdl_proto_rawDesc)))
	})
	return file_UpdateClientInfoResIdl_proto_rawDescData
}

var file_UpdateClientInfoResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_UpdateClientInfoResIdl_proto_goTypes = []any{
	(*UpdateClientInfoResIdl)(nil),                   // 0: UpdateClientInfoResIdl
	(*UpdateClientInfoResIdl_DataRes)(nil),           // 1: UpdateClientInfoResIdl.DataRes
	(*UpdateClientInfoResIdl_DataRes_GroupInfo)(nil), // 2: UpdateClientInfoResIdl.DataRes.GroupInfo
	(*Error)(nil), // 3: Error
}
var file_UpdateClientInfoResIdl_proto_depIdxs = []int32{
	3, // 0: UpdateClientInfoResIdl.error:type_name -> Error
	1, // 1: UpdateClientInfoResIdl.data:type_name -> UpdateClientInfoResIdl.DataRes
	2, // 2: UpdateClientInfoResIdl.DataRes.groupInfo:type_name -> UpdateClientInfoResIdl.DataRes.GroupInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_UpdateClientInfoResIdl_proto_init() }
func file_UpdateClientInfoResIdl_proto_init() {
	if File_UpdateClientInfoResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_UpdateClientInfoResIdl_proto_rawDesc), len(file_UpdateClientInfoResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UpdateClientInfoResIdl_proto_goTypes,
		DependencyIndexes: file_UpdateClientInfoResIdl_proto_depIdxs,
		MessageInfos:      file_UpdateClientInfoResIdl_proto_msgTypes,
	}.Build()
	File_UpdateClientInfoResIdl_proto = out.File
	file_UpdateClientInfoResIdl_proto_goTypes = nil
	file_UpdateClientInfoResIdl_proto_depIdxs = nil
}
