// protobuf.UpdateClientInfo.UpdateClientInfoReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: UpdateClientInfoReqIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateClientInfoReqIdl struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Cuid          string                          `protobuf:"bytes,1,opt,name=cuid,proto3" json:"cuid,omitempty"`
	Data          *UpdateClientInfoReqIdl_DataReq `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientInfoReqIdl) Reset() {
	*x = UpdateClientInfoReqIdl{}
	mi := &file_UpdateClientInfoReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientInfoReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientInfoReqIdl) ProtoMessage() {}

func (x *UpdateClientInfoReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_UpdateClientInfoReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientInfoReqIdl.ProtoReflect.Descriptor instead.
func (*UpdateClientInfoReqIdl) Descriptor() ([]byte, []int) {
	return file_UpdateClientInfoReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateClientInfoReqIdl) GetCuid() string {
	if x != nil {
		return x.Cuid
	}
	return ""
}

func (x *UpdateClientInfoReqIdl) GetData() *UpdateClientInfoReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateClientInfoReqIdl_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bduss         string                 `protobuf:"bytes,1,opt,name=bduss,proto3" json:"bduss,omitempty"`
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	SecretKey     []byte                 `protobuf:"bytes,3,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	Stoken        string                 `protobuf:"bytes,12,opt,name=stoken,proto3" json:"stoken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientInfoReqIdl_DataReq) Reset() {
	*x = UpdateClientInfoReqIdl_DataReq{}
	mi := &file_UpdateClientInfoReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientInfoReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientInfoReqIdl_DataReq) ProtoMessage() {}

func (x *UpdateClientInfoReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_UpdateClientInfoReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientInfoReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*UpdateClientInfoReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_UpdateClientInfoReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UpdateClientInfoReqIdl_DataReq) GetBduss() string {
	if x != nil {
		return x.Bduss
	}
	return ""
}

func (x *UpdateClientInfoReqIdl_DataReq) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *UpdateClientInfoReqIdl_DataReq) GetSecretKey() []byte {
	if x != nil {
		return x.SecretKey
	}
	return nil
}

func (x *UpdateClientInfoReqIdl_DataReq) GetStoken() string {
	if x != nil {
		return x.Stoken
	}
	return ""
}

var File_UpdateClientInfoReqIdl_proto protoreflect.FileDescriptor

const file_UpdateClientInfoReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x1cUpdateClientInfoReqIdl.proto\"\xd0\x01\n" +
	"\x16UpdateClientInfoReqIdl\x12\x12\n" +
	"\x04cuid\x18\x01 \x01(\tR\x04cuid\x123\n" +
	"\x04data\x18\x02 \x01(\v2\x1f.UpdateClientInfoReqIdl.DataReqR\x04data\x1am\n" +
	"\aDataReq\x12\x14\n" +
	"\x05bduss\x18\x01 \x01(\tR\x05bduss\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x1c\n" +
	"\tsecretKey\x18\x03 \x01(\fR\tsecretKey\x12\x16\n" +
	"\x06stoken\x18\f \x01(\tR\x06stokenB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_UpdateClientInfoReqIdl_proto_rawDescOnce sync.Once
	file_UpdateClientInfoReqIdl_proto_rawDescData []byte
)

func file_UpdateClientInfoReqIdl_proto_rawDescGZIP() []byte {
	file_UpdateClientInfoReqIdl_proto_rawDescOnce.Do(func() {
		file_UpdateClientInfoReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_UpdateClientInfoReqIdl_proto_rawDesc), len(file_UpdateClientInfoReqIdl_proto_rawDesc)))
	})
	return file_UpdateClientInfoReqIdl_proto_rawDescData
}

var file_UpdateClientInfoReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_UpdateClientInfoReqIdl_proto_goTypes = []any{
	(*UpdateClientInfoReqIdl)(nil),         // 0: UpdateClientInfoReqIdl
	(*UpdateClientInfoReqIdl_DataReq)(nil), // 1: UpdateClientInfoReqIdl.DataReq
}
var file_UpdateClientInfoReqIdl_proto_depIdxs = []int32{
	1, // 0: UpdateClientInfoReqIdl.data:type_name -> UpdateClientInfoReqIdl.DataReq
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_UpdateClientInfoReqIdl_proto_init() }
func file_UpdateClientInfoReqIdl_proto_init() {
	if File_UpdateClientInfoReqIdl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_UpdateClientInfoReqIdl_proto_rawDesc), len(file_UpdateClientInfoReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UpdateClientInfoReqIdl_proto_goTypes,
		DependencyIndexes: file_UpdateClientInfoReqIdl_proto_depIdxs,
		MessageInfos:      file_UpdateClientInfoReqIdl_proto_msgTypes,
	}.Build()
	File_UpdateClientInfoReqIdl_proto = out.File
	file_UpdateClientInfoReqIdl_proto_goTypes = nil
	file_UpdateClientInfoReqIdl_proto_depIdxs = nil
}
