// tbclient.UserPost.UserPostReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: UserPostReqIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserPostReqIdl struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          *UserPostReqIdl_DataReq `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostReqIdl) Reset() {
	*x = UserPostReqIdl{}
	mi := &file_UserPostReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostReqIdl) ProtoMessage() {}

func (x *UserPostReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_UserPostReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostReqIdl.ProtoReflect.Descriptor instead.
func (*UserPostReqIdl) Descriptor() ([]byte, []int) {
	return file_UserPostReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *UserPostReqIdl) GetData() *UserPostReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserPostReqIdl_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rn            uint32                 `protobuf:"varint,2,opt,name=rn,proto3" json:"rn,omitempty"`
	IsThread      uint32                 `protobuf:"varint,4,opt,name=is_thread,json=isThread,proto3" json:"is_thread,omitempty"`
	NeedContent   uint32                 `protobuf:"varint,5,opt,name=need_content,json=needContent,proto3" json:"need_content,omitempty"`
	Pn            uint32                 `protobuf:"varint,26,opt,name=pn,proto3" json:"pn,omitempty"`
	IsViewCard    int32                  `protobuf:"varint,33,opt,name=is_view_card,json=isViewCard,proto3" json:"is_view_card,omitempty"`
	Common        *CommonReq             `protobuf:"bytes,27,opt,name=common,proto3" json:"common,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostReqIdl_DataReq) Reset() {
	*x = UserPostReqIdl_DataReq{}
	mi := &file_UserPostReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostReqIdl_DataReq) ProtoMessage() {}

func (x *UserPostReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserPostReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*UserPostReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_UserPostReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UserPostReqIdl_DataReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserPostReqIdl_DataReq) GetRn() uint32 {
	if x != nil {
		return x.Rn
	}
	return 0
}

func (x *UserPostReqIdl_DataReq) GetIsThread() uint32 {
	if x != nil {
		return x.IsThread
	}
	return 0
}

func (x *UserPostReqIdl_DataReq) GetNeedContent() uint32 {
	if x != nil {
		return x.NeedContent
	}
	return 0
}

func (x *UserPostReqIdl_DataReq) GetPn() uint32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *UserPostReqIdl_DataReq) GetIsViewCard() int32 {
	if x != nil {
		return x.IsViewCard
	}
	return 0
}

func (x *UserPostReqIdl_DataReq) GetCommon() *CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

var File_UserPostReqIdl_proto protoreflect.FileDescriptor

const file_UserPostReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x14UserPostReqIdl.proto\x1a\x0fCommonReq.proto\"\x88\x02\n" +
	"\x0eUserPostReqIdl\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.UserPostReqIdl.DataReqR\x04data\x1a\xc8\x01\n" +
	"\aDataReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02rn\x18\x02 \x01(\rR\x02rn\x12\x1b\n" +
	"\tis_thread\x18\x04 \x01(\rR\bisThread\x12!\n" +
	"\fneed_content\x18\x05 \x01(\rR\vneedContent\x12\x0e\n" +
	"\x02pn\x18\x1a \x01(\rR\x02pn\x12 \n" +
	"\fis_view_card\x18! \x01(\x05R\n" +
	"isViewCard\x12\"\n" +
	"\x06common\x18\x1b \x01(\v2\n" +
	".CommonReqR\x06commonB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_UserPostReqIdl_proto_rawDescOnce sync.Once
	file_UserPostReqIdl_proto_rawDescData []byte
)

func file_UserPostReqIdl_proto_rawDescGZIP() []byte {
	file_UserPostReqIdl_proto_rawDescOnce.Do(func() {
		file_UserPostReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_UserPostReqIdl_proto_rawDesc), len(file_UserPostReqIdl_proto_rawDesc)))
	})
	return file_UserPostReqIdl_proto_rawDescData
}

var file_UserPostReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_UserPostReqIdl_proto_goTypes = []any{
	(*UserPostReqIdl)(nil),         // 0: UserPostReqIdl
	(*UserPostReqIdl_DataReq)(nil), // 1: UserPostReqIdl.DataReq
	(*CommonReq)(nil),              // 2: CommonReq
}
var file_UserPostReqIdl_proto_depIdxs = []int32{
	1, // 0: UserPostReqIdl.data:type_name -> UserPostReqIdl.DataReq
	2, // 1: UserPostReqIdl.DataReq.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_UserPostReqIdl_proto_init() }
func file_UserPostReqIdl_proto_init() {
	if File_UserPostReqIdl_proto != nil {
		return
	}
	file_CommonReq_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_UserPostReqIdl_proto_rawDesc), len(file_UserPostReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UserPostReqIdl_proto_goTypes,
		DependencyIndexes: file_UserPostReqIdl_proto_depIdxs,
		MessageInfos:      file_UserPostReqIdl_proto_msgTypes,
	}.Build()
	File_UserPostReqIdl_proto = out.File
	file_UserPostReqIdl_proto_goTypes = nil
	file_UserPostReqIdl_proto_depIdxs = nil
}
