// tbclient.UserMuteQuery.UserMuteQueryReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: UserMuteQueryReqIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserMuteQueryReqIdl struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Data          *UserMuteQueryReqIdl_DataReq `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMuteQueryReqIdl) Reset() {
	*x = UserMuteQueryReqIdl{}
	mi := &file_UserMuteQueryReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMuteQueryReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMuteQueryReqIdl) ProtoMessage() {}

func (x *UserMuteQueryReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_UserMuteQueryReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMuteQueryReqIdl.ProtoReflect.Descriptor instead.
func (*UserMuteQueryReqIdl) Descriptor() ([]byte, []int) {
	return file_UserMuteQueryReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *UserMuteQueryReqIdl) GetData() *UserMuteQueryReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserMuteQueryReqIdl_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *CommonReq             `protobuf:"bytes,2,opt,name=common,proto3" json:"common,omitempty"`
	Pn            uint32                 `protobuf:"varint,4,opt,name=pn,proto3" json:"pn,omitempty"`
	Rn            uint32                 `protobuf:"varint,5,opt,name=rn,proto3" json:"rn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMuteQueryReqIdl_DataReq) Reset() {
	*x = UserMuteQueryReqIdl_DataReq{}
	mi := &file_UserMuteQueryReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMuteQueryReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMuteQueryReqIdl_DataReq) ProtoMessage() {}

func (x *UserMuteQueryReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserMuteQueryReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMuteQueryReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*UserMuteQueryReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_UserMuteQueryReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UserMuteQueryReqIdl_DataReq) GetCommon() *CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *UserMuteQueryReqIdl_DataReq) GetPn() uint32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *UserMuteQueryReqIdl_DataReq) GetRn() uint32 {
	if x != nil {
		return x.Rn
	}
	return 0
}

var File_UserMuteQueryReqIdl_proto protoreflect.FileDescriptor

const file_UserMuteQueryReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x19UserMuteQueryReqIdl.proto\x1a\x0fCommonReq.proto\"\x96\x01\n" +
	"\x13UserMuteQueryReqIdl\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.UserMuteQueryReqIdl.DataReqR\x04data\x1aM\n" +
	"\aDataReq\x12\"\n" +
	"\x06common\x18\x02 \x01(\v2\n" +
	".CommonReqR\x06common\x12\x0e\n" +
	"\x02pn\x18\x04 \x01(\rR\x02pn\x12\x0e\n" +
	"\x02rn\x18\x05 \x01(\rR\x02rnB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_UserMuteQueryReqIdl_proto_rawDescOnce sync.Once
	file_UserMuteQueryReqIdl_proto_rawDescData []byte
)

func file_UserMuteQueryReqIdl_proto_rawDescGZIP() []byte {
	file_UserMuteQueryReqIdl_proto_rawDescOnce.Do(func() {
		file_UserMuteQueryReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_UserMuteQueryReqIdl_proto_rawDesc), len(file_UserMuteQueryReqIdl_proto_rawDesc)))
	})
	return file_UserMuteQueryReqIdl_proto_rawDescData
}

var file_UserMuteQueryReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_UserMuteQueryReqIdl_proto_goTypes = []any{
	(*UserMuteQueryReqIdl)(nil),         // 0: UserMuteQueryReqIdl
	(*UserMuteQueryReqIdl_DataReq)(nil), // 1: UserMuteQueryReqIdl.DataReq
	(*CommonReq)(nil),                   // 2: CommonReq
}
var file_UserMuteQueryReqIdl_proto_depIdxs = []int32{
	1, // 0: UserMuteQueryReqIdl.data:type_name -> UserMuteQueryReqIdl.DataReq
	2, // 1: UserMuteQueryReqIdl.DataReq.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_UserMuteQueryReqIdl_proto_init() }
func file_UserMuteQueryReqIdl_proto_init() {
	if File_UserMuteQueryReqIdl_proto != nil {
		return
	}
	file_CommonReq_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_UserMuteQueryReqIdl_proto_rawDesc), len(file_UserMuteQueryReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UserMuteQueryReqIdl_proto_goTypes,
		DependencyIndexes: file_UserMuteQueryReqIdl_proto_depIdxs,
		MessageInfos:      file_UserMuteQueryReqIdl_proto_msgTypes,
	}.Build()
	File_UserMuteQueryReqIdl_proto = out.File
	file_UserMuteQueryReqIdl_proto_goTypes = nil
	file_UserMuteQueryReqIdl_proto_depIdxs = nil
}
