// tbclient.User

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: User.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NameShow        string                 `protobuf:"bytes,4,opt,name=name_show,json=nameShow,proto3" json:"name_show,omitempty"`
	Portrait        string                 `protobuf:"bytes,5,opt,name=portrait,proto3" json:"portrait,omitempty"`
	Iconinfo        []*User_Icon           `protobuf:"bytes,17,rep,name=iconinfo,proto3" json:"iconinfo,omitempty"`
	IsCoreuser      int32                  `protobuf:"varint,20,opt,name=is_coreuser,json=isCoreuser,proto3" json:"is_coreuser,omitempty"`
	LevelId         int32                  `protobuf:"varint,23,opt,name=level_id,json=levelId,proto3" json:"level_id,omitempty"`
	IsBawu          int32                  `protobuf:"varint,25,opt,name=is_bawu,json=isBawu,proto3" json:"is_bawu,omitempty"`
	BawuType        string                 `protobuf:"bytes,26,opt,name=bawu_type,json=bawuType,proto3" json:"bawu_type,omitempty"`
	BDUSS           string                 `protobuf:"bytes,29,opt,name=BDUSS,proto3" json:"BDUSS,omitempty"`
	FansNum         int32                  `protobuf:"varint,30,opt,name=fans_num,json=fansNum,proto3" json:"fans_num,omitempty"`
	ConcernNum      int32                  `protobuf:"varint,31,opt,name=concern_num,json=concernNum,proto3" json:"concern_num,omitempty"`
	Sex             int32                  `protobuf:"varint,32,opt,name=sex,proto3" json:"sex,omitempty"`
	MyLikeNum       int32                  `protobuf:"varint,33,opt,name=my_like_num,json=myLikeNum,proto3" json:"my_like_num,omitempty"`
	Intro           string                 `protobuf:"bytes,34,opt,name=intro,proto3" json:"intro,omitempty"`
	PostNum         int32                  `protobuf:"varint,37,opt,name=post_num,json=postNum,proto3" json:"post_num,omitempty"`
	TbAge           string                 `protobuf:"bytes,38,opt,name=tb_age,json=tbAge,proto3" json:"tb_age,omitempty"`
	Gender          int32                  `protobuf:"varint,42,opt,name=gender,proto3" json:"gender,omitempty"`
	PrivSets        *User_PrivSets         `protobuf:"bytes,45,opt,name=priv_sets,json=privSets,proto3" json:"priv_sets,omitempty"`
	IsFriend        int32                  `protobuf:"varint,46,opt,name=is_friend,json=isFriend,proto3" json:"is_friend,omitempty"`
	LikeForum       []*User_LikeForumInfo  `protobuf:"bytes,47,rep,name=likeForum,proto3" json:"likeForum,omitempty"`
	IsGuanfang      int32                  `protobuf:"varint,52,opt,name=is_guanfang,json=isGuanfang,proto3" json:"is_guanfang,omitempty"`
	VipInfo         *User_UserVipInfo      `protobuf:"bytes,61,opt,name=vipInfo,proto3" json:"vipInfo,omitempty"`
	NewTshowIcon    []*User_TshowInfo      `protobuf:"bytes,65,rep,name=new_tshow_icon,json=newTshowIcon,proto3" json:"new_tshow_icon,omitempty"`
	IsFans          int32                  `protobuf:"varint,91,opt,name=is_fans,json=isFans,proto3" json:"is_fans,omitempty"`
	NewGodData      *User_NewGodInfo       `protobuf:"bytes,101,opt,name=new_god_data,json=newGodData,proto3" json:"new_god_data,omitempty"`
	IsDefaultAvatar int32                  `protobuf:"varint,106,opt,name=is_default_avatar,json=isDefaultAvatar,proto3" json:"is_default_avatar,omitempty"`
	TiebaUid        string                 `protobuf:"bytes,120,opt,name=tieba_uid,json=tiebaUid,proto3" json:"tieba_uid,omitempty"`
	IpAddress       string                 `protobuf:"bytes,127,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserGrowth      *User_UserGrowth       `protobuf:"bytes,137,opt,name=user_growth,json=userGrowth,proto3" json:"user_growth,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_User_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_User_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_User_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetNameShow() string {
	if x != nil {
		return x.NameShow
	}
	return ""
}

func (x *User) GetPortrait() string {
	if x != nil {
		return x.Portrait
	}
	return ""
}

func (x *User) GetIconinfo() []*User_Icon {
	if x != nil {
		return x.Iconinfo
	}
	return nil
}

func (x *User) GetIsCoreuser() int32 {
	if x != nil {
		return x.IsCoreuser
	}
	return 0
}

func (x *User) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *User) GetIsBawu() int32 {
	if x != nil {
		return x.IsBawu
	}
	return 0
}

func (x *User) GetBawuType() string {
	if x != nil {
		return x.BawuType
	}
	return ""
}

func (x *User) GetBDUSS() string {
	if x != nil {
		return x.BDUSS
	}
	return ""
}

func (x *User) GetFansNum() int32 {
	if x != nil {
		return x.FansNum
	}
	return 0
}

func (x *User) GetConcernNum() int32 {
	if x != nil {
		return x.ConcernNum
	}
	return 0
}

func (x *User) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *User) GetMyLikeNum() int32 {
	if x != nil {
		return x.MyLikeNum
	}
	return 0
}

func (x *User) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *User) GetPostNum() int32 {
	if x != nil {
		return x.PostNum
	}
	return 0
}

func (x *User) GetTbAge() string {
	if x != nil {
		return x.TbAge
	}
	return ""
}

func (x *User) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *User) GetPrivSets() *User_PrivSets {
	if x != nil {
		return x.PrivSets
	}
	return nil
}

func (x *User) GetIsFriend() int32 {
	if x != nil {
		return x.IsFriend
	}
	return 0
}

func (x *User) GetLikeForum() []*User_LikeForumInfo {
	if x != nil {
		return x.LikeForum
	}
	return nil
}

func (x *User) GetIsGuanfang() int32 {
	if x != nil {
		return x.IsGuanfang
	}
	return 0
}

func (x *User) GetVipInfo() *User_UserVipInfo {
	if x != nil {
		return x.VipInfo
	}
	return nil
}

func (x *User) GetNewTshowIcon() []*User_TshowInfo {
	if x != nil {
		return x.NewTshowIcon
	}
	return nil
}

func (x *User) GetIsFans() int32 {
	if x != nil {
		return x.IsFans
	}
	return 0
}

func (x *User) GetNewGodData() *User_NewGodInfo {
	if x != nil {
		return x.NewGodData
	}
	return nil
}

func (x *User) GetIsDefaultAvatar() int32 {
	if x != nil {
		return x.IsDefaultAvatar
	}
	return 0
}

func (x *User) GetTiebaUid() string {
	if x != nil {
		return x.TiebaUid
	}
	return ""
}

func (x *User) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *User) GetUserGrowth() *User_UserGrowth {
	if x != nil {
		return x.UserGrowth
	}
	return nil
}

type User_Icon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Icon) Reset() {
	*x = User_Icon{}
	mi := &file_User_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Icon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Icon) ProtoMessage() {}

func (x *User_Icon) ProtoReflect() protoreflect.Message {
	mi := &file_User_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Icon.ProtoReflect.Descriptor instead.
func (*User_Icon) Descriptor() ([]byte, []int) {
	return file_User_proto_rawDescGZIP(), []int{0, 0}
}

func (x *User_Icon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type User_PrivSets struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Location         int32                  `protobuf:"varint,1,opt,name=location,proto3" json:"location,omitempty"`
	Like             int32                  `protobuf:"varint,2,opt,name=like,proto3" json:"like,omitempty"`
	Group            int32                  `protobuf:"varint,3,opt,name=group,proto3" json:"group,omitempty"`
	Post             int32                  `protobuf:"varint,4,opt,name=post,proto3" json:"post,omitempty"`
	Friend           int32                  `protobuf:"varint,5,opt,name=friend,proto3" json:"friend,omitempty"`
	Live             int32                  `protobuf:"varint,6,opt,name=live,proto3" json:"live,omitempty"`
	Reply            int32                  `protobuf:"varint,7,opt,name=reply,proto3" json:"reply,omitempty"`
	BazhuShowInside  int32                  `protobuf:"varint,8,opt,name=bazhu_show_inside,json=bazhuShowInside,proto3" json:"bazhu_show_inside,omitempty"`
	BazhuShowOutside int32                  `protobuf:"varint,9,opt,name=bazhu_show_outside,json=bazhuShowOutside,proto3" json:"bazhu_show_outside,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *User_PrivSets) Reset() {
	*x = User_PrivSets{}
	mi := &file_User_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_PrivSets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_PrivSets) ProtoMessage() {}

func (x *User_PrivSets) ProtoReflect() protoreflect.Message {
	mi := &file_User_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_PrivSets.ProtoReflect.Descriptor instead.
func (*User_PrivSets) Descriptor() ([]byte, []int) {
	return file_User_proto_rawDescGZIP(), []int{0, 1}
}

func (x *User_PrivSets) GetLocation() int32 {
	if x != nil {
		return x.Location
	}
	return 0
}

func (x *User_PrivSets) GetLike() int32 {
	if x != nil {
		return x.Like
	}
	return 0
}

func (x *User_PrivSets) GetGroup() int32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *User_PrivSets) GetPost() int32 {
	if x != nil {
		return x.Post
	}
	return 0
}

func (x *User_PrivSets) GetFriend() int32 {
	if x != nil {
		return x.Friend
	}
	return 0
}

func (x *User_PrivSets) GetLive() int32 {
	if x != nil {
		return x.Live
	}
	return 0
}

func (x *User_PrivSets) GetReply() int32 {
	if x != nil {
		return x.Reply
	}
	return 0
}

func (x *User_PrivSets) GetBazhuShowInside() int32 {
	if x != nil {
		return x.BazhuShowInside
	}
	return 0
}

func (x *User_PrivSets) GetBazhuShowOutside() int32 {
	if x != nil {
		return x.BazhuShowOutside
	}
	return 0
}

type User_LikeForumInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForumName     string                 `protobuf:"bytes,1,opt,name=forum_name,json=forumName,proto3" json:"forum_name,omitempty"`
	ForumId       uint64                 `protobuf:"varint,2,opt,name=forum_id,json=forumId,proto3" json:"forum_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_LikeForumInfo) Reset() {
	*x = User_LikeForumInfo{}
	mi := &file_User_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_LikeForumInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_LikeForumInfo) ProtoMessage() {}

func (x *User_LikeForumInfo) ProtoReflect() protoreflect.Message {
	mi := &file_User_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_LikeForumInfo.ProtoReflect.Descriptor instead.
func (*User_LikeForumInfo) Descriptor() ([]byte, []int) {
	return file_User_proto_rawDescGZIP(), []int{0, 2}
}

func (x *User_LikeForumInfo) GetForumName() string {
	if x != nil {
		return x.ForumName
	}
	return ""
}

func (x *User_LikeForumInfo) GetForumId() uint64 {
	if x != nil {
		return x.ForumId
	}
	return 0
}

type User_UserVipInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VStatus       uint32                 `protobuf:"varint,1,opt,name=v_status,json=vStatus,proto3" json:"v_status,omitempty"`
	VLevel        uint32                 `protobuf:"varint,5,opt,name=v_level,json=vLevel,proto3" json:"v_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_UserVipInfo) Reset() {
	*x = User_UserVipInfo{}
	mi := &file_User_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_UserVipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_UserVipInfo) ProtoMessage() {}

func (x *User_UserVipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_User_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_UserVipInfo.ProtoReflect.Descriptor instead.
func (*User_UserVipInfo) Descriptor() ([]byte, []int) {
	return file_User_proto_rawDescGZIP(), []int{0, 3}
}

func (x *User_UserVipInfo) GetVStatus() uint32 {
	if x != nil {
		return x.VStatus
	}
	return 0
}

func (x *User_UserVipInfo) GetVLevel() uint32 {
	if x != nil {
		return x.VLevel
	}
	return 0
}

type User_TshowInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_TshowInfo) Reset() {
	*x = User_TshowInfo{}
	mi := &file_User_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_TshowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_TshowInfo) ProtoMessage() {}

func (x *User_TshowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_User_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_TshowInfo.ProtoReflect.Descriptor instead.
func (*User_TshowInfo) Descriptor() ([]byte, []int) {
	return file_User_proto_rawDescGZIP(), []int{0, 4}
}

func (x *User_TshowInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type User_NewGodInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	FieldId       uint32                 `protobuf:"varint,2,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	FieldName     string                 `protobuf:"bytes,3,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_NewGodInfo) Reset() {
	*x = User_NewGodInfo{}
	mi := &file_User_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_NewGodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_NewGodInfo) ProtoMessage() {}

func (x *User_NewGodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_User_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_NewGodInfo.ProtoReflect.Descriptor instead.
func (*User_NewGodInfo) Descriptor() ([]byte, []int) {
	return file_User_proto_rawDescGZIP(), []int{0, 5}
}

func (x *User_NewGodInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User_NewGodInfo) GetFieldId() uint32 {
	if x != nil {
		return x.FieldId
	}
	return 0
}

func (x *User_NewGodInfo) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

type User_UserGrowth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LevelId       uint32                 `protobuf:"varint,1,opt,name=level_id,json=levelId,proto3" json:"level_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_UserGrowth) Reset() {
	*x = User_UserGrowth{}
	mi := &file_User_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_UserGrowth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_UserGrowth) ProtoMessage() {}

func (x *User_UserGrowth) ProtoReflect() protoreflect.Message {
	mi := &file_User_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_UserGrowth.ProtoReflect.Descriptor instead.
func (*User_UserGrowth) Descriptor() ([]byte, []int) {
	return file_User_proto_rawDescGZIP(), []int{0, 6}
}

func (x *User_UserGrowth) GetLevelId() uint32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

var File_User_proto protoreflect.FileDescriptor

const file_User_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"User.proto\"\xa3\f\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tname_show\x18\x04 \x01(\tR\bnameShow\x12\x1a\n" +
	"\bportrait\x18\x05 \x01(\tR\bportrait\x12&\n" +
	"\biconinfo\x18\x11 \x03(\v2\n" +
	".User.IconR\biconinfo\x12\x1f\n" +
	"\vis_coreuser\x18\x14 \x01(\x05R\n" +
	"isCoreuser\x12\x19\n" +
	"\blevel_id\x18\x17 \x01(\x05R\alevelId\x12\x17\n" +
	"\ais_bawu\x18\x19 \x01(\x05R\x06isBawu\x12\x1b\n" +
	"\tbawu_type\x18\x1a \x01(\tR\bbawuType\x12\x14\n" +
	"\x05BDUSS\x18\x1d \x01(\tR\x05BDUSS\x12\x19\n" +
	"\bfans_num\x18\x1e \x01(\x05R\afansNum\x12\x1f\n" +
	"\vconcern_num\x18\x1f \x01(\x05R\n" +
	"concernNum\x12\x10\n" +
	"\x03sex\x18  \x01(\x05R\x03sex\x12\x1e\n" +
	"\vmy_like_num\x18! \x01(\x05R\tmyLikeNum\x12\x14\n" +
	"\x05intro\x18\" \x01(\tR\x05intro\x12\x19\n" +
	"\bpost_num\x18% \x01(\x05R\apostNum\x12\x15\n" +
	"\x06tb_age\x18& \x01(\tR\x05tbAge\x12\x16\n" +
	"\x06gender\x18* \x01(\x05R\x06gender\x12+\n" +
	"\tpriv_sets\x18- \x01(\v2\x0e.User.PrivSetsR\bprivSets\x12\x1b\n" +
	"\tis_friend\x18. \x01(\x05R\bisFriend\x121\n" +
	"\tlikeForum\x18/ \x03(\v2\x13.User.LikeForumInfoR\tlikeForum\x12\x1f\n" +
	"\vis_guanfang\x184 \x01(\x05R\n" +
	"isGuanfang\x12+\n" +
	"\avipInfo\x18= \x01(\v2\x11.User.UserVipInfoR\avipInfo\x125\n" +
	"\x0enew_tshow_icon\x18A \x03(\v2\x0f.User.TshowInfoR\fnewTshowIcon\x12\x17\n" +
	"\ais_fans\x18[ \x01(\x05R\x06isFans\x122\n" +
	"\fnew_god_data\x18e \x01(\v2\x10.User.NewGodInfoR\n" +
	"newGodData\x12*\n" +
	"\x11is_default_avatar\x18j \x01(\x05R\x0fisDefaultAvatar\x12\x1b\n" +
	"\ttieba_uid\x18x \x01(\tR\btiebaUid\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x7f \x01(\tR\tipAddress\x122\n" +
	"\vuser_growth\x18\x89\x01 \x01(\v2\x10.User.UserGrowthR\n" +
	"userGrowth\x1a\x1a\n" +
	"\x04Icon\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a\x80\x02\n" +
	"\bPrivSets\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\x05R\blocation\x12\x12\n" +
	"\x04like\x18\x02 \x01(\x05R\x04like\x12\x14\n" +
	"\x05group\x18\x03 \x01(\x05R\x05group\x12\x12\n" +
	"\x04post\x18\x04 \x01(\x05R\x04post\x12\x16\n" +
	"\x06friend\x18\x05 \x01(\x05R\x06friend\x12\x12\n" +
	"\x04live\x18\x06 \x01(\x05R\x04live\x12\x14\n" +
	"\x05reply\x18\a \x01(\x05R\x05reply\x12*\n" +
	"\x11bazhu_show_inside\x18\b \x01(\x05R\x0fbazhuShowInside\x12,\n" +
	"\x12bazhu_show_outside\x18\t \x01(\x05R\x10bazhuShowOutside\x1aI\n" +
	"\rLikeForumInfo\x12\x1d\n" +
	"\n" +
	"forum_name\x18\x01 \x01(\tR\tforumName\x12\x19\n" +
	"\bforum_id\x18\x02 \x01(\x04R\aforumId\x1aA\n" +
	"\vUserVipInfo\x12\x19\n" +
	"\bv_status\x18\x01 \x01(\rR\avStatus\x12\x17\n" +
	"\av_level\x18\x05 \x01(\rR\x06vLevel\x1a\x1f\n" +
	"\tTshowInfo\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1a^\n" +
	"\n" +
	"NewGodInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x19\n" +
	"\bfield_id\x18\x02 \x01(\rR\afieldId\x12\x1d\n" +
	"\n" +
	"field_name\x18\x03 \x01(\tR\tfieldName\x1a'\n" +
	"\n" +
	"UserGrowth\x12\x19\n" +
	"\blevel_id\x18\x01 \x01(\rR\alevelIdB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_User_proto_rawDescOnce sync.Once
	file_User_proto_rawDescData []byte
)

func file_User_proto_rawDescGZIP() []byte {
	file_User_proto_rawDescOnce.Do(func() {
		file_User_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_User_proto_rawDesc), len(file_User_proto_rawDesc)))
	})
	return file_User_proto_rawDescData
}

var file_User_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_User_proto_goTypes = []any{
	(*User)(nil),               // 0: User
	(*User_Icon)(nil),          // 1: User.Icon
	(*User_PrivSets)(nil),      // 2: User.PrivSets
	(*User_LikeForumInfo)(nil), // 3: User.LikeForumInfo
	(*User_UserVipInfo)(nil),   // 4: User.UserVipInfo
	(*User_TshowInfo)(nil),     // 5: User.TshowInfo
	(*User_NewGodInfo)(nil),    // 6: User.NewGodInfo
	(*User_UserGrowth)(nil),    // 7: User.UserGrowth
}
var file_User_proto_depIdxs = []int32{
	1, // 0: User.iconinfo:type_name -> User.Icon
	2, // 1: User.priv_sets:type_name -> User.PrivSets
	3, // 2: User.likeForum:type_name -> User.LikeForumInfo
	4, // 3: User.vipInfo:type_name -> User.UserVipInfo
	5, // 4: User.new_tshow_icon:type_name -> User.TshowInfo
	6, // 5: User.new_god_data:type_name -> User.NewGodInfo
	7, // 6: User.user_growth:type_name -> User.UserGrowth
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_User_proto_init() }
func file_User_proto_init() {
	if File_User_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_User_proto_rawDesc), len(file_User_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_User_proto_goTypes,
		DependencyIndexes: file_User_proto_depIdxs,
		MessageInfos:      file_User_proto_msgTypes,
	}.Build()
	File_User_proto = out.File
	file_User_proto_goTypes = nil
	file_User_proto_depIdxs = nil
}
