// tbclient.UserPost.UserPostResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: UserPostResIdl.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserPostResIdl struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Error         *Error                  `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *UserPostResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostResIdl) Reset() {
	*x = UserPostResIdl{}
	mi := &file_UserPostResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostResIdl) ProtoMessage() {}

func (x *UserPostResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_UserPostResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostResIdl.ProtoReflect.Descriptor instead.
func (*UserPostResIdl) Descriptor() ([]byte, []int) {
	return file_UserPostResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *UserPostResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *UserPostResIdl) GetData() *UserPostResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserPostResIdl_DataRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostList      []*PostInfoList        `protobuf:"bytes,1,rep,name=post_list,json=postList,proto3" json:"post_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostResIdl_DataRes) Reset() {
	*x = UserPostResIdl_DataRes{}
	mi := &file_UserPostResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostResIdl_DataRes) ProtoMessage() {}

func (x *UserPostResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_UserPostResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*UserPostResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_UserPostResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UserPostResIdl_DataRes) GetPostList() []*PostInfoList {
	if x != nil {
		return x.PostList
	}
	return nil
}

var File_UserPostResIdl_proto protoreflect.FileDescriptor

const file_UserPostResIdl_proto_rawDesc = "" +
	"\n" +
	"\x14UserPostResIdl.proto\x1a\vError.proto\x1a\x12PostInfoList.proto\"\x92\x01\n" +
	"\x0eUserPostResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.UserPostResIdl.DataResR\x04data\x1a5\n" +
	"\aDataRes\x12*\n" +
	"\tpost_list\x18\x01 \x03(\v2\r.PostInfoListR\bpostListB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_UserPostResIdl_proto_rawDescOnce sync.Once
	file_UserPostResIdl_proto_rawDescData []byte
)

func file_UserPostResIdl_proto_rawDescGZIP() []byte {
	file_UserPostResIdl_proto_rawDescOnce.Do(func() {
		file_UserPostResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_UserPostResIdl_proto_rawDesc), len(file_UserPostResIdl_proto_rawDesc)))
	})
	return file_UserPostResIdl_proto_rawDescData
}

var file_UserPostResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_UserPostResIdl_proto_goTypes = []any{
	(*UserPostResIdl)(nil),         // 0: UserPostResIdl
	(*UserPostResIdl_DataRes)(nil), // 1: UserPostResIdl.DataRes
	(*Error)(nil),                  // 2: Error
	(*PostInfoList)(nil),           // 3: PostInfoList
}
var file_UserPostResIdl_proto_depIdxs = []int32{
	2, // 0: UserPostResIdl.error:type_name -> Error
	1, // 1: UserPostResIdl.data:type_name -> UserPostResIdl.DataRes
	3, // 2: UserPostResIdl.DataRes.post_list:type_name -> PostInfoList
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_UserPostResIdl_proto_init() }
func file_UserPostResIdl_proto_init() {
	if File_UserPostResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	file_PostInfoList_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_UserPostResIdl_proto_rawDesc), len(file_UserPostResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UserPostResIdl_proto_goTypes,
		DependencyIndexes: file_UserPostResIdl_proto_depIdxs,
		MessageInfos:      file_UserPostResIdl_proto_msgTypes,
	}.Build()
	File_UserPostResIdl_proto = out.File
	file_UserPostResIdl_proto_goTypes = nil
	file_UserPostResIdl_proto_depIdxs = nil
}
